<?php //msql/connectors_codeline_sav
$r=["_"=>['value'],
"balise"=>['value§balise|id|class'],
"html"=>['value§balise'],
"div"=>['value§attributs'],
"span"=>['value§attributs'],
"css"=>['value§class'],
"br"=>[''],
"id"=>['attribut'],
"class"=>['attribut'],
"style"=>['attribut'],
"name"=>['attribut'],
"text"=>['value'],
"url"=>['value§param'],
"link"=>['value§param'],
"anchor"=>['value'],
"date"=>['value§param'],
"title"=>['param'],
"read"=>['ID§preview'],
"image"=>['value'],
"thumb"=>['value§width/height'],
"split"=>['string§cutter'],
"cut"=>['text§start/end'],
"conn"=>['connparams§conn'],
"plug"=>['plug§param'],
"core"=>['p1/p2/p3§function']]; ?>