<?php //msql/connectors_old_sav
$r=["_"=>['new'],
"{{"=>['['],
"}}"=>[':q]'],
".tit"=>[':h'],
":tit"=>[':h'],
".tib"=>[':h4'],
":tib"=>[':h4'],
":pub1"=>['§1:pub'],
":pub2"=>['§2:pub'],
":pub3"=>['§3:pub'],
":livestream"=>[':video'],
":dailymotion"=>[':video'],
":youtube"=>[':video'],
":google"=>[':video'],
":vimeo"=>[':video'],
":ted"=>[':video'],
":jukebox2"=>['§2:jukebox'],
"msq_template"=>[':microtemplate'],
"msq_ads"=>[':msq_html'],
"microform"=>[':msq_conn'],
"popvideo"=>['§1:video']]; ?>