<?php 
return ["_menus_"=>['button','type','process','param','option','condition','root','icon','hide','private'],
"1"=>['home','link','','/home','','menu','','home','',''],
"2"=>['home','url','','/home','','menu','','home','',''],
"3"=>['all','url','','all','','menu','','globe','',''],
"4"=>['admin','url','','/?admin==&log=open','','menu','','admin','',''],
"5"=>['codev','plug','plug','codev_plug_lib','','menu','dev','edit','','7'],
"16"=>['exec','plug','plug','exec_plug_lib','','menu','dev','edit','','7'],
"6"=>['root','ajax','popup','desktop___desk','','menu','','folder2','',''],
"7"=>['philumsize','link','','/plugin/philumsize','','menu','dev','phi','','6'],
"8"=>['desk','ajax','desktop','desk','','menu','','folder','',''],
"9"=>['folder','ajax','popup','modpop__3_local|real//////folder2///1:desktop*files_480','','menu','','folder','',''],
"10"=>['article','ajax','popup','popart__3_ID_3','','menu','','articles','',''],
"11"=>['search','ajax','popup','search','','menu','','search','',''],
"12"=>['taxonav','ajax','popup','plup___taxonav','','menu','','topo','',''],
"13"=>['taxonav','plug','taxonav','','','menu','','topo','','']]; ?>