<?php //msql/default_desktop_sav
$r=["_"=>['button','type','process','param','option','private','hide','icon','root'],
"1"=>['Desktop','ajax','page','deskload','','','','admin',''],
"2"=>['Home','ajax','page','deskoff___module_Home','','','','home',''],
"4"=>['site','ajax','popup','site___desktop_ok__autosize','','','1','global',''],
"5"=>['new art','ajax','popup','addArt____1','','','1','add',''],
"6"=>['finder','finder','','','shared/global//flap///mini_1 ','','','network',''],
"7"=>['recherche','ajax','popup','search__3','','','','search',''],
"8"=>['article','art','auto','418','','','1','articles',''],
"9"=>['editor','admin','editor','','','1','','edit','edit'],
"10"=>['sText','plug','stext','','','','','editor','edit'],
"11"=>['sticky','plug','sticky','','self','','','sticky','edit'],
"12"=>['notepad','plug','notepad','','','','','editor','edit'],
"13"=>['mail','plug','mail','','','','','mail','com'],
"14"=>['chat','plug','chat','','','','','chat','com'],
"15"=>['twitter','plug','twitter','revolution','','','','chat','com'],
"16"=>['update-notes','msql','system','program','updates*1302','','1','server','user'],
"17"=>['updates-table','ajax','popup','msql___system_program_updates*1304','','1','','msql','user'],
"18"=>['connectors','ajax','popup','msql___system_connectors_all','','','1','msql','user'],
"19"=>['nominations','ajax','popup','msql___lang_helps_nominations','','','1','msql','user'],
"20"=>['helps','ajax','popup','msql___lang_helps_txts','','','1','msql','user'],
"21"=>['recents','mod','recents','public','/scroll/25','','','get','user'],
"22"=>['system','admin','console','system','','1','','builders','user'],
"23"=>['ixquick','link','','https://startpage.com/fra/','','','1','search','com'],
"24"=>['web','plug','ixquick','','','','','search','com'],
"25"=>['iframe','plug','ifram','','','','','search','com'],
"26"=>['tools','ajax','popup','desktop___tools','','','','folder2','']];