<?php //msql/default_params_sav
$r=["_"=>['default','name'],
"1"=>['1','modules_table'],
"2"=>['','auto_member'],
"3"=>['400','kmax'],
"4"=>['','viewport'],
"5"=>['','title_image_font'],
"6"=>['20','nb_arts_by_page'],
"9"=>['id DESC','art_order'],
"11"=>['','new_users'],
"16"=>['','nb_days'],
"17"=>['ymd','date_format'],
"18"=>['auteurs','usertags'],
"21"=>['puce.gif puce.png pix.gif imprimer.gif envoyer.gif filet.gif vide.gif shim.gif transpix.gif triangle.gif pdf.gif print.gif email.gif doc.png pixel.gif trans.gif printer.png ','forbidden_images'],
"23"=>['.7z.psd.rar.pps ','upload_extensions'],
"25"=>['LANG','lang'],
"26"=>['fr eng esp','articles_lang'],
"27"=>['140/140','thumbnails_size'],
"19"=>['','usertags:pictos']]; ?>