<?php //msql/default_mods_sav
$r=["_"=>['block','module','param','title','condition','command','option','cache','hide','template','nobr'],
"1"=>['system','blocks','menu content footer','','','','','','','',''],
"2"=>['system','content','700','','','','','','',''],
"3"=>['content','Page_titles','','','cat','','','','','','1'],
"4"=>['footer','codeline','[[36495§newsnet:url]§txtsmall2:css]','','','','','','','','1'],
"5"=>['footer','contact','','contact','','','','','','','1'],
"6"=>['footer','codeline','[[/rss/newsnet§rss:url]§txtsmall2:css]','','','','','','','','1'],
"7"=>['footer','link','rss','','','','1','','1','','1'],
"8"=>['footer','chrono','','','','','','','','','1'],
"9"=>['content','prev_next','','','art','','','','','','1'],
"10"=>['system','design','30','','','','','','','',''],
"11"=>['content','Page_titles','','','art','','parent','','','','1'],
"12"=>['system','template','','','','','','','','',''],
"13"=>['newsletter','articles','priority=4~nbdays=1','Articles épiques','','multi','','','','',''],
"14"=>['newsletter','taxo_nav','Structure des articles','','','','','','1','',''],
"15"=>['system','art_mod','related_arts§lié à,
related_by§lié par,
tags/Tags/scroll/7:see_also-tags§tags,
auteurs//scroll/7:see_also-usertags§auteurs,
thèmes//scroll/7:see_also-usertags§thèmes,
pays//scroll/7:see_also-usertags§pays,
//scroll/7:see_also-source§source,
taxo_arts§taxo','','','tabmods','300','','',''],
"16"=>['content','LOAD','','','art','','','','','','1'],
"17"=>['content','related_arts','Voir aussi','','art','cols','2','','','',''],
"19"=>['content','articles','priority=4&nbhours=12','','home','articles','','','','','1'],
"20"=>['newsletter','articles','nbdays=1~nopriority=1~nopriority=4~preview=auto','Grands titres / 24h','','multi','','','','',''],
"21"=>['content','LOAD','','','cat','','2','','','','1'],
"22"=>['newsletter','articles','priority=1~nbdays=1~preview=false','Actu','','multi','','','','',''],
"23"=>['content','Page_titles','','','home','','parent','','','','1'],
"24"=>['content','related_by','Cet article est référencé par :','','art','cols','2','','',''],
"25"=>['','','/?module=10/dossiers/articles:folders','Evénements','','','','','','','1'],
"26"=>['menu','link','home§home:picto','','','','','','','','1'],
"27"=>['menu','link','all§globe:picto','','','','','','','','1'],
"28"=>['menu','link','/module/taxonav/Déroulements§topo:picto','','','','','','','','1'],
"29"=>['menu','link','/module/folders/10/Dossiers/articles§folder2:picto','','','','','','','','1'],
"30"=>['menu','link','/module/video/30/Vidéos/articles§video:picto','','','','','','','','1'],
"31"=>['menu','link','/module/most_read/7-24/Les plus lus/cols§view:picto','','','','','','','','1'],
"32"=>['menu','link','/module/rssin§rss:picto','','','','','','','','1'],
"33"=>['menu','link','/module/tracks§forum:picto','','','','','','','','1'],
"34"=>['menu','link','/module/suggest§edit:picto','','','','','','','','1'],
"35"=>['menu','MenusJ','//cols/4////1:categories§list:picto,
//cols/4////1:tags§tag:picto,
auteurs//cols/3////1:usertags§user:picto,
thèmes//cols/4////1:usertags§sticky:picto,
pays//cols/5////1:usertags§flag:picto,
type//cols/3////1:usertags§info:picto,
//cols/2////1:sources§url:picto','','','togup','closed','','','','1'],
"36"=>['content','MenusJ','priority=>1&priority=<4&nbdays=4&preview=auto//multi:articles§Unes,
priority=1&nbdays=2&preview=1//multi:articles§faits,
priority=>2&nbdays=7&preview=2//multi:articles§semaine,
priority=>3&nbdays=300&preview=1//multi:articles§long terme','','home','onplace','notcloseable','','','','1']]; ?>