<?php //msql/program_core_sav
$r=["_"=>['function','variables','usage','return','context'],
"1"=>['p','r','print_r()','','html'],
"2"=>['br','','','br balise','html'],
"3"=>['hr','','','hr balise','html'],
"4"=>['sep','','separator','','html'],
"5"=>['atb','d,v','html attribut','d=\"v\"','html'],
"6"=>['atc','d','class attribut','','html'],
"7"=>['atd','d','id attribut','','html'],
"8"=>['ats','d','style attribut','','html'],
"9"=>['atn','d','name attribut','','html'],
"10"=>['atv','d','value attribut','','html'],
"11"=>['atz','d','size attribut','','html'],
"12"=>['atj','d,j','javascript prop and attribut','(\'j\');','html'],
"13"=>['atjb','r','multiple javascript attributs','','html'],
"14"=>['sj','d','javascript function SaveJ','SaveJ(\'sj\');','html'],
"15"=>['atbb','d','multiple attributs: class|id|style','','html'],
"16"=>['atr','r','multiple props and attributs','','html'],
"17"=>['ul','v','balise','embed content','html'],
"18"=>['li','v','balise','embed content','html'],
"19"=>['bal','b,v','b=balise v=value','balise html','html'],
"20"=>['balc','b,c,v','balise class value','','html'],
"21"=>['balb','b,p,v','balise, free manual props, value','','html'],
"22"=>['balr','b,r,v','','','html'],
"23"=>['balise','b,r,v','b=balise r=attributs t=text :: 
attributs_rule : use key instead of name of property :
array(1=>\"type\",2=>\"name\",3=>\"id\",4=>\"value\",5=>\"class\",6=>\"size\",7=>\"maxlenght\",8=>\"onKeyPress\",9=>\"cols\",10=>\"rows\",11=>\"wrap\",12=>\"action\",13=>\"method\",14=>\"for\",15=>\"onchange\",16=>\"style\")','html balise from an array of attributes','html'],
"24"=>['span','p,v','free props, value','span balise','html'],
"25"=>['btn','c,v','class text','span balise','html'],
"26"=>['btd','d,v','id txt','span balise with id value','html'],
"27"=>['bts','d,v','style value','span balise','html'],
"28"=>['div','p,v','attributs value','div balise','html'],
"29"=>['divb','p,v','class|is|style value','div balise','html'],
"30"=>['divc','c,v','class value','div balise','html'],
"31"=>['divd','d,v','id value','div balise','html'],
"32"=>['divs','s,v','style text','div balise','html'],
"33"=>['button','c,j,v','class javascript text','html button','html'],
"34"=>['lka','l,v=\'\'','link value','a balise, display domain only','html'],
"35"=>['lkc','c,l,v','class link value','a balise','html'],
"36"=>['lkt','c,l,v','class link value','a balise with target=_blank','html'],
"37"=>['lkh','oc,ov,v,c=\'\'','onclick js, onhover js, value, class','a balise','html'],
"38"=>['llk','c,l,v','class link value','a balise inside a li balise','html'],
"39"=>['submitj','c,id,v','button javascript','button balise','html'],
"40"=>['lja','j,v,c','','','html'],
"41"=>['lj','c,j,v,o=\'\'','class js text','a balise with javascript function \'SaveJ\' - shortcut to lc()','html'],
"42"=>['ljb','c,p,j,v,a=\'\'','class, js function as attribut, js prop, value, 1=onmouseover else onclick','a balise with js and mouseover ability','html'],
"43"=>['ljc','c,d,j,v,o=\'\',p=\'\'','js button calling a core function :
class, target, js, value, ajaxmode (3=display loading), \'p\' for popup','a balise','html'],
"44"=>['ljh','c,j,v','on mouseover with timing and autoclose','a balise','html'],
"45"=>['blj','c,id,j,v','using id as target for answer of ajax','a balise in span balise','html'],
"46"=>['llj','c,j,v,id=\'\',a=\'\'','class, js, value, id of li, 1=mouseover','a balise in li balise','html'],
"47"=>['image','d,w=\'\',h=\'\',p=\'\'','image width height props','html embed image','html'],
"48"=>['img','d','image at 100%','img balise','html'],
"49"=>['rolloverimg','a,b','switch image on rollover','img button','html'],
"50"=>['etc','d,n','cut text at n pos and add \"...\"','','html'],
"51"=>['attr','r','','','html'],
"52"=>['input','t,d,v,c=\'\',h=\'\',s=\'\'','type: 1,0 (text,hidden) or any input_type ; id value class','input text for forms','forms'],
"53"=>['input1','d,v,s=\'\',c=\'\'','id value size class','input balise','forms'],
"54"=>['input2','t,n,v,c=\'\'','type name value class','input text for forms','forms'],
"55"=>['autoclic','n,v,s,mx,c,h=\'\'','input text auto-hide content','balise input with javascript','forms'],
"56"=>['jholder','v','old javascript holder','','forms'],
"57"=>['hidden','n,d,v','name id value','input for forms ','forms'],
"58"=>['checkbox','n,v,t,chk','chk=0/1 if checked','checkbox for a form','forms'],
"59"=>['offon','d','','picto true or false','forms'],
"60"=>['checkbox_j','id,v,t=\'\',b=\'\'','','','forms'],
"61"=>['checkbob','id,v,a,b','','','forms'],
"62"=>['checkact','id,v,t','','','forms'],
"63"=>['label','id,c,s,t','id class style text','label balise connected to id_input (for=\"id\")','forms'],
"64"=>['radiobuttons','r,h','array checked_key','radio balises from keys of array','forms'],
"65"=>['btnsav','c,id,j','','','forms'],
"66"=>['txarea','n,d,cl,rw,c=\'\'','name text cols rows','text area','forms'],
"67"=>['txareac_btns','','','','forms'],
"68"=>['txareac','id,c,s,j,d','','','forms'],
"69"=>['divedit','id,c,s,j,d','','','forms'],
"70"=>['txarea1','msg,cont','msg, art or track (0/1), continue value (0/1)','textarea used for edit articles, callable from ajax','forms'],
"71"=>['form','go,d','','','forms'],
"72"=>['goodarea','v,id,css,j,n','jv=javascripts n=size or cols','balise input text or a textarea','forms'],
"73"=>['goodarea_b','v,id,c,j,n,h','','','forms'],
"74"=>['imgform','here,d,t=\'\'','here=url to call cl=class oth=text ttl=title attribut (on rollover)','upload form','forms'],
"75"=>['upload','d,p','','','forms'],
"76"=>['upload_btn','id,j,t','','','forms'],
"77"=>['loadjs','f,d,t=\'\'','','','forms'],
"78"=>['connect','','','','mysql'],
"79"=>['rcptb','db','show tables','mysql_query','mysql'],
"80"=>['lstrc','rq','make array from range 0 in mysql_fetch_array','array','mysql'],
"81"=>['msq','ph,bz','build sequence for res() from ph=SELECT attributs and bz=WHERE attributs','formated string','mysql'],
"82"=>['qr','r','used by rse() and ser()','mysql_fetch_array','mysql'],
"83"=>['qra','r','','','mysql'],
"84"=>['qrw','r','','','mysql'],
"85"=>['res','ph,bz','ph=asked columns bz=where condition','object mysql_fetch_array','mysql'],
"86"=>['ser','ph,bz','multiple datas of an entry in ph where bz','simple array to use in list($a,$b)=ser($ph,$bz)','mysql'],
"87"=>['rse','ph,bz','ph=asked column bz=where condition','string result','mysql'],
"88"=>['msquery','sql','','','mysql'],
"89"=>['insert','b,d','','','mysql'],
"90"=>['update','bs,in,v,col,id','UPDATE bs SET in=v WHERE col=id','nothing (and no error)','mysql'],
"91"=>['squ','bs,v,w','','','mysql'],
"92"=>['delete','bs,id','delete in bs where id','nothing','mysql'],
"93"=>['reflush','bs,o=\'\'','ALTER TABLE bs ORDER BY id :: used by delete()','nothing','mysql'],
"94"=>['lastid','bs','sql command','id of most recent entry','mysql'],
"95"=>['sqv','d,n=\'\',b=\'\'','','','mysql'],
"96"=>['sqlformat','rq,p','','','mysql'],
"97"=>['sql','d,b,p,q,bug=\'\'','','','mysql'],
"98"=>['sql_b','sql,p,b=\'\'','','','mysql'],
"99"=>['meta','d,v,c','meta d=v and content=c','used by headers','headers'],
"100"=>['css_link','d,m=\'\'','link to css','used by headers','headers'],
"101"=>['js_link','d','js link','used by headers','headers'],
"102"=>['css_code','d','css code','used by headers','headers'],
"103"=>['js_code','d','js code','used by headers','headers'],
"104"=>['temporize','name,func,p','name of the function, func=content, p=milliseconds :: temporize() will call a javascript cuntion every p seconds','javascript','headers'],
"105"=>['relod','v','reload to a page','javascript immediately applied','headers'],
"106"=>['header_add','d,v','','','headers'],
"107"=>['headers_balises','r','','used by headers','headers'],
"108"=>['headers_r','t,r=\'\'','','','headers'],
"109"=>['mkdir_r','u','build directories topology from a string like dir1/dir11/dir111','nothing','dirs'],
"110"=>['rmdir_r','dr','path dir file topo_number','delete files of a directory, including other dirs ;
option of explode_dir function (used inside a routine)','dirs'],
"111"=>['read_file','f','open datas from fil f','text','dirs'],
"112"=>['write_file','f,t','file_url text to save in f','save file on server','dirs'],
"113"=>['get_file','f','','','dirs'],
"114"=>['file_get_context','f','','','dirs'],
"115"=>['curl_get_contents','f','','','dirs'],
"116"=>['joinable','d','','','dirs'],
"117"=>['explore','dr,p=\'\',o=\'\'','','','files'],
"118"=>['explode_dir','r,d,func','used after explore() in obtain_from_dir()','array of files in $j directory applied to the function $func','files'],
"119"=>['func','d,k,f,n','it\'s an example of func() used  by explode_dir()','string for array built by explode_dir()','files'],
"120"=>['walk_dir','dr,func','','','files'],
"121"=>['recup_fileinfo','doc','file','formated date and size of a file','files'],
"122"=>['ftime','f,d=\'\'','file','formated date of a file ','files'],
"123"=>['fsize','f','file','formated size of a file ','files'],
"124"=>['fwidth','f','','','files'],
"125"=>['gz_create','f,fb','file_url bz_name of the compressed archive','store a bz archive','files'],
"126"=>['gz_write','d,f','bz_url file_name of the decompressed archive','store a file from a bz archive','files'],
"127"=>['unpack_gz','f,d','','','files'],
"128"=>['dump','r,p','array of arrays and name of node like \'hub_table\'','prepared values for create_page()','microsql'],
"129"=>['msq_patch','f,r,nod','','','microsql'],
"130"=>['msq_menus','r','','','microsql'],
"131"=>['save_vars','dr,nod,defs','save microtable: directory table defs=array of arrays','nothing','microsql'],
"132"=>['msql_save','dr,nod,defs,dfb','save array of arrays defs in base/nod adding dfb as _menus_  :: resolve root problems','nothing','microsql'],
"133"=>['plug_motor','dr,nod,defsb','call a microtable base/nod or create it using _menus_ defsb','array of arrays','microsql'],
"134"=>['modif_vars','dr,nod,arr,k,dfb=\'\'','  (like hub_table) =array of arrays =\'add\' / \'push\' / \'del\' / value (optionnal)','the modified microtable with $arr','microsql'],
"135"=>['msql_modif','dr,nod,defs,dfb,act,n','dir node definitions menus action value 
Actions are : 
(defs is a value of a range) :
- one : modif value n
- push : add one value
(defs is the entire table) :
- arr : replace the array 
- mdf : replace value present in defs
- del : deleted values present in defs
- add : add values of defs ; if n=\'mdf\' verif if value already exists before to add it','saved array','microsql'],
"136"=>['msql_read','dr,nod,in=\'\',u=\'\'','directory nod=table i=range (optionnal) :: resolve root problems','array of a table 
or a part of it 
or only the value there is only one range','microsql'],
"137"=>['msql_read_b','dr,nod,in=\'\',u=\'\',ra=\'\'','','','microsql'],
"138"=>['mread','d,l=\'\',c=\'\'','','','microsql'],
"139"=>['msq_create','d,r,rb,k','','','microsql'],
"140"=>['msq_where','dr,nod,n,d,o=\'\'','','','microsql'],
"141"=>['msq_select','dr,pr,nd','select microbases in directory  from user  and table= (in \'bs_\') if theses tables are numeroted','array of needed tables from selection','microsql'],
"142"=>['msq_find_last','dr,pr,nod','directory hub table','previous empty value to fill (1,2,4 existing return 3)','microsql'],
"143"=>['msq_find_next','r','array','routine of msq_find_next','microsql'],
"144"=>['msq_findnext_entry','r,n','','','microsql'],
"145"=>['msq_goodtable','d','value of a table designed by string command as \'base/node§key\' in a connector ; abble to decide if the key is a number of table or a key of one table','table','microsql'],
"146"=>['msql_read_prep','b,d','','','microsql'],
"147"=>['msq_format','r','','','microsql'],
"148"=>['msq_cat','r,n','array number','make a list form the column of a table (unique key)','microsql'],
"149"=>['msq_tri','r,n,vrf','array, number, verif','return the values of a column of a table','microsql'],
"150"=>['msq_sort','r,n,i','','','microsql'],
"151"=>['msq_reorder','r','reorder the key of a table, beginning from 1','array','microsql'],
"152"=>['msq_move','r,ka,va','','','microsql'],
"153"=>['msq_walk','r,n,func,p','array, number, function, param','apply a function with param to each value of a column n','microsql'],
"154"=>['msq_walk_k','r,func','array, function','apply a function to the keys','microsql'],
"155"=>['msq_prep','r','affect numeric keys to a table, from 1','table with numerical keys','microsql'],
"156"=>['msq_prevnext','r,d','','','microsql'],
"157"=>['msq_copy','da,na,db,nb','','','microsql'],
"158"=>['msq_n','dr,nod,d','','','microsql'],
"159"=>['msq_append','defs,d','','','microsql'],
"160"=>['msq_merge','r,dr,nd','','','microsql'],
"161"=>['msq_ses','v,dr,nod,u','','','microsql'],
"162"=>['msq_data','d,o=\'\'','','','microsql'],
"163"=>['msq_f','dr,nod','','','microsql'],
"164"=>['popart','d,p=\'\',t=\'\'','','','arts'],
"165"=>['jread','c,id,v','','','arts'],
"166"=>['pecho_arts','id','call informations about article id in cache if possible or in database','array: day,frm,suj,img,nod,thm,lu,re,host,mail,ib','arts'],
"167"=>['read_msg','d,m','id, option','content of an article, options : 
- brut : not converted to html
- noimages : kill images
- nl : absolute urls (with http)
- 2 : preview only
- 3 : full text','arts'],
"168"=>['rqt','id,n=\'\'','','','arts'],
"169"=>['find_id','id','give id of an article called by unkwonw parameter as title, id, or \"last\"','id of existing and published article','arts'],
"170"=>['last_art_rqt','','','','arts'],
"171"=>['last_art_day','','','','arts'],
"172"=>['last_art','lastdate','','','arts'],
"173"=>['id_of_suj','id','use title of an article','return id of article','arts'],
"174"=>['ib_of_id','id','parent of an article','new id','arts'],
"175"=>['suj_of_id','id','title of article','string','arts'],
"176"=>['data_val','v,id,cat,val','value to recuperate in \'qdd\' where id, cat and val are known - use rse()','value from mysql - specific to mysql table \'qdd\' (datas)','arts'],
"177"=>['count_art','suj,frm','suj=title of article frm=category','number of published articles found','arts'],
"178"=>['cache_art','id','','','arts'],
"179"=>['make_table','r,csa=\'\',csb=\'\'','datas=array of arrays, csb is only for the first range','balise table','tables'],
"180"=>['make_divtable','r,h=\'\'','','','tables'],
"181"=>['make_tables','rt,r,csa,csb','datas=array of arrays, csb is only for the first range, if it is present in titles','balise table','tables'],
"182"=>['array_conn','r','','','tables'],
"183"=>['make_tabs','r,ud=\'\',c=\'\'','array with keys used as tabs','html javascript tabs','tables'],
"184"=>['slct_menus','r,lk,vf,cs1,cs2,kv','r=array (keys will be used) lk=link (like /?var=) vf=verif (var) cs1=active cs2=normal css kv=k or v: use key or value','list of links with detection of activated ','menus'],
"185"=>['slct_menus_tags','r,lk,vf,ct,csa,kv','r=array lk=link (like /?var=) vf=verif (var) ct=if nb is called, render also the number of occurences) cs1=css (use active class if detect var) kv=k/v: use key or value','list of links under li balise with detection of activated ','menus'],
"186"=>['slctmenusj','r,j,vf,sep','r=array (keys will be used) lk=link (like /?var=) vf=verif (var) cal=javascript to call','list of links in javascript with detection of selected','menus'],
"187"=>['slctmenus_sj','r,go,vf','array, js_command for SaveJ, active value (verif)','list of links calling ajax (SaveJ) with string VAR in js_command replaced by the key of each array','menus'],
"188"=>['jump_btns','id,v,add,c=\'\'','buttons of values separated by \"|\" in v sent by javascript to id and replacing the input id if add=0 or adding the words in add (like \', \')','buttons who send values in an input','menus'],
"189"=>['batch_defil','r','array','option balises from keyx of array','menus'],
"190"=>['menuder_form','r,d','call batch_defil() with r (options) and name the select input d','input select','menus'],
"191"=>['batch_defil_kv','r,here,kv','array checked_key kk/kv/vv/vk = usage of the values of the array (key-value) :
kk=send and show k;
kv=send k and show v;
vv=send and show v;
vk=send v and show k
-- used by menuder_form_kv','select balise with options and checked_value','menus'],
"192"=>['menuder_form_kv','r,d,here,kv','build option calling batch_defil_kv() knowing here=selected value and kv=key or value to use for value and title of the options','input select','menus'],
"193"=>['menuder_h','r,id,d','','','menus'],
"194"=>['menuderj_prep','pr,id,t,opt=\'\'','','','menus'],
"195"=>['mkbub','d,c=\'\',s=\'\',o=\'\'','','','menus'],
"196"=>['bubslct','j,t','','','menus'],
"197"=>['select_jp','id,f,v=\'\',o=\'\',t=\'\'','','','menus'],
"198"=>['select_jb','id,pr,v=\'\',o=\'\',oj=\'\'','','','menus'],
"199"=>['select_j','id,f,v=\'\',o=\'\',t=\'\',ty=\'\'','','','menus'],
"200"=>['msql_slct','id,k,murl','','','menus'],
"201"=>['read_rss_data','data,t,r','','','rss'],
"202"=>['read_rss','f,t,r','system/program_functions.php=file_url =master_balise name (like \'item\') =array of sub-balises (like \'title\',\'description\')','array of arrays of an sml or rss source','rss'],
"203"=>['read_xml','f','','','rss'],
"204"=>['load_xml','f,o=\'\'','','','rss'],
"205"=>['mkdts','','','','rss'],
"206"=>['rss_date','date','find timestamp from rss formated date','timestamp','rss'],
"207"=>['rss_time','date','','','rss'],
"208"=>['mkday','d=\'\',p=\'\'','timestamp','datadav using \'ymd\'','dates'],
"209"=>['calc_date','d','d=timestamp','timestamp of $d days before','dates'],
"210"=>['calctime','d','','','dates'],
"211"=>['mtime','','','','dates'],
"212"=>['timelang','','','','dates'],
"213"=>['time_prev','d','','','dates'],
"214"=>['time_ago','dt','php date(dt,df=timestamp) use relative time','formated string like \'2h 10min ago\'','dates'],
"215"=>['timetravel','','','','dates'],
"216"=>['on2cols','r,w,p','r is an array with key=label and value=content, w=total width, with of labels=1/p','table in divs','builders'],
"217"=>['onxcols','re,prm,w,h=\'\'','','','builders'],
"218"=>['scroll','r,d,n,w=\'\',h=\'\'','obj=array used to build txt, nb is the limit for create a scrool','div with ovrflow if needed','builders'],
"219"=>['scroll_b','r,d,n,w=\'\',h=\'\',id=\'\'','','','builders'],
"220"=>['iframe','d,w=\'\',h=\'\'','url width','iframe balise','builders'],
"221"=>['eradic_acc','d','convert all accentuated  characters to normal','formated string','filters'],
"222"=>['protect_utf','d','','','filters'],
"223"=>['repair_latin','d','','','filters'],
"224"=>['utf8_decode_b','d','','','filters'],
"225"=>['html_entity_decode_b','v','','','filters'],
"226"=>['unescape','d','convert entities like %u to ascii code (hex to dec)','ascii code','filters'],
"227"=>['utflatindecode','d','convert recognized entities like %u to html code','decoded utflatin','filters'],
"228"=>['urlutf','d,p','','','filters'],
"229"=>['normalize','d','forbid special characters and accept only A-aZ-z0-9','formated string','filters'],
"230"=>['entities','d','','','filters'],
"231"=>['parse','v','','','filters'],
"232"=>['strip_tags_b','d','','','filters'],
"233"=>['clean_acc','v','kill all types of accents','formated string','filters'],
"234"=>['clean_punct','in','apply typographic rules','formated string','filters'],
"235"=>['clean_punct_b','v','apply typographic rules specific to bad spaces around the quote \" (slower)','formated string','filters'],
"236"=>['lowercase','v','strtolower but keep ucfirst for each words','formated string','filters'],
"237"=>['delbr','d,o','','','filters'],
"238"=>['deln','d,o=\'\'','del /n','cleanup','filters'],
"239"=>['delconn','d','','','filters'],
"240"=>['embed_detect','v,s,e,n=\'\'','string start-cut end-cut cut_from','the part of $v who begin and finish with $s and $e','filters'],
"241"=>['quotes','d','','','filters'],
"242"=>['scale_img','w,h,wo,ho,s','width height desired_width desired_height option (vertical priority =1)','part of make_mini','img'],
"243"=>['make_mini','in,out,w,h,s','path desired_path width height option (vertical)','url of built miniature','img'],
"244"=>['imgalpha','img','path','part of make_mini','img'],
"245"=>['thumb_name','d,w,h','id width height','name of a miniature','img'],
"246"=>['make_thumb_c','d,size=\'\',s=\'\'','','','img'],
"247"=>['jcim','f,o=\'\'','','','img'],
"248"=>['popim_w','im,d','','','img'],
"249"=>['popim','im,v,id=\'\'','','','img'],
"250"=>['popthumb','f,s=\'\'','','','img'],
"251"=>['forbidden_img','nnm','','','img'],
"252"=>['save_get','','','','pages'],
"253"=>['rebuild_get','','','','pages'],
"254"=>['by_pages','r,p','give result of r by pages if needed, with limit of 10 objects by page','list of pages','pages'],
"255"=>['detect_uget','d','','','pages'],
"256"=>['recup_get','dr','','','pages'],
"257"=>['nb_page_lk','','','','pages'],
"258"=>['nb_page','tot,npg,page,no=\'\'','','','pages'],
"259"=>['mails_list','','','','mails'],
"260"=>['recup_mails_tosend','','','','mails'],
"261"=>['prep_mail_html','suj,v,url','','','mails'],
"262"=>['send_mail_html','dest,suj,v,from,url','','','mails'],
"263"=>['send_mail_txt','dest,suj,v,from,url','','','mails'],
"264"=>['send_mail','format,to,suj,msg,from,url','','','mails'],
"265"=>['contact','t,c','','','mails'],
"266"=>['read_apps_reader','f','','','desktop'],
"267"=>['read_apps','v','','','desktop'],
"268"=>['match_vdir','dr,nd,rv','','','desktop'],
"269"=>['m_apps','r,cnd,dir,p=\'\',o=\'\'','','','desktop'],
"270"=>['r_apps','p=\'\'','','','desktop'],
"271"=>['array_merge_p','r,rb','','','desktop'],
"272"=>['array_merge_px','r,rb','','','desktop'],
"273"=>['apps_arts_thumb','d','','','desktop'],
"274"=>['desktop_apps','id,va,opt,o','','','desktop'],
"275"=>['desk_icon','k,j','','','desktop'],
"276"=>['desktop_build_ico','r,c','','','desktop'],
"277"=>['app_list','r,c,cl=\'\'','','','desktop'],
"278"=>['desktop_cond','p,o=\'\'','','','desktop'],
"279"=>['desktop_js','d','','','desktop'],
"280"=>['poplist','','','','desktop'],
"281"=>['call_finder','p,o','','','desktop'],
"282"=>['msqmimes','','','','desktop'],
"283"=>['mimes_types','d','','','desktop'],
"284"=>['mimes','d,t=\'\',sz=\'\'','','','desktop'],
"285"=>['stripslashes_b','d','','','php'],
"286"=>['strin','v,s','','','php'],
"287"=>['strchr_b','v,s','','','php'],
"288"=>['strrchr_b','v,s','value separator','part of string after the separator, not including it','php'],
"289"=>['substrpos','d,s','','','php'],
"290"=>['substrrpos','d,s','','','php'],
"291"=>['subtopos','ret,a,b','','','php'],
"292"=>['split_r','d,n','data number','split at n position','php'],
"293"=>['strprm','d,n=\'\',s=\'\'','','','php'],
"294"=>['strdeb','v,s','','','php'],
"295"=>['str_until','d,s','','','php'],
"296"=>['split_one','s,v,n=\'\'','part of value after and before string (n=0), or after and before the last found string (n=1), let the sides a his place (right or left) if other is empty','an array with entries','php'],
"297"=>['split_right','s,v,n=\'\'','','','php'],
"298"=>['split_only','s,v,p=\'\',t=\'\'','','','php'],
"299"=>['strsplit','v','php str_split() for php4','array of each letter of $v','php'],
"300"=>['array_combine_a','a,b','a=keys b=values','combined array','php'],
"301"=>['array_merge_b','r,rb','','','php'],
"302"=>['array_merge_r','a,b','','','php'],
"303"=>['array_unshift_b','&r,k,v','','','php'],
"304"=>['array_reverse_b','r,s=\'\'','','','php'],
"305"=>['array_keys_b','r','','','php'],
"306"=>['array_keys_r','r,n,o=\'\'','r=array in an array n=range: key_target','array: values of a range','php'],
"307"=>['in_array_b','va,r','find key in ranges r where value=va','like in_array() ','php'],
"308"=>['in_array_r','r,d,n','array value number','verif if value exist in recursive array at column n','php'],
"309"=>['array_add_r','ra,rb','add values to recursive arrays','new array','php'],
"310"=>['array_walk_b','r,func,p1,p2','array function param2 param3','array of results of function apply to values of \'r\' as param1','php'],
"311"=>['array_part','d,s,n','data split number','the occurrence \'n\' of the pattern \'d\' split with \'s\'','php'],
"312"=>['walkeach','r,d,p','','','php'],
"313"=>['array_push_after','ra,rb,p','','','php'],
"314"=>['explode_k','d,a,b','','','php'],
"315"=>['implode_k','r,a,b','','','php'],
"316"=>['compact_val','r,a,b','','','params'],
"317"=>['decompact_conn','d','data','convert string to connector','params'],
"318"=>['decompact_conn_b','d','data','convert string to connector ; force §option to be at the end','params'],
"319"=>['decompact_mod','d','','','params'],
"320"=>['subparams','d','data','extract list of values from variable of a connector','params'],
"321"=>['subparams_a','d','data','extract list of values from options of a connector','params'],
"322"=>['good_param','d','options deductions from connectors','array','params'],
"323"=>['yesno','d','','','params'],
"324"=>['randid','p=\'\'','','','strings'],
"325"=>['nchar','o,n','value number','same value n times (repetitive value)','strings'],
"326"=>['splice','r,n','','','strings'],
"327"=>['count_r','r','','','strings'],
"328"=>['nearest','d,s','','','strings'],
"329"=>['xt','v','give the strlower extension in v','formated string','strings'],
"330"=>['xtb','v','give the strlower 4 last chars in v','formated string ','strings'],
"331"=>['is_image','d','verify if doc is an image','true','strings'],
"332"=>['determine_cond','cnd','','','strings'],
"333"=>['correct_internal_url','f,h=\'\'','','','meca'],
"334"=>['val_to_mod_b','p','','','meca'],
"335"=>['define_modc_b','vl','','','meca'],
"336"=>['tri_tag','v','basic action of tri_tags() :: explode  by \',\' and trim it, used for tags','array from string','meca'],
"337"=>['tri_tags','r','convert all values or tha array r (containing tags with commas) in an array of tag in key, and number of occurences in value','formated array','meca'],
"338"=>['currentwidth','','','','design'],
"339"=>['content_width','','','','design'],
"340"=>['curwidth_set','d','','','design'],
"341"=>['pagewidth','d,f=\'\'','','','design'],
"342"=>['active','d,n','','','design'],
"343"=>['colors','d=\'\'','','','design'],
"344"=>['rand_clr','','','','design'],
"345"=>['hexrgb_r','d','','','design'],
"346"=>['hexrgb','d,o=\'\'','hex2rgba','rgba()','design'],
"347"=>['invert_color','p,o','','','design'],
"348"=>['rstr','n','value of restriction \'n\' (number)','no restriction return \'true\'','sessions'],
"349"=>['auth','n','','','sessions'],
"350"=>['prms','n','','','sessions'],
"351"=>['prmb','n','','','sessions'],
"352"=>['nms','d','number of the nomination','nominations (helps_nominations)','sessions'],
"353"=>['yesnoses','d','','','sessions'],
"354"=>['define_s','v,d','give the the session s the value d if session is not set, then give get value to session','value of the session $v','sessions'],
"355"=>['getorpost','v,d','value data','post replace get, get replace data','sessions'],
"356"=>['get','v','','','sessions'],
"357"=>['geta','v,d','','','sessions'],
"358"=>['post','d,v=\'\'','','','sessions'],
"359"=>['ses','d,v=\'\'','call session from his name','value of session','sessions'],
"360"=>['sesr','d,k,v=\'\'','','','sessions'],
"361"=>['sesv','v,p=\'\',b=\'\'','','','sessions'],
"362"=>['sesone','v,p=\'\'','','','sessions'],
"363"=>['sesmk','v,p=\'\',b=\'\'','value_name function_name, reset','make session for datas (cache system)','sessions'],
"364"=>['sesf','v,p=\'\',b=\'\'','','','sessions'],
"365"=>['jc','','','','access'],
"366"=>['root','','','','access'],
"367"=>['prog','b=\'\',c=\'\'','','','access'],
"368"=>['https','f','link','strip https','access'],
"369"=>['http','f','','','access'],
"370"=>['nohttp','f','','','access'],
"371"=>['http_domain','f','','','access'],
"372"=>['http_root','f','','','access'],
"373"=>['findroot_b','u','','','access'],
"374"=>['utmsrc','f','','','access'],
"375"=>['host','','','','access'],
"376"=>['htac','d','part of url knowing htaccess','the param of variable formated','access'],
"377"=>['htacc','d','part of url knowing htaccess for \'read\' or \'id\'','the param of variable formated','access'],
"378"=>['urlread','d','','','access'],
"379"=>['philum','','','','access'],
"380"=>['hardurl','d','','','access'],
"381"=>['good_url','id,v','deprecated :: build explicit url from formated title (suj) if present, or i by default','url of an article found by htacc(\'read\')','access'],
"382"=>['subdom','v','make url from hub v, depend if subdomain or htaccess are activated ','url','access'],
"383"=>['prep_host','nod','good url with thttp for hub=nod if subdomain or htaccess or nothing activated','formated string','access'],
"384"=>['hostname','','','','access'],
"385"=>['mobile','','','','access'],
"386"=>['feedproxy','f','','','access'],
"387"=>['ajx','v,p=\'\'','','','ajax'],
"388"=>['ajxr','res','','','ajax'],
"389"=>['ajxg','d','','','ajax'],
"390"=>['ajxp','res,pa,oa','','','ajax'],
"391"=>['memtmp','','','','ajax'],
"392"=>['core','f,p,v1,v2,v3,v4','','','ajax'],
"393"=>['lj_tog','n,d,v','toggle button with content socket','','actions'],
"394"=>['ljbub','v,lk,oc=\'\',ov=\'\',id=\'\',tg=\'\'','lj for bubbles','','actions'],
"395"=>['saveiec','j,cat,rid,cid=\'\',v=\'\',x=\'\',c=\'\'','used for save article','','actions'],
"396"=>['btn_switch','d,g,l,v','session_name, indicator for true, link, text','button off/on with alert','actions'],
"397"=>['toggle','c,j,v,n=\'\'','class js text','toggle button with ajax call js_function','actions'],
"398"=>['bubble','c,ja,j,v','class js func, js prop, value','bubble button with ajax call js_function','actions'],
"399"=>['popbub','d,j,v,c=\'\',o=\'\'','call Apps from bubble','','actions'],
"400"=>['togbub','ja,j,v','toggle bubble','','actions'],
"401"=>['togses','v,t','toggle session','tog button','actions'],
"402"=>['togses_j','d,t','','','actions'],
"403"=>['plink','f','','','btns'],
"404"=>['prepdlink','val','','','btns'],
"405"=>['preplink','lk','link','root of link','btns'],
"406"=>['nbof','n,i','number (count), numeber (value of nms)','plurial or signle of objects (nomination)','btns'],
"407"=>['plurial','n,i','r=array of objects','letter \"s\" if $r>1','btns'],
"408"=>['flags','d','country','image flag of contry','btns'],
"409"=>['ascii','d,n=\'\'','d=ascii value, n=size','ascii code','btns'],
"410"=>['svg','d','','','btns'],
"411"=>['picto','d,c=\'\'','','','btns'],
"412"=>['pictxt','p,t=\'\',s=\'\'','','','btns'],
"413"=>['pictit','p,t,s=\'\'','','','btns'],
"414"=>['imgico','f,t=\'\',h=\'\'','','image of icon','btns'],
"415"=>['icon','v,t=\'\',h=\'\',jc=\'\'','data directory','icon (image from icon/system by default)','btns'],
"416"=>['ico','d,t=\'\'','','','btns'],
"417"=>['callico','d,t=\'\',s=\'\',c=\'\'','','','btns'],
"418"=>['icosys','d,s=\'\'','','','btns'],
"419"=>['helps','d,nd=\'\'','key of helps_txts table','value of entry','btns'],
"420"=>['hlpbt','d,p=\'\'','key of helps_txts table','button (?) opening help in a popup','btns'],
"421"=>['msqlink','b,p,d=\'\',c=\'\'','','','btns'],
"422"=>['isplug','d','','','plug'],
"423"=>['clplug_j','d,a=\'\',b=\'\'','','','plug'],
"424"=>['call_func','c,r,v','css specific_array value','shortcut to lj() but params for SaveJ are in an array','plug'],
"425"=>['call_plug_f','c,t,pl,f,p,v','','','plug'],
"426"=>['call_plug','c,t,f,p,v','class target_div plug_name option value','shortcut to lj() specific for plugins (decide if prepare for popup)','plug'],
"427"=>['plugin','d,p=\'\',o=\'\',ob=\'\',res=\'\'','plugin param1 param2','result of a plugin with params','plug'],
"428"=>['plugin_func','d,f,p=\'\',o=\'\',res=\'\'','','','plug'],
"429"=>['plug_core','d,p=\'\',o=\'\',res=\'\'','','','plug'],
"430"=>['search_engine','d','','','plug'],
"431"=>['eye','p=\'\'','','','eye'],
"432"=>['exc','d','','','utils'],
"433"=>['req','d,j=\'\'','','','utils'],
"434"=>['reqp','d','','','utils'],
"435"=>['checkupdate','','','number of newest version of philum','utils'],
"436"=>['alert','d','','','utils'],
"437"=>['patch_replace','bs,in,wh,repl','replace in by repl where wh in bs','confirmation success','utils'],
"438"=>['error_report','','','','utils'],
"439"=>['chrono','d','','','utils'],
"440"=>['pr','r','','','utils'],
"441"=>['window','d','','','utils'],
"442"=>['eco','d,o=\'\'','','','utils'],
"443"=>['verbose','r','','','utils']]; ?>