<?php //msql/program_core_sav
$r=["_"=>['function','variables','usage','return','context'],
"1"=>['p','r','print_r()','','html'],
"2"=>['br','','','br balise','html'],
"3"=>['hr','','','hr balise','html'],
"4"=>['sep','','separator','','html'],
"5"=>['atb','d,v','html attribut','d=\"v\"','html'],
"6"=>['atc','d','class attribut','','html'],
"7"=>['atd','d','id attribut','','html'],
"8"=>['ats','d','style attribut','','html'],
"9"=>['atn','d','name attribut','','html'],
"10"=>['atv','d','value attribut','','html'],
"11"=>['atz','d','size attribut','','html'],
"12"=>['att','d','','','html'],
"13"=>['atj','d,j','javascript prop and attribut','(\'j\');','html'],
"14"=>['atjb','r','multiple javascript attributs','','html'],
"15"=>['atjr','d,r','','','html'],
"16"=>['sj','d','javascript function SaveJ','SaveJ(\'sj\');','html'],
"17"=>['atbb','d','multiple attributs: class|id|style','','html'],
"18"=>['atr','r','multiple props and attributs','','html'],
"19"=>['ul','v','balise','embed content','html'],
"20"=>['li','v','balise','embed content','html'],
"21"=>['bal','b,v','b=balise v=value','balise html','html'],
"22"=>['balc','b,c,v','balise class value','','html'],
"23"=>['balb','b,p,v','balise, free manual props, value','','html'],
"24"=>['balise','b,r,v','b=balise r=attributs t=text :: 
attributs_rule : use key instead of name of property :
array(1=>\"type\",2=>\"name\",3=>\"id\",4=>\"value\",5=>\"class\",6=>\"size\",7=>\"maxlenght\",8=>\"onKeyPress\",9=>\"cols\",10=>\"rows\",11=>\"wrap\",12=>\"action\",13=>\"method\",14=>\"for\",15=>\"onchange\",16=>\"style\")','html balise from an array of attributes','html'],
"25"=>['span','p,v','free props, value','span balise','html'],
"26"=>['btn','c,v','class text','span balise','html'],
"27"=>['btd','d,v','id txt','span balise with id value','html'],
"28"=>['bts','d,v','style value','span balise','html'],
"29"=>['div','p,v','attributs value','div balise','html'],
"30"=>['divr','p,v','','','html'],
"31"=>['divb','p,v','class|is|style value','div balise','html'],
"32"=>['divc','c,v','class value','div balise','html'],
"33"=>['divd','d,v','id value','div balise','html'],
"34"=>['divs','s,v','style text','div balise','html'],
"35"=>['button','c,j,v','class javascript text','html button','html'],
"36"=>['lk','u,p=\'\',v=\'\'','','','html'],
"37"=>['lka','u,v=\'\'','link value','a balise, display domain only','html'],
"38"=>['lkc','c,u,v','class link value','a balise','html'],
"39"=>['lkt','c,u,v','class link value','a balise with target=_blank','html'],
"40"=>['lkh','oc,ov,v,c=\'\'','onclick js, onhover js, value, class','a balise','html'],
"41"=>['llk','c,l,v','class link value','a balise inside a li balise','html'],
"42"=>['submitj','c,id,v','button javascript','button balise','html'],
"43"=>['lja','c,j,v','','','html'],
"44"=>['lj','c,j,v,o=\'\'','class js text','a balise with javascript function \'SaveJ\' - shortcut to lc()','html'],
"45"=>['ljp','p,j,v','','','html'],
"46"=>['ljb','c,p,j,v,a=\'\'','class, js function as attribut, js prop, value, 1=onmouseover else onclick','a balise with js and mouseover ability','html'],
"47"=>['ljc','c,d,j,v,o=\'\',p=\'\'','js button calling a core function :
class, target, js, value, ajaxmode (3=display loading), \'p\' for popup','a balise','html'],
"48"=>['ljh','c,j,v','on mouseover with timing and autoclose','a balise','html'],
"49"=>['blj','c,id,j,v','using id as target for answer of ajax','a balise in span balise','html'],
"50"=>['llj','c,j,v,id=\'\',a=\'\'','class, js, value, id of li, 1=mouseover','a balise in li balise','html'],
"51"=>['image','d,w=\'\',h=\'\',p=\'\'','image width height props','html embed image','html'],
"52"=>['img','d,s=\'\'','image at 100%','img balise','html'],
"53"=>['rolloverimg','a,b','switch image on rollover','img button','html'],
"54"=>['etc','d,n','cut text at n pos and add \"...\"','','html'],
"55"=>['asciinb','n','','','html'],
"56"=>['gridpos','d','','','html'],
"57"=>['attr','r','','','html'],
"58"=>['toggle','c,j,v,n=\'\'','class js text','toggle button with ajax call js_function','action_j'],
"59"=>['bubble','c,ja,j,v','class js func, js prop, value','bubble button with ajax call js_function','action_j'],
"60"=>['popbub','d,j,v,c=\'\',o=\'\'','call Apps from bubble','','action_j'],
"61"=>['panup','d,j,v,c','','','action_j'],
"62"=>['togbub','ja,j,v,c=\'\',o=\'\'','toggle bubble','','action_j'],
"63"=>['togses','v,t','toggle session','tog button','action_j'],
"64"=>['togses_j','d,t','','','action_j'],
"65"=>['input','d,v,p=\'\'','type: 1,0 (text,hidden) or any input_type ; id value class','input text for forms','forms'],
"66"=>['input0','t,d,v,p=\'\'','','','forms'],
"67"=>['input1','d,v,s=\'\',c=\'\',h=\'\',m=\'\'','id value size class','input balise','forms'],
"68"=>['input2','n,v,s=\'\',c=\'\',h=\'\',m=\'\',id=\'\'','type name value class','input text for forms','forms'],
"69"=>['submit','n,v,c=\'\'','','','forms'],
"70"=>['autoclic','n,v,sz,mx,c,h=\'\',o=\'\'','input text auto-hide content','balise input with javascript','forms'],
"71"=>['jholder','v','old javascript holder','','forms'],
"72"=>['hidden','n,d,v','name id value','input for forms ','forms'],
"73"=>['checkbox','n,v,t,chk','chk=0/1 if checked','checkbox for a form','forms'],
"74"=>['offon','d,t=\'\'','','picto true or false','forms'],
"75"=>['checkbox_j','id,v,t=\'\',b=\'\',j=\'\'','','','forms'],
"76"=>['checkact','id,v,t','','','forms'],
"77"=>['label','id,c,s,t','id class style text','label balise connected to id_input (for=\"id\")','forms'],
"78"=>['radiobtn','r,h,n','','','forms'],
"79"=>['radioj','id,r,n','','','forms'],
"80"=>['radiobtj','r,vrf,id,o=\'\'','','','forms'],
"81"=>['txarea','id,v,cl,rw,p=\'\'','name text cols rows','text area','forms'],
"82"=>['txareac_btns','','','','forms'],
"83"=>['txareac','id,c,s,j,d,o=\'\'','','','forms'],
"84"=>['divedit','id,c,s,j,d','','','forms'],
"85"=>['txarea1','msg','msg, art or track (0/1), continue value (0/1)','textarea used for edit articles, callable from ajax','forms'],
"86"=>['form','go,d','','','forms'],
"87"=>['goodarea','id,v,n','jv=javascripts n=size or cols','balise input text or a textarea','forms'],
"88"=>['upload_j','id,typ,o=\'\'','','','forms'],
"89"=>['select','atr,r,kv,h=\'\'','','','forms'],
"90"=>['header_html','','','','headers'],
"91"=>['meta','d,v,c=\'\'','meta d=v and content=c','used by headers','headers'],
"92"=>['css_link','d,m=\'\'','link to css','used by headers','headers'],
"93"=>['js_link','d','js link','used by headers','headers'],
"94"=>['css_code','d','css code','used by headers','headers'],
"95"=>['js_code','d','js code','used by headers','headers'],
"96"=>['temporize','name,func,p','name of the function, func=content, p=milliseconds :: temporize() will call a javascript cuntion every p seconds','javascript','headers'],
"97"=>['relod','v','reload to a page','javascript immediately applied','headers'],
"98"=>['header_tags','r','','','headers'],
"99"=>['add','k,v','','','sessions'],
"100"=>['get','d,v=\'\'','','','sessions'],
"101"=>['generate','','','','headers'],
"102"=>['connect','','','','mysql'],
"103"=>['qd','d','','','mysql'],
"104"=>['rcptb','db','show tables','mysql_query','mysql'],
"105"=>['lstrc','rq','make array from range 0 in mysql_fetch_array','array','mysql'],
"106"=>['qrr','r','','','mysql'],
"107"=>['qra','r','','','mysql'],
"108"=>['qrw','r','','','mysql'],
"109"=>['qrf','r','','','mysql'],
"110"=>['qrid','sql,o=\'\'','','','mysql'],
"111"=>['qr','sql,o=\'\'','','','mysql'],
"112"=>['qres','v','','','mysql'],
"113"=>['atm','v','','','mysql'],
"114"=>['atmr','r','','','mysql'],
"115"=>['atmrup','r','','','mysql'],
"116"=>['mysqlra','r,o','','','mysql'],
"117"=>['mysqlrb','r,o','','','mysql'],
"118"=>['insert','b,d,o=\'\'','','','mysql'],
"119"=>['update','bs,set,v,col,id,o=\'\'','UPDATE bs SET in=v WHERE col=id','nothing (and no error)','mysql'],
"120"=>['delete','bs,id,o=\'\'','delete in bs where id','nothing','mysql'],
"121"=>['reflush','bs,o=\'\'','ALTER TABLE bs ORDER BY id :: used by delete()','nothing','mysql'],
"122"=>['lastid','bs','sql command','id of most recent entry','mysql'],
"123"=>['sqlformat','rq,p','','','mysql'],
"124"=>['sql','d,b,p,q,z=\'\'','','','mysql'],
"125"=>['sqb','d,b,p,q,z=\'\'','','','mysql'],
"126"=>['sqr','d,b,q=\'\',z=\'\'','','','mysql'],
"127"=>['sql_inner','d,b1,b2,key,p,q,z=\'\'','','','mysql'],
"128"=>['sql_b','sql,p,z=\'\'','','','mysql'],
"129"=>['mkdir_r','u','build directories topology from a string like dir1/dir11/dir111','nothing','dirs'],
"130"=>['rmdir_r','dr','path dir file topo_number','delete files of a directory, including other dirs ;
option of explode_dir function (used inside a routine)','dirs'],
"131"=>['explore','dr,p=\'\',o=\'\'','','','dirs'],
"132"=>['explode_dir','r,d,func','used after explore() in obtain_from_dir()','array of files in $j directory applied to the function $func','dirs'],
"133"=>['func','d,k,f,n','it\'s an example of func() used  by explode_dir()','string for array built by explode_dir()','dirs'],
"134"=>['walk_dir','dr,func','','','dirs'],
"135"=>['read_file','f','open datas from fil f','text','files'],
"136"=>['write_file','f,t','file_url text to save in f','save file on server','files'],
"137"=>['get_file','f','','','files'],
"138"=>['file_get_context','f','','','files'],
"139"=>['curl_get_contents','f,post=\'\'','','','files'],
"140"=>['joinable','d','','','files'],
"141"=>['recup_fileinfo','doc','file','formated date and size of a file','files'],
"142"=>['ftime','f,d=\'\'','file','formated date of a file ','files'],
"143"=>['fsize','f','file','formated size of a file ','files'],
"144"=>['fwidth','f','','','files'],
"145"=>['frdate','d','','','files'],
"146"=>['localdate','d','','','files'],
"147"=>['gz_create','f,fb','file_url bz_name of the compressed archive','store a bz archive','files'],
"148"=>['gz_read','f','','','files'],
"149"=>['gz_write','d,f','bz_url file_name of the decompressed archive','store a file from a bz archive','files'],
"150"=>['gz2im','f','','','files'],
"151"=>['is_zip','f','','','files'],
"152"=>['unpack_gz','f,d','','','files'],
"153"=>['db_f','nod,dr=\'usr/\'','','','db'],
"154"=>['db_init','f','','','db'],
"155"=>['db_add','f,row','','','db'],
"156"=>['db_write','f,r','','','db'],
"157"=>['db_read','f','','','db'],
"158"=>['nod','d','','','microsql'],
"159"=>['dump','r,p','array of arrays and name of node like \'hub_table\'','prepared values for create_page()','microsql'],
"160"=>['msq_patch','f,r,nod','','','microsql'],
"161"=>['msq_menus','r','','','microsql'],
"162"=>['read_vars','dr,nod,defsb','','','microsql'],
"163"=>['save_vars','dr,nod,r','save microtable: directory table defs=array of arrays','nothing','microsql'],
"164"=>['msql_save','dr,nod,r,h=\'\'','save array of arrays defs in base/nod adding dfb as _menus_  :: resolve root problems','nothing','microsql'],
"165"=>['msql_displace','dr,nod,id,to','','','microsql'],
"166"=>['modif_vars','dr,nod,ra,d,dfb=\'\'','  (like hub_table) =array of arrays =\'add\' / \'push\' / \'del\' / value (optionnal)','the modified microtable with $arr','microsql'],
"167"=>['msql_modif','dr,nod,defs,dfb,act,n','dir node definitions menus action value 
Actions are : 
(defs is a value of a range) :
- one : modif value n
- push : add one value
(defs is the entire table) :
- arr : replace the array 
- mdf : replace value present in defs
- del : deleted values present in defs
- add : add values of defs ; if n=\'mdf\' verif if value already exists before to add it','saved array','microsql'],
"168"=>['msql_read','dr,nod,in=\'\',u=\'\'','directory nod=table i=range (optionnal) :: resolve root problems','array of a table 
or a part of it 
or only the value there is only one range','microsql'],
"169"=>['msql_read_b','dr,nod,in=\'\',u=\'\',ra=\'\'','','','microsql'],
"170"=>['msq_create','d,r,rb,k','','','microsql'],
"171"=>['msq_where','dr,nod,n,d,o=\'\'','','','microsql'],
"172"=>['msq_choose','dr,pr,nd','','','microsql'],
"173"=>['msq_find_last','dr,pr,nod','directory hub table','previous empty value to fill (1,2,4 existing return 3)','microsql'],
"174"=>['msq_next_table','r','','','microsql'],
"175"=>['msq_next_entry','r','','','microsql'],
"176"=>['msq_goodtable','d','value of a table designed by string command as \'base/node|key\' in a connector ; abble to decide if the key is a number of table or a key of one table','table','microsql'],
"177"=>['msql_read_prep','b,d','','','microsql'],
"178"=>['msq_format','r','','','microsql'],
"179"=>['msq_col','r,n','','','microsql'],
"180"=>['msq_cat','r,n','array number','make a list form the column of a table (unique key)','microsql'],
"181"=>['msq_tri','r,n,vrf','array, number, verif','return the values of a column of a table','microsql'],
"182"=>['msq_sort','r,n,i','','','microsql'],
"183"=>['msq_reorder','r','reorder the key of a table, beginning from 1','array','microsql'],
"184"=>['msq_move','r,ka,va','','','microsql'],
"185"=>['msq_displace','r,id,to','','','microsql'],
"186"=>['msq_walk','r,n,func,p','array, number, function, param','apply a function with param to each value of a column n','microsql'],
"187"=>['msq_walk_k','r,func','array, function','apply a function to the keys','microsql'],
"188"=>['msq_prep','r','affect numeric keys to a table, from 1','table with numerical keys','microsql'],
"189"=>['msq_prevnext','r,d','','','microsql'],
"190"=>['msq_copy','da,na,db,nb','','','microsql'],
"191"=>['msq_n','dr,nod,d','','','microsql'],
"192"=>['msq_append','defs,d','','','microsql'],
"193"=>['msq_merge','r,dr,nd','','','microsql'],
"194"=>['msq_ses','v,dr,nod,u','','','microsql'],
"195"=>['msq_data','d,o=\'\'','','','microsql'],
"196"=>['msq_f','dr,nod','','','microsql'],
"197"=>['make_table','r,head=\'\',keys=\'\'','datas=array of arrays, csb is only for the first range','balise table','tables'],
"198"=>['make_divtable','r,h=\'\'','','','tables'],
"199"=>['make_tables','rt,r,csa,csb,o=\'\'','datas=array of arrays, csb is only for the first range, if it is present in titles','balise table','tables'],
"200"=>['array_conn','r','','','tables'],
"201"=>['make_tabs','r,ud=\'\',c=\'\'','array with keys used as tabs','html javascript tabs','tables'],
"202"=>['slct_menus','r,lk,vf,cs1,cs2,kv','r=array (keys will be used) lk=link (like /?var=) vf=verif (var) cs1=active cs2=normal css kv=k or v: use key or value','list of links with detection of activated ','menus'],
"203"=>['slct_menus_tags','r,lk,vf,ct,csa,kv','r=array lk=link (like /?var=) vf=verif (var) ct=if nb is called, render also the number of occurences) cs1=css (use active class if detect var) kv=k/v: use key or value','list of links under li balise with detection of activated ','menus'],
"204"=>['slctmenusj','r,j,vf,sep,kv=\'\'','r=array (keys will be used) lk=link (like /?var=) vf=verif (var) cal=javascript to call','list of links in javascript with detection of selected','menus'],
"205"=>['slctmenusja','r,j,vf','','','menus'],
"206"=>['slctmenus_sj','r,go,vf','array, js_command for SaveJ, active value (verif)','list of links calling ajax (SaveJ) with string VAR in js_command replaced by the key of each array','menus'],
"207"=>['jump_btns','id,v,add,c=\'\'','buttons of values separated by \"|\" in v sent by javascript to id and replacing the input id if add=0 or adding the words in add (like \', \')','buttons who send values in an input','menus'],
"208"=>['menuder_h','r,id,d,j','','','menus'],
"209"=>['menuderj_prep','pr,id,t,opt=\'\'','','','menus'],
"210"=>['mkbub','d,c=\'\',s=\'\',o=\'\'','','','menus'],
"211"=>['bubslct','j,t','','','menus'],
"212"=>['select_jp','id,f,v=\'\',o=\'\',t=\'\'','','','menus'],
"213"=>['select_jb','id,pr,v=\'\',o=\'\',oj=\'\'','','','menus'],
"214"=>['select_j','id,f,v=\'\',o=\'\',t=\'\',ty=\'\'','','','select_j //existing_list'],
"215"=>['msql_slct','id,k,murl','','','select_j //existing_list'],
"216"=>['read_rss_data','data,t,r','','','rss'],
"217"=>['read_rss','f,t,r','system/program_functions.php=file_url =master_balise name (like \'item\') =array of sub-balises (like \'title\',\'description\')','array of arrays of an sml or rss source','rss'],
"218"=>['read_xml','f','','','rss'],
"219"=>['load_xml','f,o=\'\'','','','rss'],
"220"=>['mkdts','','','','rss'],
"221"=>['rss_date','date','find timestamp from rss formated date','timestamp','rss'],
"222"=>['rss_time','date','','','rss'],
"223"=>['mkday','d=\'\',p=\'\'','timestamp','datadav using \'ymd\'','dates'],
"224"=>['calc_date','d','d=timestamp','timestamp of $d days before','dates'],
"225"=>['calctime','d','','','dates'],
"226"=>['mtime','','','','dates'],
"227"=>['timelang','','','','dates'],
"228"=>['time_prev','d','','','dates'],
"229"=>['time_ago','dt','php date(dt,df=timestamp) use relative time','formated string like \'2h 10min ago\'','dates'],
"230"=>['timetravel','','','','dates'],
"231"=>['on2cols','r,w,p','r is an array with key=label and value=content, w=total width, with of labels=1/p','table in divs','builders'],
"232"=>['onxcols','re,prm,w,h=\'\'','','','builders'],
"233"=>['scroll','r,d,n,w=\'\',h=\'\',id=\'\'','obj=array used to build txt, nb is the limit for create a scrool','div with ovrflow if needed','builders'],
"234"=>['scroll_b','r,d,n,w=\'\',h=\'\',id=\'\'','','','builders'],
"235"=>['iframe','d,w=\'\',h=\'\'','url width','iframe balise','builders'],
"236"=>['video_html','f,w=\'\',h=\'\'','','','builders'],
"237"=>['eradic_acc','d','convert all accentuated  characters to normal','formated string','filters'],
"238"=>['protect_utf','d','','','filters'],
"239"=>['repair_latin','d','','','filters'],
"240"=>['utf8_decode_a','d','','','filters'],
"241"=>['utf8_decode_b','d','','','filters'],
"242"=>['html_entity_decode_b','v','','','filters'],
"243"=>['specialspace','d','','','filters'],
"244"=>['decode_unicode','d','','','filters'],
"245"=>['utflatindecode','d','convert recognized entities like %u to html code','decoded utflatin','filters'],
"246"=>['urlutf','d,p','','','filters'],
"247"=>['normalize','d','forbid special characters and accept only A-aZ-z0-9','formated string','filters'],
"248"=>['entities','d','','','filters'],
"249"=>['parse','v','','','filters'],
"250"=>['strip_tags_b','d','','','filters'],
"251"=>['clean_acc','v','kill all types of accents','formated string','filters'],
"252"=>['clean_punct','in','apply typographic rules','formated string','filters'],
"253"=>['clean_punct_b','v','apply typographic rules specific to bad spaces around the quote \" (slower)','formated string','filters'],
"254"=>['lowercase','v','strtolower but keep ucfirst for each words','formated string','filters'],
"255"=>['delbr','d,o','','','filters'],
"256"=>['deln','d,o=\'\'','del /n','cleanup','filters'],
"257"=>['delconn','d','','','filters'],
"258"=>['embed_detect','v,s,e,n=\'\'','string start-cut end-cut cut_from','the part of $v who begin and finish with $s and $e','filters'],
"259"=>['prop_detect','v,s','','','filters'],
"260"=>['clean_title','d','','','filters'],
"261"=>['scale_img','w,h,wo,ho,s','width height desired_width desired_height option (vertical priority =1)','part of make_mini','img'],
"262"=>['make_mini','in,out,w,h,s','path desired_path width height option (vertical)','url of built miniature','img'],
"263"=>['imgalpha','img','path','part of make_mini','img'],
"264"=>['colors','d=\'\'','','','img'],
"265"=>['rand_clr','','','','img'],
"266"=>['hexrgb_r','d','','','img'],
"267"=>['hexrgb','d,o=\'\'','hex2rgba','rgba()','img'],
"268"=>['invert_color','p,o','','','img'],
"269"=>['prep_mail_html','suj,v,url','','','mails'],
"270"=>['send_mail_html','dest,suj,v,from,url','','','mails'],
"271"=>['send_mail_txt','dest,suj,v,from,url','','','mails'],
"272"=>['send_mail','format,to,suj,msg,from,url','','','mails'],
"273"=>['contact','t,c','','','mails'],
"274"=>['stripslashes_b','d','','','php'],
"275"=>['strin','v,s','','','php'],
"276"=>['strchr_b','v,s','','','php'],
"277"=>['strrchr_b','v,s','value separator','part of string after the separator, not including it','php'],
"278"=>['substrpos','d,s','','','php'],
"279"=>['substrrpos','d,s','','','php'],
"280"=>['subtopos','ret,a,b','','','php'],
"281"=>['split_r','d,n','data number','split at n position','php'],
"282"=>['strprm','d,n=\'\',s=\'\'','','','php'],
"283"=>['strdeb','v,s','','','php'],
"284"=>['strend','v,s','','','php'],
"285"=>['str_until','d,s','','','php'],
"286"=>['split_one','s,v,n=\'\'','part of value after and before string (n=0), or after and before the last found string (n=1), let the sides a his place (right or left) if other is empty','an array with entries','php'],
"287"=>['split_right','s,v,n=\'\'','','','php'],
"288"=>['str_extract','s,v,p=\'\',t=\'\'','','','php'],
"289"=>['strsplit','v','php str_split() for php4','array of each letter of $v','php'],
"290"=>['array_combine_a','a,b','a=keys b=values','combined array','php'],
"291"=>['array_combine_sub','a,b','','','php'],
"292"=>['array_merge_b','r,rb','','','php'],
"293"=>['array_merge_r','a,b','','','php'],
"294"=>['array_unshift_b','&r,k,v','','','php'],
"295"=>['array_reverse_b','r,s=\'\'','','','php'],
"296"=>['array_keys_b','r','','','php'],
"297"=>['array_keys_r','r,n,o=\'\'','r=array in an array n=range: key_target','array: values of a range','php'],
"298"=>['in_array_b','d,r','find key in ranges r where value=va','like in_array() ','php'],
"299"=>['in_array_p','d,r','','','php'],
"300"=>['in_array_r','r,d,n','array value number','verif if value exist in recursive array at column n','php'],
"301"=>['array_add_r','ra,rb','add values to recursive arrays','new array','php'],
"302"=>['array_walk_b','r,func,p1,p2','array function param2 param3','array of results of function apply to values of \'r\' as param1','php'],
"303"=>['array_part','d,s,n','data split number','the occurrence \'n\' of the pattern \'d\' split with \'s\'','php'],
"304"=>['walkeach','r,d,p','','','php'],
"305"=>['unset_in','r,d,n','','','php'],
"306"=>['array_push_after','ra,rb,p','','','php'],
"307"=>['explode_r','d,a,b','','','php'],
"308"=>['explode_k','d,a,b','','','php'],
"309"=>['implode_k','r,a,b','','','php'],
"310"=>['implode_keys','r,a=\'\'','','','php'],
"311"=>['yesno','d','','','strings'],
"312"=>['randid','p=\'\'','','','strings'],
"313"=>['nchar','o,n','value number','same value n times (repetitive value)','strings'],
"314"=>['splice','r,n','','','strings'],
"315"=>['count_r','r','','','strings'],
"316"=>['nearest','d,s','','','strings'],
"317"=>['xt','d','give the strlower extension in v','formated string','strings'],
"318"=>['xtb','d','give the strlower 4 last chars in v','formated string ','strings'],
"319"=>['is_image','d','verify if doc is an image','true','strings'],
"320"=>['determine_cond','cnd','','','context'],
"321"=>['define_modc_b','vl','','','context'],
"322"=>['rstr','n','value of restriction \'n\' (number)','no restriction return \'true\'','sessions'],
"323"=>['auth','n','','','sessions'],
"324"=>['prms','n','','','sessions'],
"325"=>['prma','n','','','sessions'],
"326"=>['prmb','n','','','sessions'],
"327"=>['nms','d','number of the nomination','nominations (helps_nominations)','sessions'],
"328"=>['yesnoses','d','','','sessions'],
"329"=>['msqlang','d','','','sessions'],
"330"=>['voc','d,b','','','sessions'],
"331"=>['getif','v,d','','','sessions'],
"332"=>['geta','d,v','','','sessions'],
"333"=>['post','d,v=\'\'','','','sessions'],
"334"=>['ses','d,v=\'\'','call session from his name','value of session','sessions'],
"335"=>['sesz','d,v=\'\'','','','sessions'],
"336"=>['sesg','v,d','','','sessions'],
"337"=>['sesr','d,k,v=\'\'','','','sessions'],
"338"=>['sesif','d,v=\'\'','','','sessions'],
"339"=>['sesone','v,p=\'\'','','','sessions'],
"340"=>['sesmk','v,p=\'\',b=\'\'','value_name function_name, reset','make session for datas (cache system)','sessions'],
"341"=>['jc','','','','access'],
"342"=>['root','','','','access'],
"343"=>['prog','o=\'\'','','','access'],
"344"=>['progb','o=\'\'','','','access'],
"345"=>['https','f','link','strip https','access'],
"346"=>['http','f','','','access'],
"347"=>['ishttp','f','','','access'],
"348"=>['nohttp','f','','','access'],
"349"=>['http_domain','f','','','access'],
"350"=>['http_root','f','','','access'],
"351"=>['findroot_b','u','','','access'],
"352"=>['utmsrc','f','','','access'],
"353"=>['host','','','','access'],
"354"=>['htac','d','part of url knowing htaccess','the param of variable formated','access'],
"355"=>['htacc','d','part of url knowing htaccess for \'read\' or \'id\'','the param of variable formated','access'],
"356"=>['urlread','d','','','access'],
"357"=>['philum','','','','access'],
"358"=>['good_url','id,v','deprecated :: build explicit url from formated title (suj) if present, or i by default','url of an article found by htacc(\'read\')','access'],
"359"=>['subdom','v','make url from hub v, depend if subdomain or htaccess are activated ','url','access'],
"360"=>['prep_host','nod','good url with thttp for hub=nod if subdomain or htaccess or nothing activated','formated string','access'],
"361"=>['hostname','','','','access'],
"362"=>['mobile','','','','access'],
"363"=>['hardurl','d','','','access'],
"364"=>['feedproxy','f','','','access'],
"365"=>['ajx','v,p=\'\'','','','ajax'],
"366"=>['ajxg','d','','','ajax'],
"367"=>['ajxr','res','','','ajax'],
"368"=>['ajxp','res,pa,oa','','','ajax'],
"369"=>['memtmp','','','','ajax'],
"370"=>['loadjs','f,d,t=\'\'','','','actions'],
"371"=>['lj_tog','n,d,v','toggle button with content socket','','actions'],
"372"=>['ljbub','v,lk,oc=\'\',ov=\'\',id=\'\',tg=\'\'','lj for bubbles','','actions'],
"373"=>['saveiec','j,cat,rid,cid=\'\',v=\'\',x=\'\',c=\'\',suj=\'\'','used for save article','','actions'],
"374"=>['btn_switch','d,g,l,v','session_name, indicator for true, link, text','button off/on with alert','actions'],
"375"=>['preplink','lk','link','root of link','btns'],
"376"=>['prepdlink','val','','','btns'],
"377"=>['nbof','n,i','number (count), numeber (value of nms)','plurial or signle of objects (nomination)','btns'],
"378"=>['plurial','n,i','r=array of objects','letter \"s\" if $r>1','btns'],
"379"=>['flags','','country','image flag of contry','btns'],
"380"=>['flag','d','','','btns'],
"381"=>['ascii','d,n=\'\'','d=ascii value, n=size','ascii code','btns'],
"382"=>['svg','d','','','btns'],
"383"=>['picto','d,s=\'\',c=\'\'','','','btns'],
"384"=>['pictxt','p,t=\'\',s=\'\'','','','btns'],
"385"=>['pictit','p,t,s=\'\'','','','btns'],
"386"=>['imgico','f,t=\'\',h=\'\'','','image of icon','btns'],
"387"=>['uicon','d,p,o=\'\'','','','btns'],
"388"=>['icon','v,t=\'\',h=\'\',jc=\'\'','data directory','icon (image from icon/system by default)','btns'],
"389"=>['ico','d,t=\'\'','','','btns'],
"390"=>['icons_r','','','','btns'],
"391"=>['callico','d,t=\'\',s=\'\',c=\'\'','','','btns'],
"392"=>['icosys','d,s=\'\'','','','btns'],
"393"=>['helps','d,nd=\'\'','key of helps_txts table','value of entry','btns'],
"394"=>['hlpbt','j,t=\'\'','key of helps_txts table','button (?) opening help in a popup','btns'],
"395"=>['msqlink','b,p,d=\'\',c=\'\'','','','btns'],
"396"=>['tri_tag','v','','','btns'],
"397"=>['compact_val','r,a,b','','','params'],
"398"=>['decompact_conn','d','','','params'],
"399"=>['decompact_conn_b','d','','','params'],
"400"=>['decompact_mod','d','','','params'],
"401"=>['subparams','d','','','params'],
"402"=>['subparams_a','d','','','params'],
"403"=>['good_param','d','','','params'],
"404"=>['clplug_j','d,a=\'\',b=\'\'','','','plug'],
"405"=>['call_func','c,r,v','css specific_array value','shortcut to lj() but params for SaveJ are in an array','plug'],
"406"=>['call_plug','c,t,f,p,v','class target_div plug_name option value','shortcut to lj() specific for plugins (decide if prepare for popup)','plug'],
"407"=>['plugin','d,p=\'\',o=\'\',ob=\'\',res=\'\'','plugin param1 param2','result of a plugin with params','plug'],
"408"=>['plugin_func','d,fc,p=\'\',o=\'\',res=\'\'','','','plug'],
"409"=>['appin','d,mth,p=\'\',o=\'\'','','','plug'],
"410"=>['search_engine','d','','','plug'],
"411"=>['call_finder','p,o','','','plug'],
"412"=>['eye','p=\'\'','','','eye'],
"413"=>['exc','d','','','utils'],
"414"=>['req','d,j=\'\'','','','utils'],
"415"=>['scanplug','','','','utils'],
"416"=>['reqp','d','','','utils'],
"417"=>['checkupdate','','','number of newest version of philum','utils'],
"418"=>['checkversion','','','','utils'],
"419"=>['utf','d','','','utils'],
"420"=>['utfb','d','','','utils'],
"421"=>['utfc','d','','','utils'],
"422"=>['secure_inputs','','','','utils'],
"423"=>['genpswd','nb=8','','','utils'],
"424"=>['alert','d','','','utils'],
"425"=>['patch_replace','bs,in,wh,repl','replace in by repl where wh in bs','confirmation success','utils'],
"426"=>['currentwidth','','','','design'],
"427"=>['curwidth_set','d','','','design'],
"428"=>['active','d,n','','','design'],
"429"=>['error_report','','','','design'],
"430"=>['chrono','d=\'\'','','','design'],
"431"=>['pr','r','','','design'],
"432"=>['window','d','','','design'],
"433"=>['eco','d,o=\'\'','','','design'],
"434"=>['verbose','r','','','design']];