<?php 
return ["_"=>['name','usage'],
"1"=>['adimg','restore images'],
"2"=>['anagram','anagrams'],
"3"=>['ascii','unicode'],
"4"=>['backup','backup sql'],
"5"=>['backupim','backup images'],
"6"=>['captor','capture datas'],
"7"=>['funcs','build tree of funcs'],
"8"=>['genpswd','password generator'],
"9"=>['simbad','names of stars'],
"10"=>['spitable','periodic table'],
"11"=>['starmap','map of stars'],
"12"=>['trans','translations'],
"13"=>['wordstats','stats of words']]; ?>