<?php 
return ['_'=>['rssurl','name','root','bot'],
1=>['www.mondialisation.ca/feed/ ','mondialisation','presse libre','1'],
2=>['wsws.org/fr/rss.xml','wsws','presse libre',''],
3=>['lesactualitesdudroit.20minutes-blogs.fr/index.rss','lesactualitesdudroit','blogs',''],
4=>['monde-diplomatique.fr/recents.xml ','monde-diplomatique','news',''],
5=>['www.pressegauche.org/spip.php?page=backend','pressegauche','blogs',''],
6=>['info-palestine.eu/backend.php','info-palestine','old',''],
7=>['resistance71.wordpress.com/feed/','resistance71','old',''],
8=>['www.investigaction.net/feed/','investigaction','presse libre','1'],
9=>['contretemps.eu/rss','contretemps','blogs',''],
10=>['feeds.feedburner.com/internetactu/bcmJ','internetactu','old',''],
11=>['https://www.bastamag.net/spip.php?page=backend','bastamag','news','1'],
12=>['tlaxcala-int.org/rss_lg.asp?lg_rss=fr','tlaxcala-int','presse libre','3'],
13=>['www.ism-france.org/rss.xml','ism-france','presse libre',''],
15=>['numerama.com/rss/news.rss','numerama','web','2'],
16=>['www.legrandsoir.info/spip.php?page=backend','legrandsoir','presse libre','1'],
17=>['www.elcorreo.eu.org/spip.php?page=backend','elcorreo','presse libre','1'],
18=>['nonfiction.fr/rss-actualites.xml','nonfiction','blogs',''],
19=>['framablog.org/index.php/feed/atom','framasoft','web',''],
20=>['blog.monolecte.fr/feed/rss2','monolecte','old',''],
21=>['gillesbonafi.blogspot.com/feeds/posts/default','gillesbonafi','old',''],
22=>['https://www.voltairenet.org/spip.php?page=backend&id_secteur=1110&lang=fr','voltairenet','presse libre','1'],
23=>['http://www.dedefensa.org/rss','dedefensa','presse libre','1'],
24=>['http://www.wikistrike.com/rss','wikistrike','old','2'],
25=>['www.agoravox.fr/spip.php?page=backend&id_rubrique=41','agoravox','blogs',''],
26=>['https://usbeketrica.com/rss','usbeketrica','news','2'],
27=>['www.alterinfo.net/xml/syndication.rss','alterinfo','news',''],
28=>['www.oulala.info/feed/','oulala','blogs',''],
29=>['www.regards.fr/spip.php?page=backend','regards','blogs',''],
30=>['www.gurumed.org/feed/','gurumed','liestream',''],
31=>['www.journaldelascience.fr/rss-home.xml','delascience','science',''],
32=>['wired.com/wiredscience/feed/','wired/science','science',''],
33=>['projetcelestia.com/feed/','projetcelestia','science',''],
34=>['naturealerte.blogspot.com/feeds/posts/default','naturealerte','science',''],
35=>['feeds.feedburner.com/DailyGeekShow?format=xml','dailygeekshow','old',''],
36=>['www.begeek.fr/feed','begeek','web',''],
37=>['almanar.com.lb/french/rss.php','almanar','news',''],
38=>['feeds.feedburner.com/oumma?format=xml','oumma','blogs',''],
39=>['www.acrimed.org/spip.php?page=backend','acrimed','presse libre','2'],
40=>['www.jetdencre.ch/feed','jetdencre','old',''],
41=>['www.gizmodo.fr/feed','gizmodo','liestream',''],
42=>['www.primitivi.org/spip.php?page=backend','19h17','old',''],
43=>['blog.agone.org/feed/rss2','agone','blogs',''],
44=>['cadtm.org/spip.php?page=backend-fr','cadtm','presse libre',''],
45=>['europalestine.com/rss','capjo','presse libre','1'],
46=>['https://www.cetri.be/spip.php?page=backend','cetri','presse libre',''],
47=>['lmsi.net/spip.php?page=backend','lmsi','blogs',''],
48=>['irinnews.org/french.xml','irin','news',''],
49=>['fr.sott.net/xml_engine/signs_rss','sott','news','1'],
50=>['reporterre.net/spip.php?page=backend','reporterre','presse libre',''],
51=>['fawkes-news.blogspot.com/feeds/posts/default','fawkes-news','blogs',''],
52=>['www.4emesinge.com/feed/','4emesinge','old','3'],
53=>['lesmoutonsenrages.fr/feed/','lesmoutonsenrages','old',''],
54=>['huffingtonpost.fr/feeds/verticals/france/index.xml','huffingtonpost','liestream',''],
55=>['mrmondialisation.org/feed/atom/','mrmondialisation','news','1'],
56=>['arretsurinfo.ch/tous-les-articles/feed/','arretsurinfo','presse libre','1'],
57=>['popsci.com/rss.xml','popsci','science',''],
58=>['ilfattoquotidiano.fr/feed/','ilfattoquotidiano','presse libre','3'],
59=>['democracynow.org/democracynow.rss','democracynow','blogs',''],
60=>['french.ruvr.ru/rss/export_all.xml','ruvr.ru','news',''],
61=>['publicsenat.fr/lcp/politique/flux/accueil','publicsenat','news',''],
62=>['www.contrepoints.org/feed','contrepoints','blogs',''],
63=>['eauxglacees.com/backend.php3','eauxglacees','old',''],
64=>['fabrice-nicolino.com/index.php/?feed=rss2','fabrice-nicolino','blogs',''],
65=>['globaldashboard.org/feed/','globaldashboard','blogs',''],
66=>['ovnis-direct.com/rss.xml','ovnis-direct','science',''],
67=>['morpheus.fr/spip.php?page=backend','morpheus','blogs',''],
68=>['fr.sputniknews.com/export/rss2/archive/index.xml','sputniknews','news','2'],
69=>['www.disclose.tv/media/rss','disclose.tv','blogs',''],
70=>['chroniquepalestine.com/category/articles/feed','chroniquepalestine','presse libre','1'],
71=>['insolentiae.com/feed/atom/','insolentiae','blogs',''],
72=>['https://lesakerfrancophone.fr/feed','lesakerfrancophone','presse libre','1'],
73=>['http://thesaker.is/feed/','thesaker','presse libre',''],
74=>['https://reseauinternational.net/feed/','reseauinternational','presse libre','1'],
14=>['http://www.francesoir.fr/rss.xml','francesoir','news','1'],
137=>['https://www.aubedigitale.com/feed/','aubedigitale','presse libre',''],
75=>['histoireetsociete.com/feed/','histoireetsociete','presse libre',''],
76=>['www.vice.com/fr/rss','vice.com','news','2'],
77=>['2012un-nouveau-paradigme.com/rss','2012un-nouveau-paradigme','blogs',''],
78=>['placegrenet.fr/feed','placegrenet','blogs',''],
79=>['lelibrepenseur.org/feed/','lelibrepenseur','blogs','3'],
80=>['https://francais.rt.com/rss','rt.com','news','1'],
81=>['bonnes-nouvelles.be/site/rss.php','bonnes-nouvelles','blogs',''],
82=>['lesbrindherbes.org/feed/','lesbrindherbes','blogs',''],
83=>['anguillesousroche.com/feed/','anguillesousroche','blogs',''],
84=>['feeds.feedburner.com/les-crises-fr','les-crises','presse libre','1'],
142=>['https://elucid.media/feed','elucid','presse libre','1'],
85=>['https://www.ldh-france.org/feed/','ldh.org','news',''],
86=>['crashdebug.fr/?format=feed&type=rss','crashdebug','presse libre',''],
87=>['maximechaix.info/?feed=rss2','maximechaix','blogs','2'],
88=>['siecledigital.fr/feed/','siecledigital','web',''],
89=>['informaction.info/rss.xml','informaction','presse libre',''],
90=>['www.tinkuy.fr/feed','tinkuy','blogs',''],
91=>['https://kauilapele.wordpress.com/feed/','kauilapele','blogs',''],
92=>['https://anticons.wordpress.com/feed/','anticons','presse libre','2'],
93=>['anonews.co/feed/','anonews','presse libre',''],
94=>['davidicke.com/feed/rss/headlines','davidicke','blogs','2'],
95=>['http://feeds.feedburner.com/zerohedge/feed','zerohedge','presse libre',''],
96=>['http://www.medelu.org/spip.php?page=backend','medelu.org','presse libre',''],
97=>['https://ruptures-presse.fr/feed/','ruptures','news',''],
98=>['https://worldpeacethreatened.com/feed','worldpeacethreatened','presse libre','3'],
99=>['http://www.pravdafrance.com/export.xml','pravdafrance','blogs','2'],
100=>['http://multinationales.org/spip.php?page=backend','multinationales','presse libre','2'],
101=>['https://lilianeheldkhawam.com/feed/','lilianeheldkhawam','presse libre','1'],
102=>['http://www.entelekheia.fr/feed/','entelekheia','presse libre','1'],
103=>['http://www.vududroit.com/feed/','vududroit','presse libre',''],
104=>['https://paris-luttes.info/spip.php?page=backend','paris-luttes','blogs','3'],
105=>['https://lepressoir-info.org/spip.php?page=backend','lepressoir-info','blogs','3'],
106=>['http://www.19h17.info/feed/','19h17','blogs','2'],
107=>['http://www.larevuedesressources.org/spip.php?page=backend','larevuedesressources','science',''],
108=>['https://dnipress.com/en/posts/rss/','dnipress','presse libre',''],
109=>['https://www.dailynews.com/news/feed/','dailynews','star',''],
110=>['http://ramzybaroud.net/feed','ramzybaroud','star',''],
111=>['http://feeds.soundcloud.com/users/soundcloud:users:59629355/sounds.rss','wagingnonviolence','star',''],
112=>['http://www.helencaldicott.com/feed/','helencaldicott','star',''],
113=>['http://chomsky.info/feed/','chomsky','star',''],
114=>['https://www.macfound.org/rss/program/21/','macfound','star',''],
115=>['http://www.huffingtonpost.fr/feeds/index.xml','huffingtonpost','star',''],
116=>['http://feeds.soundcloud.com/users/soundcloud:users:59629355/sounds.rss','wagingnonviolence','star',''],
117=>['http://www.gisti.org/spip.php?page=backend&id_rubrique=0','gisti.org','news','2'],
118=>['http://www.revolutionpermanente.fr/spip.php?page=backend','revolutionpermanente.fr','blogs','2'],
119=>['https://www.craigmurray.org.uk/feed/','craigmurray.org','blogs',''],
120=>['https://www.opendemocracy.net/xml/rss/home/index.xml','opendemocracy.net','web',''],
121=>['https://feeds.feedburner.com/undernews','undernews','presse libre','1'],
122=>['https://aa.com.tr/fr/rss/default?cat=live','aa.com','news',''],
123=>['http://www.middleeasteye.net/fr/rss','middleeasteye','presse libre',''],
124=>['https://orientxxi.info/?page=backend&lang=fr','orientxxi','presse libre','2'],
125=>['https://www.observatoiredesmedias.com/feed/','observatoiredesmedias','presse libre',''],
126=>['https://www.lewrockwell.com//feed/','lewrockwell','presse libre','2'],
127=>['http://newsnet.fr/rss/newsnet','newsnet','blogs',''],
128=>['https://la-bas.org/spip.php?page=backend','la-bas','blogs','3'],
129=>['https://www.strategic-culture.org/feed/','strategic-culture','presse libre','1'],
130=>['https://dijoncter.info/spip.php?page=backend','dijoncter.info','blogs','2'],
131=>['http://www.astrosurf.com/luxorion/rss.xml','astrosurf','science',''],
132=>['https://www.mintpressnews.com/rss/','mintpressnews','science','2'],
134=>['https://www.telesurenglish.net/rss/news.xml','telesurenglish','presse libre',''],
133=>['newsnet.fr/rss','newsnet','presse libre',''],
135=>['tomluongo.me/feed/','tomluongo','auteurs',''],
136=>['http://feeds.feedburner.com/','ZoneMilitaire','news',''],
138=>['https://asiatimes.com/?tag=ATPlus&feed=rss2','asiatimes','news',''],
139=>['https://www.grain.org/entries.rss?locale=fr','grain','presse libre',''],
140=>['https://phys.org/feeds/','phys','science',''],
141=>['https://www.infomigrants.net/fr/rss/all.xml','infomigrants','presse libre','1']]; ?>