<?php 
return [1=>['exopolitique','Quand on entend qu\'un autre monde est possible, il s\'agit d\'une croyance. En face, d\'autres opposent n\'être capables de croire que ce qu\'ils voient, mais cette assertion tournée comme une accusation, est en fait un aveu d\'irrationalité. Car avoir la foi est rationnel, tandis que lorsque ce monde dont nous parlons adviendra, il n\'y aura plus besoin d\'y croire, il sera réel ; C\'est seulement que les récalcitrants auront du mal à s\'y faire, tout au plus. 

Croire qu\'un autre monde est possible est une foi rationnelle dans la mesure où il s\'agit d\'une projection logique de l\'avenir, d\'un avenir possible, à portée de main, pour peu qu\'on y travaille et qu\'on s\'oriente vers ces objectifs nobles.
Même si c\'est difficile d\'en définir tous les aspects, on sait déjà au moins au dessiner tous les contours. Pour commencer, à la base de tout, il semble évident que la pratique du commerce n\'y a pas sa place, et qu\'à l\'inverse on se mette à coopérer, travailler ensemble, de façon orientée et organisée. Que chacun dans son travail, aussi modeste soit-il, ait conscience de contribuer à une oeuvre à l\'échelle planétaire et historique. 
Les défis que l\'humanité a à relever sont si nombreux et intenses qu\'il devient nécessaire, sur un plan évolutif, qu\'à un moment les humains s\'unissent rationnellement.

Pour moi il ne s\'agit même plus d\'une foi ou d\'une projection vague et approximative. Je connais d\'autres monde, leur fontcionnement, leurs relations, et c\'est ce que je vais exposer. 
Le but de cet exposé de mes faibles quoique passionnantes connaissances, est de révéler publiquement ce que peu de gens savent, admettent, ou sont capables de croire, et soyez-en sûr, ce que les politiciens eux, savent déjà. Mais je suis opposé à ce que le peuple reste condamné à l\'ignorance, et que les premiers-cités conservent encore logtemps leur ridicule pouvoir.

Premièrement : Oui, les extraterrestres existent, ils nous visitent, ils communiquent avec nous, ils interfèrent avec les militaires, le commandement de l\'OTAN les connait, et peut les contacter à tout moment. Du matériel et de la technologie ET ont déjà été entre leurs mains, sans pour autant qu\'ils n\'en comprennent le fonctionnement. (Il faut savoir que le commandement de l\'OTAN est pétrifié de terreur par ce qu\'il ne comprend pas).

Deuxièmement : La présence ET sur terre ne peut être révélée qu\'au moyen du travail conjoint des concitoyens, par le bouche-à-oreilles en quelque sorte. Il s\'agit là d\'une règle extrêmemnt importante, puisqu\'elle est à la base du principe de Liberté appliqué à l\'ensemble des habitants d\'une planète, Liberté qui elle-même est le principe le plus important du Cosmos. 
L\'information transmise doit être de qualité, et provenir de personnes de confiance. En l\'absence ou complément de cela il ne vous reste qu\'à faire votre propre investigation sur internet, tant que c\'est encore possible... Le secret n\'est pas si opaque qu\'il n\'y paraît, car les ET désirent se faire connaître, et désirent profondément communiquer.

Troisièmement : La vie sur ces planètes qui nous visitent laisse entrevoir qu\'ils ne pratiquent pas le commerce entre eux. L\'intérêt de souligner ce point essentiel est que ces civilisations, qui sont plus avancés et anciennes que la nôtre, doivent nous servir d\'exemple. Elles vivent en paix, au sein d\'un gouvernement modial, dont la légitimité est telle que chacun lui voue un quasi-culte, et un immense respect. Chez eux, devenir politicien est un immense honneur. Le respect qu\'ils ont pour leurs supérieurs hiérarchiques est tel que ces derniers se sentent obligés de se présentent comme étant avant tout au service de leurs subordonnés. En effet, s\'ils bénéficient d\'une intelligence supérieure, et qu\'ils ils reçoivent une formation adaptée, et ont une parfaite conscience de la responsabilité qui leur incombe.

Quatrièrmement : Les relations et le rôle des civilisations à travers la galaxie sont simples et évidentes : elles s\'inter-surveillent. La prérogative universelle de l\'humanité consiste à aller à la découverte de nouveaux mondes, et à porter assisance à ceux qui sont dans le besoin. Dans ce cadre, elles exercent les unes sur les autres un rôle de veille empli de bienveillance et de précaution. Cette surveillance est bienvenue et honorable, car philosophiquement ils sont porteurs de perspectives nouvelles et enrichissantes. 
En effet, il ne s\'agit pas, comme les américains-barbares, de donner des ordres en disant de faire comme ceci ou cela. Chaque humanité doit scrupuleusement suivre sa propre voie évolutive et faire ses propres choix. Dans ce cadre la règle est celle de l\'ingérence. Quand ces planètes ont des objectifs communs, elles peuvent se confédérer ponctuellement ou à plus long terme. Les raisons pour lesquelles ils choisissent de faire leur mission sur Terre est très vraisemblablement d\'ordre sentimental, et / ou d\'ordre technique (ressemblance physique).

Cinquièmement : Le nombre de planètes habitées dans la galaxie est très élevé. Il y en a environ 32 à 100 AL, 2048 à 1000 AL. La durée des voyages spaciaux dépend de l\'avancement de chacune, mais pour celles qui nous surveillent il faut six mois de voyage pour venir jusqu\'à nous. Parmi le très grand nombre qui nous visitent occasionnellement, aucune n\'a le droit de se faire voir, mais parfois, comme les humains, 2 à 3% d\'entre eux sont des criminels. Tant que notre planète reste surveillée par une confédération ponctuelle, ils seraient détruits s\'ils tentaient d\'intervenir, cependant des êtres gris, de petite taille, sans aucun sens moral, a pu déjouer ces barricades en provoquant un crash, à Roswell en 1947. Une deuxième race hostile, colonialiste, fait partie des dangers qui nous menacent. Ils procèdent à long terme et veulent s\'accaparer nos richesses, qui somme toutes, sont assez rares. La planète Terre est considérée comme \"un joyau\". Pour cela ils bénéficient de l\'aide des personnes de pouvoir (dites \"les élites\"), et ils leur tendent des arnaques puissantes, en jouant sur leur complexe de supériorité. 

Sixièmement : Depuis 1947 l\'ingérence stricte a donc été, légitmement, semi-levée. Il s\'en est suivi une politique de lente habituation à leur présence. En effet les dangers qui menacent la Terre sont multiples. Outre la présence des races hostiles qui est suivie de très près et modulée au maximum, les dangers intérieurs sont au moins aussi grands et périlleux. Parmi ceux-là, ils notent la perte de liberté, la démocratie factice, une \"oligo-dictature\" [1:nh], et surtout en tout premier lieu, les effets de la fin de la civilisation. En effet, notre civilisation, en raison de ce qu\'elle se base sur des principes obsolètes, et qui est régie par des règles absurdes, court à sa perte, et ceci, à court terme. Cela a souvent été le cas dans notre passé, autant que dans les leurs. Mais l\'humanité survivra, indépendamment de cette ère qu\'ils considèrent comme \"des heures sombres\".

Septièmement : Un effondrement économique va ravager les villes du monde et pousser les peuples à retourner en campagne. Notez que certains bâtiments militaires sont déjà prêts à cette éventualité. Ce qui assurera la survie de tout à chacun, est la préparation à cet effondrement. Une \"guerre civile mondiale\" est attendue. Pour sauver vos vies et celles de vos familles il faut impérativement s\'unir et créer des villages auto-suffisants, en eau, nourriture, électricité, et médicaments. 

Conclusion : Pour ce qui nous concerne, en temps que contactés, il ne nous a rien été demandé explicitement. Simplement les faits nous ont été exposés, à l\'occasion uniquement des questions que nous avons pu poser. Nous ne nous sentons pas du tout à la hauteur de ces communications qui sont de l\'ordre de l\'exo-politique. C\'est le hasard qui a fait de nous des sortes d\'ambassadeurs de la Terre. Il est certains qu\'étant donné qu\'aucun pouvoir politique n\'est légitime, il aurait été superflu que ces informations informations leur soit transmises, dans l\'optique qu\'elles préviennent les populations. Cela aurait été leur rôle, cependant ce sont eux-mêmes qui sont les artisans de cet apocalypse, dont l\'industrie sera bénéficiaire.

J\'en reviens à un principe essentiel dans ce qui fait la légitimité, d\'un choix, d\'une élection, ou d\'un pouvoir, c\'est le fait d\'appartenir à un réseau social qui soit correctement informé, et le fait que ses membres soient pro-actifs au sein de ce réseau. Cela implique une très grande écoute de chacun, et une grande capacité à avoir foi en les personnes qui nous sont proches, lorsqu\'elles transmettent une information. 
Cette façon de procéder est opposée à celle, industrielle, des médias. Eux, s\'imaginent que l\'information vient d\'en haut et peut être distribuée de façon standardisée à tout le monde, d\'un coup, facilitant et accélérant le travail d\'information. Cependant cette voie d\'accès à l\'information est improprement utilisée pour diffuser des opinions tendancieuses, mensongères, et finalement néfastes si l\'auditeur n\'a pas les informations nécessaires pour s\'en prémunir. Il est impératif de rejeter négativement toute instruction ou discours qui ne soit pas présenté sous forme de \"tiret-à-la-ligne\" et d\'en examiner scrupuleusement la logique sur laquelle elles se fondent. Car pour qu\'une opinion personnelle soit entendue correctement par tous, il faut que les auditeurs soient formatés - ce que ces discours tendent à faire - et finalement incapables d\'exercer leur propre liberté. 

Alors Oui, pour en revenir à l\'essentiel, Un autre monde est possible, et d\'ailleurs ils nous visitent, avec un esprit empli de bienvaillance et aussi d\'effroi face aux crimes monstueux qui sont perpetrés au nom d\'idéaux abérrants. Des crimes contre les humains et contre la nature, qui confisquent à l\'humanité de la Terre les moyens qui lui ont été légués d\'évoluer confortablement. C\'est sa survie à long terme qui est en péril. 
Car la vie est un bien précieux et fragile.

[1:nb] [http://oumo.fr/1020|Conseils sur la façon de structurer une nouvelle société sur la Terre.] [http://www.ummo-sciences.org/fr/O1.htm]

']]; ?>