<?php 
return ['_'=>['block','module','param','title','condition','command','option','cache','hide','template','bt','div','prv','pop'],
2=>['system','blocks','banner cover menu content footer','','','','','','','','','','',''],
3=>['system','content','800','','','','','','','','','','',''],
4=>['footer','contact','1','Message à Newsnet','','','','1','1','','','','',''],
5=>['footer','conn','newsnet:picto','','','','','','','','','','',''],
6=>['content','prev_next','','','art','','','','','','','','',''],
7=>['content','Page_titles','','','art','','parent','','','','','','',''],
8=>['system','design','92','','','','','','','','','','',''],
9=>['system','template','','','','','','','','','','','',''],
10=>['newsletter','articles','priority=4&nbdays=1','Articles épiques','','multi','','','','','','','',''],
11=>['content','LOAD','','','art','','','','','','','','',''],
12=>['footer','chrono','','','','','','','','','','','',''],
13=>['banner','app','citation_call','','home','','','','','','','','',''],
14=>['banner','app','meteo_build','','home','','','','','','','','',''],
15=>['content','api','cmd:tracks','Tracks','notes','','','','','','','','',''],
16=>['content','LOAD','','','home','','','','','','','','',''],
17=>['newsletter','articles','nbdays:1,priority:3,preview:auto','Grands titres / 24h','','multi','','','','','','','',''],
18=>['content','favs','','Favoris','favoris','','-','','','','','','',''],
19=>['content','most_read','7-24','Les plus lus','charts','cols','3','','','','','','',''],
20=>['content','folders','10','Dossiers','dossiers','articles','-','','','','','','',''],
21=>['content','suggest','home','publier','publier','','','','','','','','',''],
22=>['content','articles','id:996','Lisez : La Société-Réseau','pub','read','-','','1','','','','','1'],
23=>['content','rssin','','Flux Rss','rss','','-','','','','','','',''],
24=>['content','conn_playlist','mp3','Audio','audio','articles','','','','','','','',''],
25=>['menu','MenuBub','','bubmenu','','','','','1','','','','',''],
26=>['content','deja_vu','','','deja_vu','icons','','','','','','','',''],
27=>['content','stats','7','stats','stats','','','','','','','','',''],
28=>['content','plug','fav','','fav','','','','','','','','',''],
29=>['content','tracks','7','Commentaires','tracks','','','','','','','','',''],
30=>['content','desktop_varts','360','Dossiers thématiques','repertoires','','','','','','','','',''],
31=>['content','related_arts','','En référence à :','art','panel','blocks','','','panart_j','','','',''],
32=>['content','related_by','','Article cité par :','art','panel','blocks','','','panart_j','','','',''],
33=>['content','connector','[84681:art]
[84681:read]

[100 leaders et modèles pour la Paix et la Justice:h][newsnet_links_6:msq_conn]

[https://www.transcend.org/tms/2018/01/in-pursuit-of-peace-and-justice-100-peace-justice-leaders-and-models/]','Hall of Fame','Hall of Fame','','article','','','','','','',''],
34=>['menu','MENU','contentmenu','Menus','home','','','','','','','','',''],
35=>['contentmenu','api_arts','priority:3|4,nbdays:14,preview:2,nodig:1','Analyses','home','','','','','','','','',''],
36=>['contentmenu','api_arts','nbdays:1,preview:2','24h','home','','','','','','','','',''],
37=>['contentmenu','api_arts','priority:1|2,nbdays:7,preview:2,nodig:1','Faits simples','home','','','','','','','','',''],
38=>['contentmenu','api_arts','priority:4,nbdays:90,preview:2','Articulations historiques','home','','','','','','','','',''],
39=>['newsletter','articles','priority:1,nbdays:1,preview:false','Actu','','multi','','','1','','','','',''],
40=>['tweetfeed','api_arts','priority:3,preview:1','Fil Twitter','','','','','','','','','',''],
41=>['tweetfeed','api_arts','priority:4,preview:1','Articles mémorables','','','','','','','','','',''],
42=>['content','LOAD','','','cat','','preview','','','','','','',''],
43=>['cover','articles','priority=4|5&hours=24&nodig=1','','home','panel','blocks','','','panart_j','','','',''],
44=>['content','api','','','api','','1','','','','','','',''],
45=>['content','conn_playlist','video','Vidéos','video','articles','','','','','','','',''],
46=>['content','agenda','','Agenda','agenda','articles','','','','','','','',''],
47=>['newsletter','articles','priority:1,nbdays:1,preview:false','Actu','','multi','','','1','','','','',''],
48=>['contentmenu','classtag_arts','auteurs','Auteurs','home','panel','inline','','','panart_j','','','',''],
49=>['contentmenu','classtag_arts','auteurs','Auteurs spéciaux','home','panel','inline','','1','panart_j','','','',''],
50=>['contentmenu','folders','','Dossiers en cours','home','articles','','','','','','','',''],
51=>['contentmenu','api_arts','folder:Grand changement','Great shift','home','','','','','','','','',''],
52=>['contentmenu','taxo_nav','','Cheminements','home','','','','','','','','',''],
53=>['contentmenu','catj','documentaires','Catégories','home','','','','','','','','',''],
54=>['contentmenu','conn_playlist','video','Vidéos','home','articles','','','','','','','',''],
55=>['contentmenu','conn_playlist','twitter','Twits','home','articles','','','','','','','',''],
56=>['contentmenu','conn_playlist','audio','Audio','home','articles','','','1','','','','',''],
57=>['contentmenu','conn_playlist','pdf','Pdf','home','articles','','','1','','','','',''],
58=>['contentmenu','conn_playlist','img','Images','home','articles','','','','','','','1',''],
59=>['contentmenu','api','cmd:tracks,ti:Commentaires','Commentaires','home','','','','','','','','',''],
60=>['contentmenu','api_chan','1','','home','','','','1','','','','',''],
61=>['contentmenu','read','514','À propos','home','','','','','','','','',''],
62=>['contentmenu','app','pad','Pad','home','','','','1','','','','',''],
63=>['system','desktop','','','','','','','1','','','','',''],
64=>['contentmenu','suggest','','Proposer un article','home','','','','1','','','','',''],
65=>['contentmenu','most_read','7','+ Lus','home','panel','inline','','','panart_j','','','',''],
66=>['system','ARTMOD','ARTMOD','','','tabs','','','','','','','',''],
67=>['ARTMOD','related_arts','','Articles liés','','','','','','','','','',''],
68=>['ARTMOD','related_by','','Cité par','','','','','','','','','',''],
69=>['ARTMOD','parent_art','','Article parent','','','','','','','','','',''],
70=>['ARTMOD','child_art','','Dossier d\'articles','','','','','','','','','',''],
71=>['ARTMOD','same_tags','','Articles similaires','','','','','','','','','',''],
72=>['dev','popart','','','home','','','','','','','','',''],
73=>['content','read','514','Pro-Activité','pub','','','','','','','','','']]; ?>