<?php 
return ['_'=>['root','action','type','button','icon','auth'],
1=>['Newsnet','m:context,p:home','page','Accueil','nn',''],
2=>['Newsnet','36495','art','A propos','smile',''],
3=>['Newsnet','/rss','','Flux Rss','rss',''],
4=>['Newsnet','/context/rss','','Réception Rss','rss2',''],
5=>['Newsnet','/context/publier','','Publier','edit','8'],
6=>['Newsnet','apicom,home','popup','Api','atom',''],
7=>['Newsnet','32','module','Hall of Fame','trophee',''],
8=>['Newsnet','tracks,home___newsnet','popup','Contact','mail',''],
9=>['Newsnet','stats,home','popup','Stats','stats',''],
10=>['Navigation','nbdays=7&preview=2,t:Tout,m:api_arts','module','Toutes catégories','globe',''],
11=>['Navigation','priority=4&nbdays=90&preview=2,t:Articulations,m:api_arts','module','Articulations','journal',''],
12=>['Navigation','p:priority=3|4&nbdays=14&preview=2&nodig=1,t:Analyses,m:api_arts','module','Analyses','articles',''],
13=>['Navigation','priority=2&nbdays=7&preview=2&nodig=1,t:Instantanés,m:api_arts','module','Instantanés','article',''],
14=>['Navigation','priority:1;nbdays:7;preview:2;nodig:1,t:Faits,m:api_arts','module','Faits','doc',''],
15=>['Navigation','p:auteurs,t:Auteurs,d:panel,o:inline,tp:panart_j,m:classtag_arts','module','Auteurs','user',''],
16=>['Navigation','t:Dossiers en cours,d:articles,m:folders','module','Dossiers d\'articles','folder2',''],
17=>['Navigation','p:Déroulements,m:taxo_nav','module','Déroulements','topo-open',''],
18=>['Navigation','t:Dossiers thématiques,m:api_chan','module','Chaînes','virtual',''],
19=>['Navigation','p:video,t:Vidéos,d:articles,m:conn_playlist','module','Vidéos','youtube',''],
20=>['Navigation','p:audio,t:Audio,d:articles,m:conn_playlist','module','Audio','sound',''],
22=>['Navigation','p:pdf,t:Pdf,d:articles,m:conn_playlist','module','Pdf','pdf',''],
44=>['Navigation','t:Liens web,d:articles,m:webs','module','Webs','web',''],
23=>['Navigation','p:twitter,t:Twits des articles,d:articles,m:conn_playlist','module','Twits','tw2',''],
21=>['Navigation','t:Commentaires,m:tracks','module','Commentaires','chat',''],
25=>['Navigation','p:favs,m:app','module','Favoris','like',''],
26=>['Navigation','m:suggest','module','Proposer','write',''],
27=>['Navigation','p:pub,m:context','module','Pub','prosperity',''],
28=>['Navigation','m:context,p:Hall of Fame','content','Hall of Fame','medal',''],
29=>['Sections','','overcat','Sections','level','8'],
30=>['Classements/Catégories','o:popapi,m:cats','mod','Catégories','',''],
31=>['Classements/Tags','p:tag,t:Tags,d:lines,o:popapi,m:tags','mod','Définitions','',''],
32=>['Classements/Auteurs','p:auteurs,t:Auteurs,d:lines,o:popapi,m:tags','mod','Auteurs','',''],
33=>['Classements/Thèmes','p:thèmes,t:Thèmes dactualité,d:lines,o:popapi,m:tags','mod','Thèmes','',''],
34=>['Classements/Pays','p:pays,t:Pays,d:lines,o:popapi,m:tags','mod','Pays','',''],
35=>['Classements/Types dinfos','p:type,t:Type dinfo,d:lines,o:popapi,m:tags','mod','Types','',''],
36=>['Classements/Sources','d:line,o:popapi,m:sources','mod','Sources','',''],
37=>['Classements/Personnalités','p:personnalité,t:Personnalités,d:lines,o:popapi,m:tags','mod','Pays','',''],
38=>['Classements/Consortiums','p:org,t:Consortiums,d:lines,o:popapi,m:tags','mod','users','',''],
39=>['Classements/Metas récents','p:100,d:lines,o:popap,m:last_tags','mod','Tags','',''],
40=>['Classements/Répertoires virtuels','d:lines,o:popap,m:folder','mod','Tags','','8'],
41=>['Classements/Recherches enregistrées','p:100,d:lines,o:popapi,m:last_search','mod','Tags','',''],
43=>['Classements/Années','p:100,d:lines,o:popapi,m:timetravel','mod','clock','',''],
42=>['Classements/Articles','','arts','Articles','','']]; ?>