<?php 
return ['_'=>['rssurl','name','root','bot'],
1=>['www.mondialisation.ca/feed/ ','mondialisation','presse libre','1'],
2=>['lesactualitesdudroit.20minutes-blogs.fr/index.rss','lesactualitesdudroit','blogs'],
3=>['monde-diplomatique.fr/recents.xml ','monde-diplomatique','news',''],
4=>['www.pressegauche.org/spip.php?page=backend','pressegauche','blogs'],
5=>['info-palestine.eu/backend.php','info-palestine','old',''],
6=>['resistance71.wordpress.com/feed/','resistance71','blogs'],
7=>['www.investigaction.net/feed/','investigaction','presse libre','1'],
8=>['contretemps.eu/rss','contretemps','blogs'],
9=>['feeds.feedburner.com/internetactu/bcmJ','internetactu','web',''],
10=>['bastamag.net/spip.php?page=backend','bastamag','news','1'],
11=>['tlaxcala-int.org/rss_lg.asp?lg_rss=fr','tlaxcala-int','presse libre','1'],
12=>['www.ism-france.org/rss.xml','ism-france','presse libre','1'],
13=>['altermonde-sans-frontiere.com/spip.php?page=backend','altermonde','presse libre','2'],
14=>['numerama.com/rss/news.rss','numerama','web','2'],
15=>['www.legrandsoir.info/spip.php?page=backend','legrandsoir','presse libre','1'],
16=>['www.elcorreo.eu.org/spip.php?page=backend','elcorreo','presse libre','1'],
17=>['nonfiction.fr/rss-actualites.xml','nonfiction','blogs'],
18=>['framablog.org/index.php/feed/atom','framasoft','web'],
19=>['blog.monolecte.fr/feed/rss2','monolecte','old',''],
20=>['gillesbonafi.blogspot.com/feeds/posts/default','gillesbonafi','old'],
21=>['voltairenet.org/spip.php?page=backend&id_secteur=1110&lang=fr','voltairenet','presse libre','1'],
22=>['http://www.dedefensa.org/rss','dedefensa','presse libre','1'],
23=>['http://www.wikistrike.com/rss','wikistrike','blogs','2'],
24=>['www.agoravox.fr/spip.php?page=backend&id_rubrique=41','agoravox','blogs'],
25=>['bellaciao.org/fr/backend.php3','bellaciao','news'],
26=>['www.alterinfo.net/xml/syndication.rss','alterinfo','news'],
27=>['www.oulala.info/feed/','oulala','blogs',''],
28=>['www.regards.fr/spip.php?page=backend','regards','blogs'],
29=>['www.gurumed.org/feed/','gurumed','science'],
30=>['www.journaldelascience.fr/rss-home.xml','delascience','science'],
31=>['wired.com/wiredscience/feed/','wired/science','science'],
32=>['projetcelestia.com/feed/','projetcelestia','science'],
33=>['naturealerte.blogspot.com/feeds/posts/default','naturealerte','science'],
34=>['feeds.feedburner.com/DailyGeekShow?format=xml','dailygeekshow','web'],
35=>['www.begeek.fr/feed','begeek','web'],
36=>['almanar.com.lb/french/rss.php','almanar','news'],
37=>['feeds.feedburner.com/oumma?format=xml','oumma','blogs',''],
38=>['acrimed.org/spip.php?page=backend','acrimed','news','2'],
39=>['www.jetdencre.ch/feed','jetdencre','blogs'],
40=>['www.gizmodo.fr/feed','gizmodo','web'],
41=>['www.primitivi.org/spip.php?page=backend','primitivi','old'],
42=>['blog.agone.org/feed/rss2','agone','blogs'],
43=>['cadtm.org/spip.php?page=backend-fr','cadtm','presse libre','1'],
44=>['europalestine.com/spip.php?page=backend','capjo','presse libre','1'],
45=>['cetri.be/spip.php?page=backend&id_rubrique=38','cetri','presse libre','1'],
46=>['lmsi.net/spip.php?page=backend','lmsi','news'],
47=>['irinnews.org/french.xml','irin','news'],
48=>['fr.sott.net/xml_engine/signs_rss','sott','news',''],
49=>['reporterre.net/spip.php?page=backend','reporterre','presse libre','1'],
50=>['fawkes-news.blogspot.com/feeds/posts/default','fawkes-news','blogs',''],
51=>['www.4emesinge.com/feed/','4emesinge','blogs','3'],
52=>['lesmoutonsenrages.fr/feed/','lesmoutonsenrages','blogs',''],
53=>['huffingtonpost.fr/feeds/verticals/france/index.xml','huffingtonpost','news',''],
54=>['mrmondialisation.org/feed/atom/','mrmondialisation','news',''],
55=>['arretsurinfo.ch/tous-les-articles/feed/','arretsurinfo','presse libre','1'],
56=>['popsci.com/rss.xml','popsci','science',''],
57=>['ilfattoquotidiano.fr/feed/','ilfattoquotidiano','presse libre','3'],
58=>['democracynow.org/democracynow.rss','democracynow','blogs',''],
59=>['french.ruvr.ru/rss/export_all.xml','ruvr.ru','news',''],
60=>['publicsenat.fr/lcp/politique/flux/accueil','publicsenat','news',''],
61=>['www.contrepoints.org/feed','contrepoints','blogs',''],
62=>['eauxglacees.com/backend.php3','eauxglacees','blogs',''],
63=>['fabrice-nicolino.com/index.php/?feed=rss2','fabrice-nicolino','blogs',''],
64=>['globaldashboard.org/feed/','globaldashboard','blogs',''],
65=>['ovnis-direct.com/rss.xml','ovnis-direct','science',''],
66=>['morpheus.fr/spip.php?page=backend','morpheus','blogs',''],
67=>['fr.sputniknews.com/export/rss2/archive/index.xml','sputniknews','news','2'],
68=>['www.disclose.tv/media/rss','disclose.tv','blogs',''],
69=>['insolentiae.com/feed/atom/','insolentiae','blogs',''],
70=>['lesakerfrancophone.fr/feed','lesakerfrancophone','presse libre','1'],
71=>['histoireetsociete.wordpress.com/feed/','histoireetsociete','presse libre','1'],
72=>['www.vice.com/fr/rss','vice.com','news',''],
73=>['2012un-nouveau-paradigme.com/rss','2012un-nouveau-paradigme','blogs',''],
74=>['placegrenet.fr/feed','placegrenet','blogs',''],
75=>['lelibrepenseur.org/feed/','lelibrepenseur','blogs','3'],
76=>['https://francais.rt.com/rss','rt.com','news','1'],
77=>['bonnes-nouvelles.be/site/rss.php','bonnes-nouvelles','blogs',''],
78=>['lesbrindherbes.org/feed/','lesbrindherbes','blogs',''],
79=>['anguillesousroche.com/feed/','anguillesousroche','blogs',''],
80=>['feeds.feedburner.com/les-crises-fr?format=xml','les-crises','blogs',''],
81=>['ldh-france.org/feed/','ldh.org','news',''],
82=>['crashdebug.fr/?format=feed&type=rss','crashdebug','presse libre',''],
83=>['maximechaix.info/?feed=rss2','maximechaix','blogs','2'],
84=>['siecledigital.fr/feed/','siecledigital','web',''],
85=>['informaction.info/rss.xml','informaction','presse libre',''],
86=>['www.tinkuy.fr/feed','tinkuy','blogs',''],
87=>['https://kauilapele.wordpress.com/feed/','kauilapele','blogs',''],
88=>['https://anticons.wordpress.com/feed/','anticons','presse libre','2'],
89=>['anonews.co/feed/','anonews','presse libre',''],
90=>['davidicke.com/feed/rss/headlines','davidicke','blogs','2'],
91=>['http://feeds.feedburner.com/zerohedge/feed','zerohedge','presse libre',''],
92=>['http://reseauinternational.net/feed/','reseauinternational','blogs',''],
93=>['http://www.medelu.org/spip.php?page=backend','medelu.org','presse libre','1'],
94=>['https://ruptures-presse.fr/feed/','ruptures','news',''],
95=>['https://worldpeacethreatened.com/feed','worldpeacethreatened','presse libre','3'],
96=>['http://www.pravdafrance.com/export.xml','pravdafrance','blogs','2'],
97=>['http://multinationales.org/spip.php?page=backend','multinationales','presse libre','1'],
98=>['https://lilianeheldkhawam.com/feed/','lilianeheldkhawam','presse libre',''],
99=>['http://www.entelekheia.fr/feed/','entelekheia','presse libre','1'],
100=>['https://paris-luttes.info/spip.php?page=backend','paris-luttes','blogs','3'],
101=>['https://lepressoir-info.org/spip.php?page=backend','lepressoir-info','blogs','3'],
102=>['http://www.19h17.info/feed/','19h17','blogs','2'],
103=>['http://www.larevuedesressources.org/spip.php?page=backend','larevuedesressources','science',''],
104=>['https://dnipress.com/en/posts/rss/','dnipress','presse libre',''],
105=>['https://www.dailynews.com/news/feed/','dailynews','star',''],
106=>['http://ramzybaroud.net/feed','ramzybaroud','star',''],
107=>['http://feeds.soundcloud.com/users/soundcloud:users:59629355/sounds.rss','wagingnonviolence','star',''],
108=>['http://www.helencaldicott.com/feed/','helencaldicott','star',''],
109=>['http://chomsky.info/feed/','chomsky','star',''],
110=>['https://www.macfound.org/rss/program/21/','macfound','star',''],
111=>['http://www.huffingtonpost.fr/feeds/index.xml','huffingtonpost','star',''],
112=>['http://feeds.soundcloud.com/users/soundcloud:users:59629355/sounds.rss','wagingnonviolence','star','']]; ?>