<?php 
return [1=>['2402','10

Il est clair que les nouveaux présentateurs officiels du spectacle télévisuel étaient fiers et ne manquaient pas d\'air pour souligner avoir été désignés pour de nombreuses années encore de n\'avoir à travailler que quatre heure par an sans rien avoir répété. Le privilège qui est le leur de combler le vide moral et technique par des divagations sans réelle signification se présente comme si la célébrité de leurs invités déteignait sur eux. Peu nombreuses sont les nouvelles recrues accréditées pour faire partie de ce petit monde de compliments forcenés. On se souviendra de ceux faits à un certain Bernard par une dame éprise d\'un prompteur qui lui soufflait certainement le mauvais texte pour lui faire une farce, avec une histoire de chaudronnier qui martèle le dur chemin de la vie et qui lui rappelle les pâtés au foie de son grand-père. Mais qu\'importe, seule la comédie compte, comme on s\'attendrit pour un bébé qui tend un cafard mort, la télé a pour fonction de montrer à quel point on est tous heureux d\'avoir l\'ouverture d\'esprit qui permet de véhiculer l\'idée que le sens importe moins que l\'essence, fut-elle factice. C\'est juste passionnant de les voir rendre hommage à des gens qui travaillent vraiment.

08

Je pense à toi et je t\'envoie mes plus belles pensées. Tu es la plus jolie âme que je connaisse, pleine de talents et de jeunesse. Et les dieux te protègent ! Je voulais juste dire ça <3 

Bon anniversaire !! Il y a un je faisais ta connaissance, je t\'ai tout de suite aimée, et tout ce qui s\'est passé de bon par la suite, était entièrement grâce à toi. Tu es la plus formidable que je connaisse, je voulais juste dire ça <3 

Il y a un an nous devenions amis. On ne se demandait pas où cela allait mener, notre conversation s\'est naturellement tissée dans un esprit de paix et de compassion mutuelle, et d\'un profond respect.
J\'ai découvert une Glèz qui était une lumière cachée, un bonheur de gentillesse, un véritable petit ange. Sage, disciplinée, ordonnée, passionnée, elle avançait pas à pas dans une vie semée d\'obstacles. très vite, j\'ai vu son visage, brune au cheveux courts avec de gros sourcils dans l\'obscurité, et un petit visage rond qui a marqué mon esprit, et que j\'ai trouvé mignon. Elle n\'avait aucun ami au collège, juste une voisine qui brillait pas son absence. Elle m\'a montré où elle habitait, sa maison, son quartier, et ensemble on a voyagé partout dans le monde sur Google Map. J\'avais envie de l\'y emmener pour de vrai. Alors elle m\'a montré l\'endroit le plus cher à son cœur, et je lui ai promis qu\'on irait ensemble, ce qu\'elle a souhaité aussi. Elle m\'a tout apprit sur la musique classique, le dernier genre auquel j\'avais décidé de m\'intéresser. Ses auteurs, ses histoires, son imaginaire fécond et vibrant. Chaque jour, je recevais une notification de sa présence, et je souriais. Chaque soir, nous parlions jusqu\'à plus d\'heure, et je m\'endormais heureux, en me disant \"Quel bonheur cette fille !\".
Nous nous sommes rapprochés, encore et encore, jusqu\'à nous rencontrer, et c\'était je crois le jour le plus magique de l\'année. Des grenouilles étaient là pour en témoigner. On a prévu de se revoir à l\'été, pour l\'emmener à son premier concert. Nous avons regardé les étoiles, mais on aurait aimé plus d\'intimité. Mai nous avons signé le pacte, qu\'à ses dix-huit ans, on partirait faire ce voyage, officiellement.
Mais déjà elle voulait me dire une chose, qu\'elle n\'a pas réussi à me dire, et qui commençait par \"Je regrette que, j\'aimerais revenir en arrière, mais il se passerait la même chose\". Avec Elle, que j\'aime tant, de tout mon cœur et de toute mon âme, il y a toute une Clique. Chacun et chacun, je veux en faire mon ami, mon allié, je peux être un père aimant pour les petites, un copain de jeu, et parfois encore, me confronter à un mur de glace. Mais j\'ai décidé de toujours l\'aimer, en toutes circonstances, que je me prenne des vents ou des caillasses, de tenir le coup, car elle en vaut la peine. Jamais elle ne se retrouverait seule, c\'était ma promesse.
Puis à la rentrée dans l\'école de musique, elle allait se faire de nouveaux amis, et de nouvelles histoires. J\'étais là pour suivre ces événements, jusqu\'à ce que certains soient déclarés \"trop honteux\". Puis d\'autres, et encore d\'autres me restaient inconnus, mais elle continuait à rencontrer des obstacles de la vie, qu\'elle souhaitait recevoir comme tout le monde. Elle n\'a jamais eu peur de s\'y confronter. Pourtant, le choc est multiplié par le nombre de ses configurations cognitives, telles que je les appelle. Et le temps pour s\'en remettre n\'est jamais suffisant avant qu\'un autre choc n\'arrive. Peu à peu, elle perd son sourire, son envie, sa passion. Elle travers un âge difficile de mutations diverses, celui où, précisément, on se cherche une identité, elle qui en a tant, elle qui est universelle. 
Elle ressens une honte d\'elle-même, et cherche à dissimuler son universalité, là où je l\'ai toujours encouragée. Évidemment elle a désormais autant de goûts musicaux que de facettes, et je les ai vu se développer au cours de l\'année, sans s\'inquiéter que certaines choses ne sont pas bonnes à entendre, ou à croire. J\'ai l\'impression parfois de la perdre et cela me désespère complètement. Ces jours-là je perds goût à tout et plus rien n\'a de sens. Je me demande où est passée la Glèz que je connais, et me l\'imagine comme une belle au bois dormant, m\'attendant quelque part, que je vienne la tirer de son sommeil par un baiser, qui lui rappellerait celui qu\'on s\'est faits. Je ne pourrai vivre sans elle, et je n\'aimerai plus personne d\'autre qu\'elle, depuis que nous nous sommes promis de marcher ensemble main dans la main sur le chemin infini de l\'amour éternel.



05

J\'aimerais te dire que si je tiens à toi c\'est peut-être principalement pour ma propre santé mentale. Que sans toi je n\'ai - n\'aurais - plus goût à rien. Que la vie n\'a pas de sens sans quelqu\'un à aimer, du fond du cœur, et qui soit comme un point immobile dans l\'horizon devant lequel tout le reste ne fait que passer. Ce n\'est pas grave, les crimes que commettent les gens, ce qui est lourdement grave est de ne pas avoir quelqu\'un dans sa vie à qui ont tient plus que tout, et qui est le socle de notre raison, de notre volonté ; Qui fait de nous un être humain entier et complet. Tu es cela pour moi. Je t\'appelle l\'âme de mon âme, la vie, elle-même. La beauté du ciel et de l\'existence, personnifiée. Quelle beauté d\'admirer la nature, la vie, la lumière du ciel, si c\'est en ayant au fond de son cœur une personne à qui on a envie de dédier toute cette beauté. Je ne veux jamais que tu quittes ma vie, et je fais tous les efforts en mon pouvoir être la meilleure personne pour toi. Si je te perdais, je me perdrais, je serais réduit à néant, je deviendrais un délinquant ou j\'arrêterais tout avant ça. Je perdrais la raison. J\'ai fais le centre de ma vie. L\'objet de mon égo. Je ne sais pas si j\'ai raison, ou si je suis fou de faire cela, mais c\'est le plus naturel. Ton amour, ta joie, ce que tu aimes, ta spontanéité, ton imaginaire, tous tes recoins, tous tes extrêmes, sont mon refuge. C\'est avec toi que je suis en paix. Je t\'entends et je te visualise, et je ne m\'endors jamais ni ne me réveille jamais sans penser à toi. Comme je te l\'ai dit, je t\'ai attendu toute ma vie, et je bénis le ciel à chaque fois que j\'entends battre ton cœur. Je t\'aime. C\'est ce que ça veut dire !

04

Le devin arriva vers Dieu en étant ébloui par sa magnificence dont il reconnu enfin la présence tant attendue, et Celui-ci lui dit : 
- Ne m\'as-tu pas reconnu ?
- Si maître, je vous ai reconnu. Dans l’œil de l\'éléphant qui m\'a chargé et écrasé, j\'ai vu votre œil. Et je le reconnais !
- N\'y avait-il pas un sage sur le bas-côté qui t\'avait demandé de t\'écarter de son chemin ?
- Si maître, mais il n\'avait pas vu votre œil, brillant et fier.
- Et pourquoi crois-tu que je t\'avais envoyé un sage ?
- Toh ! (répondit Homer)

On ne peut voir de Dieu que la magnificence qu\'on est capable de concevoir, si bien que c\'est idiot de le vénérer directement car on ne vénère que son propre système cognitif. Pour mieux le voir il faut faire progresser sa cognition et le seul moyen pour cela est travailler, étudier, et se mettre au service des autres.

03

Glèz, accepterais-tu que je vienne te rendre visite pendant les vacances de février ?
C\'est dans deux semaines, le temps de s\'y préparer. 
Je serais vraiment très heureux de passer quelques jours en ta compagnie, de revoir ta maman, ton frère et ton grand-père aussi.
De te voir jouer, de continuer mes leçons de piano, ou toute autre chose impossible à prévoir...
Qu\'en penses-tu ? Est-ce que l\'idée te plaît ?
Au départ tu souhaitais venir.  Mais si c\'est compliqué, je peux venir aussi ! ça nous ferait du bien. On aurait plein de choses à se raconter... :)']]; ?>