<?php 
return [1=>['lylie','1/ Ayant le bonheur d\'opérer dans différents domaines sans liens entre eux, je peux vous affirmer le cercle zététique opère dans tous les secteurs, partout où se définit \"la réalité\", dans le but de stériliser par anticipation toutes les voies de recherches et de réflexion qui peuvent conduire à s\'éloigner du dogme.
Poussés dans leurs retranchements, l\'argument ultime qu\'ils donneront sera de ne pas prendre le risque de passer pour un imbécile, à vouloir fonder ses réflexions sur des choses qui sont opportunément jugées fausses, du moins, sur le plan de la logique classique, la seule qui soit acceptée en tant que logique. Cette logique fait abstraction du fait que \"la réalité\" n\'est en fait rien d\'autre qu\'une construction psychologique [déjà, à la base]. En partant de là, rien de fin peut être prouvé. Comment prouveriez-vous que vous êtes triste ? Un zététicien vous dira que vous faites semblant pour attirer l\'attention.
En tous cas je félicite votre approche dépassionnée et rationnelle, qui permet de déconstruire une opinion qui est objectivement dirigée par un besoin préalable de prouver l\'inanité de la curiosité et de l\'intérêt du public pour un syndrome qui, selon moi par contre, est très pertinent pour mieux comprendre le psychisme et surtout pour progresser scientifiquement vers de nouvelles découvertes qui promettent d\'être très pertinentes.
2/ J\'ai découvert votre existence en suivant Olympe, et je suis vraiment surpris étonné et heureux de vous voir contribuer à faire connaître le Tdi alors qu\'il a vraiment été très longtemps occulté par l\'incrédulité. Je serais vraiment très intéressé d\'échanger avec vous sur un certain nombre de caractéristiques du Tdi qui ne me semblent jamais être véritablement abordées sur un plan scientifique.
Merci

Bonjour Lyli je suis Davy je t\'ai découvert hier par hasard, une émission de cauet, sur Fb, j\'ai cherché tes comptes, me suis abonné à peu près partout je crois lol. J\'ai beaucoup regretté de n\'avoir pas pu rencontrer Billy Milligan avant sa mort car je venais seulement de découvrir le Tdi. Je l\'ai découvert après le film Glass, et j\'ai compris que l\'auteur avait voulu faire une \"fusion\" de deux films, Incassable et Split. Après j\'ai compris en quoi l\'auteur de ces trois films avait une excellente compréhension du Tdi, bien qu\'il ait dû complètement rogner tout ce qui fait l\'intérêt de ce phénomène pour le rendre cinématographique. Franchement, convertir le protecteur en un monstre c\'est nier son niveau évolutif qui est très avancé sur le plan moral et éthique. La réalité m\'est apparue bien plus fantastique que la fiction. C\'est cela qui m\'intéresse. Si tu veux, j\'ai le tome 2 introuvable de \"les mille et une guerres de Billy Milligan\" ; le premier, \"les mille et une vies\" étant disponible facilement (que tu connais sûrement), bien que censuré encore aujourd\'hui aux EU, il me semble. Pourquoi censuré ? J\'espère qu\'on pourra en parler. L\'auteur, Daniel Keyes, m\'a énormément inspiré. Son travail, sa droiture, sa clarté, ont permis de retranscrire des informations très pertinentes par à ce que j\'étudie (ça aussi j\'espère pouvoir en parler, pas mal de scientifiques y ont pensé). Depuis j\'ai développé une véritable passion pour, et compréhension profonde de, la Tdi, car j\'y vois, avec d\'autres phénomènes, un progrès considérable à faire dans la compréhension du psychisme. Ta copine Zelliana qui oriente ses études vers ce phénomène entrera peut-être dans l\'histoire si elle va jusqu\'au bout. J\'aurais vraiment mille et une questions à te poser, à toi et à elle, et à tout ce petit monde lol. Mon truc c\'est que je m\'entends avec tout le monde, lol. Enfin sauf les gens qui croient avoir tout compris à l\'univers. Ce que j\'ai compris, et que j\'ai vu, c\'est que tout se passe pour le mieux possible et qu\'il faut s\'en réjouir ! Bien à toi, très affectueusement. Heureux de t\'avoir rencontré. D\'ailleurs je crois que j\'ai sauté de joie lol.

*

Bonjour Lylie,
Vous saluer est un honneur qui m\'émeut un peu.

Je m\'appelle Davy, j\'habite à Paris, et je suis chercheur ingénierie logicielle, principalement.
J\'ai fait votre connaissance récemment, suite à quoi je me suis empressé de faire le tour de vos publications, en étant vivement enthousiasmé à l\'idée d\'enfin pouvoir observer un Tdi (je dis cela pour être sincère, et je ne souhaite pas que vous vous sentiez offensée).
Je suis particulièrement satisfait de vous voir profiter de la vie et de votre liberté, dont la médecine aura privé ceux qui avant vous étaient atteints du même syndrome en suscitant l\'incompréhension et l\'enfermement, conduisant à un renforcement pourtant facile à deviner de la souffrance.

La liberté ! Que n\'ont-ils pas compris ?

Parmi mes nombreuses activités, j\'ai une branche scientifique dont il serait inopportun ici d\'énumérer tous les domaines, mais principalement ça se porte sur la physique, la biologie et la psychologie, et les interconnexions entre ces trois domaines [la logique]. Dans le passé j\'étais publicateur dans le monde de la musique, et j\'ai gardé la fibre journalistique au point d\'être aujourd\'hui dans la presse alternative. Un de mes principaux buts dans la vie en général porte sur la construction d\'un système social dit \"idéal\", et j\'ai publié plusieurs livres sur ce sujet. D\'autres livres portent sur un dernier centre d\'attention, qui est très présent au quotidien pour moi, qui est la vie aliène.

J\'espère que cette présentation ne vous paraîtra pas trop \"folle\" :)
Mon désir est d\'entamer avec vous un échange qui, selon ce que je souhaite et ne peux que souhaiter, sera équitable. Il est certain que ma première impression, et mon principal regret en ayant lu les biographies de Billy Milligan faites par Daniel Keyes, est de ne pas avoir été là à l\'époque pour apporter le soutien que j\'aurais largement pu apporter, du moins à ce qu\'il me semble.

Un des points communs à tous mes travaux est de me situer à un stade où rien n\'est acquit et tout est à découvrir et à comprendre. Et il y a de nombreux aspects des nombreuses sortes de problèmes que je rencontre dans n\'importe quel domaine qui peuvent se résoudre avec des connaissances simples et claires.

L\'intérêt d\'avoir atteint mon âge, je l\'ai remarqué à partir de l\'âge de trente ans que je n\'avais jamais espéré dépasser, est de pouvoir saisir toujours mieux la profondeur et la justesse de ce qui existe tel que cela existe.

Dans le même temps apparaît avec plus de fermeté et de clarté ce qui fait l\'injustice et ce que cette injustice réclame de savoir.

Dans un monde idéal je crois, ce message ne finirait pas à la corbeille d\'un de vos agents de presse et pourrait s\'entamer une discussion fondée sur ce que j\'appelle l\'ordre moral, qui consiste en cette équité dont je vous ai parlée. En tous cas c\'est ce à quoi je travaille, et je présente mes excuses pour les éventuels débordements qu\'il peut y avoir dans ma communication, ou dans le simple fait de vous écrire.

Car ce qui m\'a le plus frappé et stupéfié dans la cohorte de Billy Milligan, est précisément l\'édiction de règles entre les résidents qui procédait de normes éthiques très élevées. Et bien souvent, on pouvait constater l\'ajout de l\'intelligence de chacun pour former des solutions, des idées, des concepts (et même des plans d\'évasion !) qui étaient d\'un très haut niveau d\'intelligence. Comme il le disait, \"la somme vaut plus que les parties\". (L\'expression exacte aurait été \"le total vaut plus que la somme des parties\").

Je reviendrais sur le terme de l\'émergence dans une autre missive, car je crois bien que j\'ai l\'intention de continuer à vous écrire quelques temps, même en l\'absence de réponse. Je ferai mon \"blog de Dav\" en mode perso :)
Vous pourrez le prendre comme une contrepartie de ce que j\'ai déjà obtenu de vous en suivant vos vidéos. Si tant est que cela ait la moindre valeur pour vous.

Ce que je veux dire ici, et ce qui m\'intéresse et me motive pour vous écrire, est qu\'il y a dans l\'émergence de \"la somme des parties\", par sérendipité, quelque chose de \"plus\". Peut-être vous êtes-vous déjà interrogée sur la provenance d\'une information qui ne se situait objectivement pas préalablement dans votre \"cerveau\". Personne n\'a l\'air d\'y prêter attention. Il faut dire que les processus naturels d\'auto-amnésie, le plus souvent consacrés à effacer les rêves, sont là pour protéger d\'une surcomplexité la partie consciente, l\'infime partie de l\'hippocampe qui sélectionne les choix batchés par le cortex préfrontal, qui sont ainsi \"libres\". Cette liberté est le but de l\'univers !

Bien affectueusement,
Un admirateur :)

']]; ?>