<?php 
return [1=>['symétries','1. On ne peut pas dire \"la fusée décolle du fait d\'une symétrie de force\" pour prouver l\'existence d\'une symétrie dont on a constaté l\'existence en observant une fusée décoller : c\'est tautologique.
2. Vous ne parlez pas par exemple d\'anisotropie, or c\'est fondamental, notamment pour ce que vous appelez \"des particules d\'interaction\" : l\'interaction est justement due à une anisotropie.
3. Quand vous ajoutez un facteur additionnel pour vous extraire d\'une contradiction apparente, vous commettez une symétrie. 
4. La symétrie est en effet fondamentale dans l\'univers, tout va toujours par deux. Par exemple tout être vivant a un axe de symétrie.
5. Quand vous observez les constituants internes et encore plus internes de la matière, vous voyez bien une mise en abime. Il ne faut donc pas s\'y attarder, mais revenir à l\'essentiel, l\'anisotropie qui est à l\'origine de cette illusion.
6. Les dimensions s\'ajoutent les unes aux autres par un effet de symétrie. Quand vous ajoutez un facteur externe pour résoudre une contradiction entre deux résultats qui relèvent de deux référentiels, vous ajoutez une dimension. Pour illustrer ceci, il faut revenir aux fondamentaux. 
7. Dès que vous parlez de \"ligne droite\", ceci n\'est qu\'une illusion de l\'esprit. Il n\'existe pas de ligne droite dans l\'univers. L\'objet lancé dans l\'espace suit effectivement une courbe qui signifie sa plus faible dépense en énergie. C\'est cela \"sa\" ligne droite mais ce n\'est pas une ligne \"droite\".
8. Un exemple éclairant : deux lignes sont parallèles quand elles ne se coupent pas, mais ceci, encore, est faux. Si elles sont tracées sur une sphère deux lignes droites parallèles se coupent. Il se passe ici la même chose que lorsque vous ajoutez un paramètre : on ajoute une dimension (de 2d à 3d). Et dans ce cas il en résulte que les deux lignes parallèles obtiennent, ou voient se révéler, une nouvelle propriété, qui est de pouvoir se croiser. Ces propriétés étaient déjà là mais elles n\'étaient pas visibles depuis la perspective 2d. En ajoutant une dimension on révèle de nouvelles propriétés. Mais la réalité reste la même.
9. Il en va de même avec les lois de l\'univers : celles que nous observons ne sont que des descriptions faites en l\'absence d\'une dimension ultérieure qui permet d\'expliquer plus simplement ce qui est observé. 
10. Je trouve qu\'ajouter des vecteurs de forces pour suivre l\'avion depuis le référentiel de la montagne est un exemple percutant de ce qu\'il ne faut vraiment surtout pas faire. Au contraire, le trop-plein de complications a tendance à prouver qu\'on fait fausse route. Les référentiels doivent être appropriés à ce qui et observé, ils sont relatifs. Vous n\'aurez jamais de loi absolue telle que vous l\'espérez, puisque cela engendre une complexification infinie qui crée une mise en abime.
11. L\'introduction du concept d\'anisotropie ou de rupture de symétrie permet d\'expliquer les interactions entre des événements qui appartiennent à des référentiels distincts.
12. L\'énergie n\'est qu\'un sous-produit de la masse, qui est en cours de conversion en espace. C\'est le temps qui produit la masse.
13. Ce qui définit une ligne droite est qu\'elle est la projection de quelque chose d\'inconnu dans la dimension dans laquelle on l\'observe. Ce quelque chose d\'inconnu peut s\'exprimer par un nombre qui s\'incrémente. L\'algorithme appliqué à ce nombre permet de recréer une ligne droite, comme par exemple l\'application d\'une parabole à un point arbitraire, à partir duquel on projette les points d\'une ligne qui semble droite. On peut ainsi projeter cette idée de la ligne droite sur d\'autres dimensions sans problème, en sachant qu\'il s\'agira de la même réalité, même si elle prend des formes différentes selon les référentiels.
14. Le fait qu\'existent des formes différentes d\'une même réalité permet de s\'extraire de l\'obligation de vouloir trouver des lois qui expliquent le changement apparent de trajectoire de la boule sur un tourne-disque.  

https://www.youtube.com/watch?v=PqZyHgm6o-c']]; ?>