<?php 
return [1=>['','[Le clivage qui s\'installe dans la société française depuis un an n\'est pas qu\'une question de politique et de vision de l\'avenir, mais révèle deux conceptions de la vie de l\'homme, dont la divergence impose désormais un choix.:b]

Liberté, Égalité, Fraternité ?

N\'y a-t-il plus d\'intelligence dans ce pays, n\'y a-t-il plus de bon sens ? L\'épuisement spirituel de la population et le matérialisme forcené inculqué depuis l\'après-guerre ont-ils conduit la population française à son point de non retour... ou son point de rupture ? Y a-t-il encore la place pour un sursaut salvateur ou bien la peur et la servilité l\'ont-elles emporté ?

L\'état d\'esprit des Français laisse apparaître que désormais plusieurs réalités se côtoient dans notre pays, selon le niveau d\'information et la conscience de chacun, divisant et brouillant la société, les familles, les amis...

Entre ceux qui ont plus ou moins calqué leur opinion sur le narratif uniforme matraqué par les radios et les télévisions et ceux qui ne leur accordent plus la moindre confiance et ont cherché la vérité ailleurs, la société française, jusqu\'au c&oelig;ur des familles, parfois des couples, s\'est divisée à l\'ombre d\'un minuscule virus.

Un clivage qui semble s\'étendre chaque jour un peu plus, dressant les uns contre les autres et profitant à ceux qui concentrent toujours plus de pouvoir et d\'argent, comme le montrent l\'inexistence politique du Parlement, les salaires croissants des élus et les comptes en banques des GAFA et de Big Pharma durant cette année de misère grandissante du peuple, particulièrement des jeunes et des étudiants condamnés à la soupe populaire.

La détresse de la jeunesse est très préoccupante. Jusqu\'à quand des parents vont-ils continuer à envoyer leurs enfants dans des écoles démentes où [https://enfance-libertes.fr/ecoles-un-systeme-de-jetons-pour-respirer|trois jetons] leur sont donnés par des fonctionnaires zélés pour choisir entre respirer ou pisser ? D\'où les enfants bâillonnés sortent parfois avec des [file:///C:/Users/ha/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/JV436OVY/<iframe id=\"lbry-iframe\" width=\"560\" height=\"315\" src=\"https:/odysee.com/$/embed/La-video-qu\'il-ne-fallait-pas-poster-sur-Youtube-!-Conséquence---2ème-avertissement-et-14-jours-d\'interdiction-de-publication/bda76f89434dba4b91fd4d3869e5a0a3683d9826?r=5u5aNNDgb6gwjXbsDYn35sgim1Toduvv\" allowfullscreen></iframe>|saturations en oxygène] autour de 83 %, soit un état d\'hypoxie sévère, là où l\'on doit s\'inquiéter des [https://santeconnexion.com/content/18-la-saturation-en-oxygene|conséquences] sous les 95 % ?

Les artisans, les entrepreneurs vont-ils continuer à se laisser mourir parce que ce sont les ordres ? La peur du gendarme et de l\'amende a-t-elle plus de force que l\'instinct de survie pour eux et leurs familles ? Est-ce que quelqu\'un a encore un peu de lucidité et de courage dans ce pays ?

Tout le monde va-t-il continuer à croire qu\'il y a une pandémie qui justifie cette folie, alors que les [https://www.francesoir.fr/opinions-tribunes/les-lendemains-dune-lettre-ouverte-ouverte-qui-fait-du-bruit|chiffres de l\'INSEE] démontrent qu\'il n\'y a pas plus de morts en France en 2020 que les années précédentes ? Et comme l\'a [file:///C:/Users/ha/AppData/Local/Microsoft/Windows/INetCache/Content.Outlook/JV436OVY/<iframe width=\"560\" height=\"315\" src=\"https:/www.youtube.com/embed/2tDFRh3bVTc\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>|précisé depuis le Pr Raoult], qu\'il y en a moins en 2020 chez les moins de 65 ans qu\'en 2019 ?

Le taux de mortalité du COVID tous âges confondus est de 0,05 % environ, c\'est un fait. Alors s\'il n\'y a pas de vraie raison sanitaire à la dictature qui s\'installe, n\'est-il pas temps de s\'interroger sur les véritables motivations d\'une telle opération et sur les objectifs réels du contrôle et de l\'asservissement des populations ?

C\'est perdre son temps et rajouter à la confusion que de tenter de chercher des explications logiques à une politique volontairement incohérente. Il est tout aussi inutile de se perdre en conjectures sur l\'incompétence des uns et les revirements des autres. Tout ceci est inspiré des techniques de manipulation mentale bien connues (voir [https://archive.org/details/KubarkLeManuelSecretDeManipulationMentale|le manuel Kubark] déclassifié par la CIA).

[philum_465_17c117.jpg]

Alors combien de temps encore soumis et insoumis vont-ils se focaliser sur les ombres de la caverne de Platon ?

Toutes ces mesures à l\'encontre de la vie ont raturé une France faite de défaillances d\'entreprises et par effet domino de leurs sous-traitants, de files de jeunes sans espoir d\'avenir devant l\'aide alimentaire, de taux de suicides alarmants, d\'une séparation physique des gens jusque dans les familles, de couvre-feux absurdes ne reposant sur aucun argument censé, de masques dangereux pour la santé, comme vient encore de le démontrer [https://www.researchsquare.com/article/rs-124394/v1|un rapport allemand] sur la santé des enfants, ainsi que de confinements à répétition dont on sait a minima désormais [https://covidinfos.net/experts/confinement-aucune-vie-na-ete-sauvee-par-cette-strategie-revele-une-nouvelle-etude-internationale/723|l\'inefficacité sanitaire].

Les Français trop crédules vont-ils chercher plus d\'ivresse encore à boire les mensonges éhontés d\'une presse collaborant à des intérêts partisans qu\'ils dissimulent ? Les démonstrations ne manquent pourtant pas de l\'arrogance et du mépris des castes influentes vis à vis du bas-peuple, des sans-dents, des gilets jaunes. [Cette question de la croyance en la bienveillance ou la malveillance au pouvoir est cruciale. Elle est l\'une des clés du sursaut possible en chacun, le coup d\'arrêt fatal à la naïveté.:b]

Il est convenu désormais que lorsqu\'on évoque les coulisses de ces forces qui ont pris pouvoir sur la vie de chacun, on soit alors immédiatement traité de complotiste délirant, voire dangereux. Sans doute les présidents Eisenhower et Kennedy étaient-ils aussi des complotistes délirants. Car qui connaît le [bah8-Oy45mw|discours d\'Eisenhower:video] du 17 janvier 1961 lorsqu\'il a quitté le pouvoir ? En voici un extrait particulièrement d\'actualité :

[« Dans les assemblées du gouvernement, nous devons donc nous garder de toute influence injustifiée, qu\'elle ait ou non été sollicitée, exercée par le complexe militaro-industriel. [Le risque d\'une désastreuse ascension d\'un pouvoir illégitime existe et persistera:b]. Nous ne devons jamais laisser le poids de cette combinaison mettre en danger nos libertés et nos processus démocratiques. Nous ne devrions jamais rien prendre pour argent comptant. [Seule une communauté de citoyens prompts à la réaction et bien informés pourra imposer un véritable entrelacement de l\'énorme machinerie industrielle et militaire de la défense:b] avec nos méthodes et nos buts pacifiques, de telle sorte que sécurité et liberté puissent prospérer ensemble. »:q]

Car qui connaît le [f8eKtdz59Vw|discours de J.F. Kennedy:video] à New York le 27 avril 1961, qui demandait en vain son aide à la presse et dont voici un extrait :

[« ... [Car nous sommes confrontés, dans le monde entier, à une conspiration monolithique et impitoyable qui compte principalement sur des moyens secrets pour étendre sa sphère d\'influence par l\'infiltration plutôt que l\'invasion:b], la subversion plutôt que les élections et l\'intimidation au lieu du libre arbitre. C\'est un système qui a nécessité énormément de ressources humaines et matérielles dans la construction d\'une machine étroitement soudée et d\'une efficacité remarquable, [elle combine des opérations militaires, diplomatiques, de renseignements, économiques, scientifiques et politiques. Leurs ramifications sont occultées et non publiées.:b] Ses erreurs sont enterrées et ne font pas les gros titres, on fait taire ses dissidents, on ne les glorifie pas; aucune dépense n\'est mise en question, aucune rumeur n\'est imprimée, aucun secret n\'est révélé. Elle conduit la guerre froide, en bref, avec une discipline de guerre qu\'aucune démocratie n\'espérerait jamais vouloir égaler... C\'est pourquoi le législateur athénien décréta comme criminel tout citoyen se désintéressant du débat... Je sollicite votre aide dans l\'immense tâche qui est d\'informer et d\'alerter le peuple américain avec la certitude qu\'avec votre aide l\'homme deviendra ce pour quoi il est né libre et indépendant. »:q]

Je ne sais pour ma part quel dysfonctionnement peut expliquer qu\'il y a tant de gens éduqués, pour croire ce qu\'on leur dit sans rien remettre en question. Sans doute faut-il y deviner les barrières d\'une programmation de souche auxquelles se greffent le carcan de leur éducation et parfois leur simple intérêt cupide. Il se confirme que l\'essentiel du bon sens et de la réaction à ce qui se joue vient des couches sociales les moins éduquées, les moins formatées peut-être, alors que le modèle de la dystopie hante nombre des plus diplômés. De quoi se faire traiter de populiste en plus de complotiste.

Car est jusque-là populiste celui qui aime le peuple, lui reconnaît sa légitimité et son bon sens culturel, issu d\'une longue histoire de celles qui forge et nourrit l\'esprit d\'une nation. Car est désormais complotiste ou conspirationniste celui qui se pose des questions et cherche la vérité au lieu d\'accepter la ligne officielle qui révèle les apprentis dictateurs.

Les seuls vrais conspirateurs sont ceux qui conspirent contre les peuples. Et ils accusent ceux qui les dévoilent d\'être ce qu\'ils sont eux-mêmes, c\'est une technique aussi vieille que l\'homme.

La responsabilité de la presse aujourd\'hui dans ce mécanisme de manipulation des masses est majeure. Elle est impardonnable et lorsque cette folie sera brutalement interrompue, car je crois qu\'elle le sera, la presse telle qu\'on l\'a connue ne s\'en relèvera pas. Elle disparaîtra au profit d\'une presse plus citoyenne et seront confrontés à leurs responsabilités ceux qui ont fait ce qu\'elle est devenue.

Certains ont fait le pari de se ranger du côté des puissants pour assurer leur intérêt personnel mais n\'ont pas compris l\'éphémérité du pouvoir, ni ne saisissent l\'impermanence des cycles de l\'histoire. Ils n\'ont pas mieux perçu l\'aspect eschatologique de ce que vit la planète en ce moment, ils n\'ont pas la vision globale de ce qui se joue parce qu\'ils sont ignorants de l\'aspect spirituel de cette guerre déclarée à l\'humanité. Ils n\'en mesurent pas les finalités profondes et s\'arrêtent à la seule perception de leur logique et de leur expérience matérialiste. Ils demeurent insensibles aux aspects plus élevés auxquels les appelle plus que jamais leur condition humaine.

Ils ont vécu dans un monde qu\'ils croient inusable dans son fonctionnement, n\'ayant croyance que de ce qu\'ils ont appris d\'un passé si bref et d\'une éducation biaisée. Leur conscience se limite pour le moment à ce contexte et ils n\'entendent pas encore son appel à l\'ouverture et à l\'expansion.

[Dans ce monde d\'imposture où sont adulés et portés au pinacle les indignes et où sont diffamés et persécutés les justes, toutes les valeurs sont inversées.:b] On peut raisonnablement voir le combat planétaire actuel comme une formidable opportunité d\'étendre sa conscience et reprendre individuellement et collectivement sa souveraineté en tant qu\'être vivant, égal à tout être vivant, et non assujetti par force ou par délégation à des pouvoirs iniques et profondément corrompus.

[Le nouveau clivage ne se résume pas seulement à mon sens au mondialisme contre le souverainisme, mais avant tout au matérialisme contre le spiritualisme:b], ce qui, je le précise, ne signifie pas le religieux, mais la reconnaissance pour ce qu\'elle est de la dimension spirituelle de l\'être, qui est un sentiment partagé par une majorité d\'hommes peuplant ce monde.

Comme le disait le philosophe théologien Pierre Theillard de Chardin : « Nous ne sommes pas des êtres humains vivant une expérience spirituelle mais des êtres spirituels vivant une expérience humaine ». C\'est je crois cette dimension de l\'homme qui est appelée à s\'éveiller comme jamais en ces jours, qui pourraient aussi devenir les plus sombres si cette lumière ne jaillit pas en chacun.

Je suis de ceux qui mesurent la vraie richesse de l\'humanité à la reconnaissance et au partage généreux et bienveillant de ses différences, certainement pas à leur castration dans une soupe mondialiste uniforme et insipide. Je crois en une humanité extraordinairement diverse et créative et pour autant unie dans un schéma plus grand que la somme de ses parties. C\'est ce qu\'il lui appartient désormais de cultiver sous tous ses climats et toutes ses particularités culturelles et ethniques, dans le respect et la conscience au sens large du Vivant.

Cela pointe la polarité opposée au monde ultra-matérialiste promu par les transhumanistes rêvant de fondre la machine et l\'homme dans une vision démente de sa transcendance. Le danger n\'a jamais été aussi grand de voir s\'accomplir cette folie par la dictature mondiale qui se répand depuis un an dans le déni de trop de gens encore. Et c\'est pourquoi dans cette phase la polarisation ne fait que croître.

Je suis intimement convaincu que c\'est là le véritable enjeu de tout ce qui se joue en ce moment. [Que cette crise sans précédent dans notre histoire est l\'opportunité unique et brève de décider le monde que nous choisissons désormais, pas celui que nous subissons par peur, résignation ou sentiment d\'impuissance depuis trop longtemps.:b] Nous sommes les puissants, tous ensemble.

C\'est cette conscience de la force d\'un peuple uni dans sa quête de liberté, d\'égalité et de fraternité qui effraie les injustes. C\'est ce qu\'ils s\'acharnent à étouffer dans la confusion, la censure et la répression.

Que ce prétexte du COVID ne serve pas que le camp des censeurs ultra-matérialistes, mais qu\'il serve avant tout celui de ceux qui souhaitent la conscience avant la science.

Sans doute est-il enfin temps de se souvenir de qui nous sommes. Et de reprendre les rênes de nos destinées et de notre condition au sein du creuset alchimique de nos vies, à la lumière d\'une dimension de nous-mêmes plus vaste que ce qui nous a jusque-là limités.

[Le jeu planétaire aujourd\'hui peut se voir comme le temps de la moisson de nos expériences. Et il n\'est pas trop tard pour en décider la richesse:b]. Même sur le tard, toute conscience qui s\'éveille et se tourne vers sa souveraineté est un diamant dans l\'escarcelle de l\'humanité.

Nous et nos enfants serons riches ou pauvres demain de ce que nous avons décidé aujourd\'hui. C\'est notre choix.

[http://www.francesoir.fr/opinions-tribunes/il-est-temps-de-se-souvenir-de-qui-nous-sommes]']]; ?>