<?php 
return ['_'=>['button','type','process','param','option','condition','root','icon','hide','private'],
1=>['close','ajax','desktop','','','desk','','close','',''],
2=>['Desktop','ajax','page','deskload','','desk menu','','desktop','',''],
3=>['Root','ajax','desktop','desk___desk','','boot menu','','folder2','',''],
4=>['Root Folder','ajax','popup','desktop___desk','','boot menu','','folder2','1','1'],
5=>['Site','ajax','popup','site___desktop_ok__autosize','','menu','','window','','1'],
6=>['Home','ajax','page','deskoff___module_Home','','desk menu','','home','',''],
7=>['Articles virtuels','mod','desktop_varts','cache','','desk','Articles','virtual','',''],
8=>['Articles','mod','desktop_arts','cat=public|pub~nbdays=30','','desk','Articles','virtual','',''],
9=>['recents','mod','recents','public','/icons/','desk','Articles','virtual','',''],
10=>['article','art','auto','418','','desk','','articles','1',''],
11=>['Fichiers','mod','desktop_files','local|virtual','//dev|img','desk','','folder2','',''],
12=>['New art','ajax','popup','addArt____1','','desk','','add','1','1'],
13=>['Finder','finder','','','shared/local//flap///mini_1 ','menu desk','','network','',''],
14=>['recherche','ajax','popup','search__3','','desk','','search','','']]; ?>