<?php 
return ['_'=>['button','type','process','param','option','condition','root','icon','hide','private'],
1=>['Accueil','link','','/module/Home','','','','home','',''],
2=>['cache','ajax','ajax','rebuild__3xx','','','boot/reset','loading','','4'],
3=>['mini','link','','/?rebuild_img==','','','boot/reset','loading','','4'],
4=>['login','ajax','popup','loged______1','','','boot','logout','',''],
5=>['reload','link','','/reload','','','boot','reload','',''],
6=>['reboot','link','','/reboot','','','boot','reload','','1'],
7=>['logout','link','','/logout','','','boot','logout','','1'],
8=>['logoff','link','','/logoff','','','boot','logout','','1'],
9=>['shutdown','link','','/shutdown','','','boot','no','','4'],
10=>['tablet','js','android_ui();','','','','utils','gsm','1',''],
11=>['tablet','ajax','socket','plugin__self_tablet','','','utils','gsm','',''],
12=>['favs','plug','favs','','','','','like','1',''],
13=>['dev','link','','/dev','','','','phi','','6'],
14=>['publish','linkt','','/plug/publish_site.php?copy==','','','','txt','1','7'],
15=>['philum','ajax','popup','about','','','','phi2','','']]; ?>