<?php 
return ['_'=>['button','type','process','param','option','condition','root','icon','hide','private'],
1=>['plugin','plug','plug','','','desk menu','plug','peak','',''],
2=>['exec','plug','exec','','','menu','dev','edit','','7'],
3=>['code','plug','code','','','menu','dev','edit','','7'],
4=>['codev','plug','codev','','','menu','dev','edit','','7'],
5=>['dev','plug','dev','','','menu','dev','edit','','7'],
6=>['test','plug','test','','','menu','test','edit','','7'],
7=>['test-edit','ajax','popup','plupin__3_codev_plug_test','','menu','test','conn','','7'],
8=>['rstr','ajax','popup','admin__3_restrictions','','menu','favs','valid','','7'],
9=>['sys','ajax','popup','admin__3_console','','menu','favs','admin','','7'],
10=>['apps','ajax','popup','call___adminx_submod*pop','','menu','favs','apps','','7'],
11=>['msqadd','plug','msqadd','msqadd_1','','menu','plug','right','','6'],
12=>['philumsize','plug','philumsize','','','menu','plug','phi','','6'],
13=>['coreflush','plug','coreflush','','','menu','plug','phi','','7'],
14=>['_erase','linkt','','/plugin/_erase.php?dir=&del=','','menu','plug','phi','','7']]; ?>