<?php 
return ['_'=>['button','type','process','param','option','condition','root','icon','hide','private'],
1=>['home','link','','/home','','','','home','',''],
2=>['cache','ajax','popup','rebuild__3xx','','','boot/reset','loading','','4'],
3=>['mini','link','','/?rebuild_img==','','','boot/reset','loading','','4'],
4=>['login','ajax','popup','loged______1','','','boot','logout','',''],
5=>['reload','link','','/reload','','','boot','reload','',''],
6=>['reboot','link','','/reboot','','','boot','reload','','1'],
7=>['logout','link','','/logout','','','boot','logout','','1'],
8=>['logoff','link','','/logoff','','','boot','logout','','1'],
9=>['shutdown','link','','/shutdown','','','boot','no','','4'],
10=>['hubs','bub','','hubs','','','hubs','folder2','',''],
11=>['desktop','js','SaveJc','page_deskload;desk;popup_site___desktop_ok__autosize','','','utils','desktop','',''],
12=>['android','ajax','socket','tog__self_tablet','','','utils','gsm','',''],
13=>['b/w','ajax','socket','tog__self_negcss','','','utils','view','',''],
14=>['mod 2','ajax','socket','slctmod__self_2','','','utils','view','1',''],
15=>['favs','plug','favs','','','','','like','1',''],
16=>['dev','link','','/dev','','','utils','phi','','6'],
17=>['publish','linkt','blank','/plug/publish_site','','','utils','export','','7'],
18=>['philum','ajax','popup','about','','','','phi2','','']]; ?>