<?php 
return ['_'=>['date','text'],
1=>['0901','publication'],
2=>['0901','- correctif friend_rub pour qu\'il prenne en compte les articles _systemrn- correctif id_of_urlsuj(), qui, sans condition, permet à sql de s\'arrêter sur l\'occurrence la plus pertinente'],
3=>['0902','- le connecteur :track renvoie le contenu plutôt qu\'un bouton vers popup, du commentaire prit en référencern- sconn prend en compte les connecteurs list, html, font, size, color, cssrn- refonte du connecteur :web, renvoie une preview de la page linkée, titre, image et description qui sont présents dans l\'espace de nommage ob: des méta'],
4=>['0903','- amélioration du traitement (rendu récursif) du connecteur :track, pour lire les commentaires pris en référencern- le bouton du connecteur vidéo convertit directement la sélection sans passer par le formulaire'],
5=>['0904','- correctif pour que les tags ne soient plus sensibles au champ temporelrn- correctif lien des titres du gestionnaire des titres'],
6=>['0907','- correctif login mobilern- correctif sécurité accès à la console'],
7=>['0909','- ajout du plugin genpswd, génère un mot de passe naturel avec accents et nombresrn- ajout du plug md5'],
8=>['0910','- fix pb liens à variables dans l\'interprétateur (depuis le fix précédent)rn- correctif à l\'essai du non-traitement des sauts de lignes dans du code html (chose non interdite quoi que exceptionnelle)'],
9=>['0912','- fix pb nl2br dans tracksrn- rénove détect philum defs dans importrn- réduit qté méta, rstr74=espaces de noms ob, sinon metas normauxrn- nettoie ajxrn- todo retarder titres SaveIrn- oubli remise en marche cache boutons d\'éditeur'],
10=>['0913','- améliore gestion des notes de glossairesrn- ajout de prop_detect()rn- améliore gestionnaire admin de consultation rapide des articles'],
11=>['0916','- répercussion des icônes des utags dans l\'éditeurrn- requalification du defcon4 de nobr (obsolète) vers détection de footerrn- ajout d\'un nouveau membre vidéo : vk.com (reste inusité)'],
12=>['0917','- ajout du paramètre 12 de modules : jsrnpermet de lancer le module via javascript, après le lancement de la pagern- amélioration gestionnaire de modules de sorte à supporter le nouveau dispositif à retardateur : rendu responsable des requires'],
13=>['0920','- fix pb controls lecteur mp4 html5'],
14=>['0925','- réforme de l\'outil de tags, ajout de la suppression']]; ?>