<?php 
return ['_'=>['category','name'],
'1'=>['access','htaccess'],
'2'=>['access','create_hub'],
'3'=>['access','first_node'],
'4'=>['access','sub_domain'],
'5'=>['server','update server'],
'6'=>['options','gdf_ability'],
'7'=>['options','google-site-verification'],
'8'=>['options','time_zone'],
'9'=>['options','error_reporting'],
'10'=>['server','srvim limit'],
'11'=>['options','utf8'],
'12'=>['access','upload'],
'13'=>['server','updates'],
'14'=>['server','server mirror'],
'15'=>['server','server img'],
'16'=>['server','fractal']]; ?>