<?php 
return [1=>['','','body','7|7','1','','font-family:Arial, Verdana, sans-serif; font-size:12px; border:0; margin:0; padding:0 10px;'],
2=>['','','@font-face','','','','font-family: \'Banda_regular\'; src: url(\'/fonts/Banda_regular-webfont.eot?iefix\') format(\'eot\'), url(\'/fonts/Banda_regular-webfont.woff\') format(\'woff\'), url(\'/fonts/Banda_regular-webfont.svg#webfont\') format(\'svg\');'],
3=>['','','@font-face','','','','font-family: \'Anivers_Regular\'; src: url(\'/fonts/Anivers_Regular-webfont.eot?iefix\') format(\'eot\'), url(\'/fonts/Anivers_Regular-webfont.woff\') format(\'woff\'), url(\'/fonts/Anivers_Regular-webfont.svg#webfont\') format(\'svg\');'],
4=>['','','a','','','','cursor:pointer; text-decoration:none;'],
5=>['','','h1','','','','font-family:Impact, Arial Black; font-size:24px; margin:0; padding:0px;'],
6=>['','','h2','7|7|5','||','4||','font-family:MemphisLTStdBold; font-size:20px; margin:4px 0; padding:0; text-shadow:1px 1px 2px #999999;'],
7=>['','','h3','8','','','font-family:Geneva, Arial, Helvetica, sans-serif; font-variant:small-caps; margin:0;'],
8=>['','','h4','5','','4','font-size:14px; margin:0;'],
9=>['','','td','','','4','border:0px; padding:2px;'],
10=>['','','table','','','4','font-size:11px; margin:0px;'],
11=>['','','blockquote','','','4','font-size:13px; width:75%; margin:0; padding:4px 0; line-height:15px; border-width:1px; border-style:solid; border-width:1px 0;'],
12=>['','','img','','','','border:0px;'],
13=>['','','hr','','','4',''],
14=>['','','ul','','','','list-style-position:inside; margin:0; padding:0;'],
15=>['','','ol','','','','list-style-position:inside; margin:0; padding:0;'],
16=>['','','li','','','',''],
17=>['','','input','7','6','4','border-width:1px; border-style:solid; margin:0px; -moz-border-radius:7px; margin:4px 0;'],
18=>['','','textarea','7','6','4','border-width:1px; border-style:solid; margin:1px solid; -moz-border-radius:2px;'],
19=>['','','select','7','6','4','padding:0px;'],
20=>['','','submit','7','6','4',''],
21=>['','','form','','','','padding:0px; margin:0px;'],
22=>['banner','','','||','2||','||','margin-bottom:10px; -moz-border-radius:7px; padding:10px;'],
23=>['page','','','||','3||','4||','text-align:left; margin:10px auto; width:850px; padding:10px; border-width:1px; border-style:solid; -moz-border-radius:7px;'],
24=>['leftbar','','','|7|5','','','float:left; width:200px;'],
25=>['rightbar','','','|7|5','||','4||','float:right; width:0px; '],
26=>['menu','','','7|7|7','||','||','font-family:Verdana; font-size:13px; line-height:30px; font-weight:bold; padding:0 0 10px 0;; font-variant:small-caps; border-width:0 0 0px 0;'],
27=>['menu','','li','||','||','||','display:inline;'],
28=>['menu','','li a','||','2||','2||','padding:4px 10px; border-width:1px; border-style:solid; -moz-border-radius:7px; text-shadow:2px 2px 4px #999999;'],
29=>['menu','','li a:hover','||','||','7||',''],
30=>['menu','active','','5|5|7','||','||','//border-bottom:1px solid black;'],
31=>['content','','','||','3||','4||','float:left; left:200px; right:0px; width:639px; margin:0 0 0 10px; padding:10px 0 0 0; border-width:0; border-style:solid;'],
32=>['footer','','','7|7|5','||','||','clear:both; margin-top:5px; text-align:center;'],
33=>['','tab','','||','||','2||','font-family:Verdana; margin-bottom:20px;'],
34=>['','tabb','','7|7|5','||','5||','font-family:Arial; font-size:11px; margin-bottom:20px; border-width:1px; border-style:solid;'],
35=>['','tabc','','7|7|5','||','2||','font-size:12px; margin-bottom:20px; opacity:0.5;'],
36=>['','panel','','8||','2||','||','font-family:Georgia; font-size:13px; padding:4px 3px; -moz-border-radius:0 0 4px 4px;'],
37=>['menu','panel','li','','','','display:block; font-variant:normal; font-weight:normal;; font-family:Verdana;'],
38=>['menu','panel','li a:hover','','','','border:0;'],
39=>['','','ul.panel','','','','padding:4px; /*0px*/ border:0;'],
40=>['','','ul.panel li','','','','list-style-type:none; font-size:12px; padding:0; margin:2px 0; '],
41=>['','','ul.panel li a','||','||6','||','display:block; padding:4px ; -moz-border-radius:4px;'],
42=>['','','ul.pubart li','','','','margin-bottom:0px; '],
43=>['','pubart_img','','','','','min-height:45px;'],
44=>['','active','','5','','',''],
45=>['','','li.active','||','||','||',''],
46=>['','justy','','7||','2||','6||','font-family:Georgia; font-size:16px; text-align:left; padding:4px 4px 10px 4px; border-width:0; border-style:solid; background-repeat:none; /*background-image:url(/bkg/_mbr/_mbr2.png);*/'],
47=>['','justy','a','5','','','text-decoration:underline;'],
48=>['','justy','img','||','||','7||','border-width:0px; border-style:solid;'],
49=>['','txtot','','5','','','font-family:impact; font-size:20px; margin-left:4px;'],
50=>['','txtit','','8','','','font-family:Georgia; font-size:16px; font-variant:small-caps; font-weight:bold; padding:4px;'],
51=>['','txtcadr','','||5','||','4||','font-weight:bold; font-variant:small-caps; line-height:16px; padding:0; border-width:0 0 1px 0; border-style:solid;'],
52=>['','txtblc, .txtnoir, .txtred, .txtx, .txtyl','','','','','font-family:Arial, Helvetica, sans-serif; font-size:11px; margin:0px; padding:1px 3px 0px 4px; letter-spacing:1px; line-height:18px; border-width:0 0 1px 0; border-style:solid; -moz-border-radius:4px;'],
53=>['','txtx','','8|8|5','||','4|4|5',''],
54=>['','txtblc','','7|7|7','','',''],
55=>['','txtred','','|5|8','1','|5|5','border-color:red;'],
56=>['','txtnoir','','|6|6','7','|6|6','background:black; color:white;'],
57=>['','txtclr','','','','','color:red; font-weight:bold;'],
58=>['','txtyl','','7|7|1','','||1','background:red;'],
59=>['','txtalert','','5','','','border:medium double red; padding:4px;'],
60=>['','txtsmall','','5|7|7','||','6||','font-family:Arial; font-size:10px; padding:0px 1px; border-width: 1px 0 0 0;'],
61=>['','txtsmall2','','8|7|7','','','font-family:Arial; font-size:9px; padding:0px 1px;'],
62=>['','txtbox','','8|8|8','1|1|6','4||','font-size:11px;

padding:0 5px;

border-width:1px;

border-style:solid;

-moz-border-radius:7px;'],
63=>['','rss','','6|6|7','||','','font-size:8px; color:white;

border:1px solid black;

background:#FF6600;

letter-spacing:1px;

font-weight:bold;

padding:2px 3px 1px 3px;'],
64=>['','stabilo','','7||','4||','||',''],
65=>['','htab','','','','','float:left; width:48%; margin:0px 7px 0px 0; align:center;'],
66=>['','htab3','','','','','float:left; width:32%; margin:0px 7px 10px 0; align:center;'],
67=>['scroll','','','||','||','||','overflow:auto; height:400px;'],
68=>['board','','','||','||','4||','float:left; list-style-type:none; padding:4px; border-width:1px; border-style:solid; -moz-border-radius:7px;'],
69=>['board','','li','','','',''],
70=>['','taxonomy','li','|7|5','||','||','list-style-type:auto; padding:0 16px;'],
71=>['','imgl','','','','','float:left; margin:2px 4px 0px 0px;'],
72=>['','imgr','','','','','float:right; margin:2px 0px 0px 4px;'],
73=>['','clear','','','','','clear:left;'],
74=>['','console','','||','||','||','font-family:Courier New; font-weight:bold; line-height:18px; font-size:15px; color:#00ff00; background:black; border:4px double white; margin:10px; padding:10px;'],
75=>['line','','','8','','','margin:0px; padding:0px; text-align:center; font-family:Impact; font-size:10px; font-weight:lighter;'],
76=>['','lina','','','','','float:left; width:16px; color:#bbbbbb;'],
77=>['','linc','','8','','','float:left; width:16px;'],
78=>['','nb_pages','','','','','line-height:18px;'],
79=>['','nb_pages','a','','','4','padding:0 4px; border-style:solid; border-width:1px; -moz-border-radius:4px;'],
80=>['menuH','','','','','','width:100%; margin-top:0px; margin-bottom:10px; background:none; /*height:22px;*/'],
81=>['menuH','','a','','','','text-decoration: none; text-transform: capitalize; font-size: 1.1em; line-height:22px; padding:0 10px;'],
82=>['menuH','','ul','||','2||','||',''],
83=>['menuH','','li','7|7|5','2||','||','font-size:12px; width:auto;'],
84=>['menuH','','li a:hover','||','||','||','border:none;'],
85=>['menuH','','ul li','|7|5','||','||','margin-right:4px; opacity:1;'],
86=>['menuH','','li ul','||6','','','border:0; width:200px; margin: -22px 0 0 200px;'],
87=>['menuH','','li li','','','','border:0; width:200px; line-height:20px;'],
88=>['menuH','','li ul ul','','','','margin: -22px 0 0 200px;'],
89=>['menuH li:hover, #menuH li.sfhover','','','7||','3||','||','/*parents hors-hover*/'],
90=>['menuH li:hover a, #menuH li.sfhover a','','','7','','','/*parents*/'],
91=>['menuH li li:hover a, #menuH li li.sfhover a','','','7','','','/*restantes*/'],
92=>['menuH li li:hover a:hover, #menuH li li.sfhover a:hover','','','5','','','/*hover en cours*/']]; ?>