<?php
//philum_microsql_nmk_design_5

$nmk_design_5["_menus_"]=array('div','class','element','color','background','border','free');
$nmk_design_5["1"]=array('','','body','7|7','1','','font-family:Arial, Verdana, sans-serif; font-size:12px; border:0; margin:0; padding:0 10px;');
$nmk_design_5["2"]=array('','','a','','','','cursor:pointer; text-decoration:none;');
$nmk_design_5["3"]=array('','','h1','','','','font-family:Impact, Arial Black; font-size:24px; margin:0; padding:0px;');
$nmk_design_5["4"]=array('','','h2','7|7|5','||','4||','font-family:MemphisLTStdBold; font-size:20px; margin:4px 0; padding:0; text-shadow:1px 1px 2px #999999;');
$nmk_design_5["5"]=array('','','h3','8','','','font-family:Geneva, Arial, Helvetica, sans-serif; font-variant:small-caps; margin:0;');
$nmk_design_5["6"]=array('','','h4','5','','4','font-size:14px; margin:0;');
$nmk_design_5["7"]=array('','','td','','','4','border:0px; padding:2px;');
$nmk_design_5["8"]=array('','','table','','','4','font-size:11px; margin:0px;');
$nmk_design_5["9"]=array('','','blockquote','','','4','font-size:13px; width:75%; margin:0; padding:4px 0; line-height:15px; border-width:1px; border-style:solid; border-width:1px 0;');
$nmk_design_5["10"]=array('','','img','','','','border:0px;');
$nmk_design_5["11"]=array('','','hr','','','4','');
$nmk_design_5["12"]=array('','','ul','','','','list-style-position:inside; margin:0; padding:0;');
$nmk_design_5["13"]=array('','','ol','','','','list-style-position:inside; margin:0; padding:0;');
$nmk_design_5["14"]=array('','','li','','','','');
$nmk_design_5["15"]=array('','','input','7','6','4','border-width:1px; border-style:solid; margin:0px; -moz-border-radius:7px; margin:4px 0;');
$nmk_design_5["16"]=array('','','textarea','7','6','4','border-width:1px; border-style:solid; margin:1px solid; -moz-border-radius:2px;');
$nmk_design_5["17"]=array('','','select','7','6','4','padding:0px;');
$nmk_design_5["18"]=array('','','submit','7','6','4','');
$nmk_design_5["19"]=array('','','form','','','','padding:0px; margin:0px;');
$nmk_design_5["20"]=array('banner','','','||','2||','||','margin-bottom:10px; -moz-border-radius:7px; padding:10px;');
$nmk_design_5["21"]=array('page','','','||','3||','4||','text-align:left; margin:10px auto; width:850px; padding:10px; border-width:1px; border-style:solid; -moz-border-radius:7px;');
$nmk_design_5["22"]=array('leftbar','','','|7|5','','','float:left; width:200px;');
$nmk_design_5["23"]=array('rightbar','','','|7|5','||','4||','float:right; width:0px; ');
$nmk_design_5["24"]=array('menu','','','7|7|7','||','||','font-family:Verdana; font-size:13px; line-height:30px; font-weight:bold; padding:0 0 10px 0;; font-variant:small-caps; border-width:0 0 0px 0;');
$nmk_design_5["25"]=array('menu','','li','||','||','||','display:inline;');
$nmk_design_5["26"]=array('menu','','li a','||','2||','2||','padding:4px 10px; border-width:1px; border-style:solid; -moz-border-radius:7px; text-shadow:2px 2px 4px #999999;');
$nmk_design_5["27"]=array('menu','','li a:hover','||','||','7||','');
$nmk_design_5["28"]=array('menu','active','','5|5|7','||','||','//border-bottom:1px solid black;');
$nmk_design_5["29"]=array('content','','','||','3||','4||','float:left; left:200px; right:0px; width:639px; margin:0 0 0 10px; padding:10px 0 0 0; border-width:0; border-style:solid;');
$nmk_design_5["30"]=array('footer','','','7|7|5','||','||','clear:both; margin-top:5px; text-align:center;');
$nmk_design_5["31"]=array('','tab','','||','||','2||','font-family:Verdana; margin-bottom:20px;');
$nmk_design_5["32"]=array('','tabb','','7|7|5','||','5||','font-family:Arial; font-size:11px; margin-bottom:20px; border-width:1px; border-style:solid;');
$nmk_design_5["33"]=array('','tabc','','7|7|5','||','2||','font-size:12px; margin-bottom:20px; opacity:0.5;');
$nmk_design_5["34"]=array('','panel','','8||','2||','||','font-family:Georgia; font-size:13px; padding:4px 3px; -moz-border-radius:0 0 4px 4px;');
$nmk_design_5["35"]=array('menu','panel','li','','','','display:block; font-variant:normal; font-weight:normal;; font-family:Verdana;');
$nmk_design_5["36"]=array('menu','panel','li a:hover','','','','border:0;');
$nmk_design_5["37"]=array('','','ul.panel','','','','padding:4px; /*0px*/ border:0;');
$nmk_design_5["38"]=array('','','ul.panel li','','','','list-style-type:none; font-size:12px; padding:0; margin:2px 0; ');
$nmk_design_5["39"]=array('','','ul.panel li a','||','||6','||','display:block; padding:4px ; -moz-border-radius:4px;');
$nmk_design_5["40"]=array('','','ul.pubart li','','','','margin-bottom:0px; ');
$nmk_design_5["41"]=array('','pubart_img','','','','','min-height:45px;');
$nmk_design_5["42"]=array('','active','','5','','','');
$nmk_design_5["43"]=array('','','li.active','||','||','||','');
$nmk_design_5["44"]=array('','justy','','7||','2||','6||','font-family:Georgia; font-size:16px; text-align:left; padding:4px 4px 10px 4px; border-width:0; border-style:solid; background-repeat:none; /*background-image:url(/bkg/_mbr/_mbr2.png);*/');
$nmk_design_5["45"]=array('','justy','a','5','','','text-decoration:underline;');
$nmk_design_5["46"]=array('','justy','img','||','||','7||','border-width:0px; border-style:solid;');
$nmk_design_5["47"]=array('','txtot','','5','','','font-family:impact; font-size:20px; margin-left:4px;');
$nmk_design_5["48"]=array('','txtit','','8','','','font-family:Georgia; font-size:16px; font-variant:small-caps; font-weight:bold; padding:4px;');
$nmk_design_5["49"]=array('','txtcadr','','||5','||','4||','font-weight:bold; font-variant:small-caps; line-height:16px; padding:0; border-width:0 0 1px 0; border-style:solid;');
$nmk_design_5["50"]=array('','txtblc, .txtnoir, .txtred, .txtx, .txtyl','','','','','font-family:Arial, Helvetica, sans-serif; font-size:11px; margin:0px; padding:1px 3px 0px 4px; letter-spacing:1px; line-height:18px; border-width:0 0 1px 0; border-style:solid; -moz-border-radius:4px;');
$nmk_design_5["51"]=array('','txtx','','8|8|5','||','4|4|5','');
$nmk_design_5["52"]=array('','txtblc','','7|7|7','','','');
$nmk_design_5["53"]=array('','txtred','','|5|8','1','|5|5','border-color:red;');
$nmk_design_5["54"]=array('','txtnoir','','|6|6','7','|6|6','background:black; color:white;');
$nmk_design_5["55"]=array('','txtclr','','','','','color:red; font-weight:bold;');
$nmk_design_5["56"]=array('','txtyl','','7|7|1','','||1','background:red;');
$nmk_design_5["57"]=array('','txtalert','','5','','','border:medium double red; padding:4px;');
$nmk_design_5["58"]=array('','txtsmall','','5|7|7','||','6||','font-family:Arial; font-size:10px; padding:0px 1px; border-width: 1px 0 0 0;');
$nmk_design_5["59"]=array('','txtsmall2','','8|7|7','','','font-family:Arial; font-size:9px; padding:0px 1px;');
$nmk_design_5["60"]=array('','txtbox','','8|8|8','1|1|6','4||','font-size:11px;
padding:0 5px;
border-width:1px;
border-style:solid;
-moz-border-radius:7px;');
$nmk_design_5["61"]=array('','rss','','6|6|7','||','','font-size:8px; color:white;
border:1px solid black;
background:#FF6600;
letter-spacing:1px;
font-weight:bold;
padding:2px 3px 1px 3px;');
$nmk_design_5["62"]=array('','stabilo','','7||','4||','||','');
$nmk_design_5["63"]=array('','htab','','','','','float:left; width:48%; margin:0px 7px 0px 0; align:center;');
$nmk_design_5["64"]=array('','htab3','','','','','float:left; width:32%; margin:0px 7px 10px 0; align:center;');
$nmk_design_5["65"]=array('scroll','','','||','||','||','overflow:auto; height:400px;');
$nmk_design_5["66"]=array('board','','','||','||','4||','float:left; list-style-type:none; padding:4px; border-width:1px; border-style:solid; -moz-border-radius:7px;');
$nmk_design_5["67"]=array('board','','li','','','','');
$nmk_design_5["68"]=array('','taxonomy','li','|7|5','||','||','list-style-type:auto; padding:0 16px;');
$nmk_design_5["69"]=array('','imgl','','','','','float:left; margin:2px 4px 0px 0px;');
$nmk_design_5["70"]=array('','imgr','','','','','float:right; margin:2px 0px 0px 4px;');
$nmk_design_5["71"]=array('','clear','','','','','clear:left;');
$nmk_design_5["72"]=array('','console','','||','||','||','font-family:Courier New; font-weight:bold; line-height:18px; font-size:15px; color:#00ff00; background:black; border:4px double white; margin:10px; padding:10px;');
$nmk_design_5["73"]=array('line','','','8','','','margin:0px; padding:0px; text-align:center; font-family:Impact; font-size:10px; font-weight:lighter;');
$nmk_design_5["74"]=array('','lina','','','','','float:left; width:16px; color:#bbbbbb;');
$nmk_design_5["75"]=array('','linc','','8','','','float:left; width:16px;');
$nmk_design_5["76"]=array('','nb_pages','','','','','line-height:18px;');
$nmk_design_5["77"]=array('','nb_pages','a','','','4','padding:0 4px; border-style:solid; border-width:1px; -moz-border-radius:4px;');
$nmk_design_5["78"]=array('menuH','','','','','','width:100%; margin-top:0px; margin-bottom:10px; background:none; /*height:22px;*/');
$nmk_design_5["79"]=array('menuH','','a','','','','text-decoration: none; text-transform: capitalize; font-size: 1.1em; line-height:22px; padding:0 10px;');
$nmk_design_5["80"]=array('menuH','','ul','||','2||','||','');
$nmk_design_5["81"]=array('menuH','','li','7|7|5','2||','||','font-size:12px; width:auto;');
$nmk_design_5["82"]=array('menuH','','li a:hover','||','||','||','border:none;');
$nmk_design_5["83"]=array('menuH','','ul li','|7|5','||','||','margin-right:4px; opacity:1;');
$nmk_design_5["84"]=array('menuH','','li ul','||6','','','border:0; width:200px; margin: -22px 0 0 200px;');
$nmk_design_5["85"]=array('menuH','','li li','','','','border:0; width:200px; line-height:20px;');
$nmk_design_5["86"]=array('menuH','','li ul ul','','','','margin: -22px 0 0 200px;');
$nmk_design_5["87"]=array('menuH li:hover, #menuH li.sfhover','','','7||','3||','||','/*parents hors-hover*/');
$nmk_design_5["88"]=array('menuH li:hover a, #menuH li.sfhover a','','','7','','','/*parents*/');
$nmk_design_5["89"]=array('menuH li li:hover a, #menuH li li.sfhover a','','','7','','','/*restantes*/');
$nmk_design_5["90"]=array('menuH li li:hover a:hover, #menuH li li.sfhover a:hover','','','5','','','/*hover en cours*/');

?>