<?php 
return ['_'=>['block','module','param','title','condition','command','option','cache','hide','template','nobr','div'],
2=>['system','blocks','banner menu content footer','','','','','','','','',''],
3=>['system','design','2','','','','','','','','',''],
4=>['content','Page_titles','','','cat','','','','','','1',''],
5=>['content','rub_tags','','','cat','','','','','','',''],
6=>['content','LOAD','','','cat','','preview','','','','',''],
7=>['footer','credits','','','','','','1','','','1',''],
8=>['footer','Admin','','','','','','1','','','1',''],
9=>['footer','chrono','','','','','','','','','1',''],
11=>['footer','contact','','','','','','1','','','1',''],
15=>['content','prev_next','','','art','','','','','','1',''],
16=>['content','Page_titles','','','art','','','','','','1',''],
17=>['content','LOAD','','','art','','','','','','',''],
19=>['newsletter','articles','preview=false','tit','','articles','','','','','',''],
20=>['system','content','640','','','','','','','','',''],
21=>['system','template','','','','','','','1','','',''],
28=>['banner','search','Recherche','','','','right','','','','1',''],
29=>['menu','link','Home§home:picto','','','','','','','','1',''],
32=>['system','banner','640','','','','','','','','',''],
33=>['system','art_mod','related_arts§lié à,nrelated_by§lié par','title','','tabmods','','','1','','',''],
34=>['menu','categories','','','','','','','','','',''],
46=>['banner','Banner','','','','','','1','','','1',''],
47=>['system','apps','','','','','','','','','',''],
50=>['footer','log-out','','','','','','','','','',''],
51=>['content','recents','1','','home','cols','3','','','','',''],
52=>['content','MenusJ','close§x,n10/dossiers/cols/3:folders§Phénomènes,npriority=>1~nbdays=1/A la Une/cols/2:articles§24h,npriority=3~nbdays=7/Sujets sensibles/cols/3:articles§7j,npriority=4~nbdays=365~preview=false/***/cols/4:articles§1 an,n7-24/Les plus lus/cols/4:most_read§+ lus,nlinks/Sites/scroll:msql_links§urls,nrssurl/Rss-Player/:rss§rss,nSource des articles//scroll/nb:sources§sources,n1/Déjà vu/cols/4:deja_vu§vus,nfavs:plug§favoris,nemail/newsletter quotidienne:newsletter§newsletter,n:suggest§proposer,nhubs§hubs','','','','','','1','','',''],
53=>['','finder','','','','','','','','',''],
54=>['system','desktop','','','','','','','1','','',''],
55=>['content','articles','cat=public&priority=1','','home','articles','','','1','','',''],
56=>['content','connector','http://philum.fr/236:rss_read','','home','','article','','1','','',''],
57=>['content','finder','','','home','','shared------mini','','1','','',''],
59=>['content','chat','public','','home','','','','1','','',''],
60=>['content','login_popup','log','','','','','','1','','',''],
62=>['content','columns','contact,hour,chrono','','','','','','1','','',''],
64=>['content','add_art','','','','','44','','1','','',''],
65=>['lab','text','','','home','','','','','',''],
66=>['content','Wall','','Wall','','','','','1','','',''],
67=>['content','desktop_folder','cat=public','','','','','','1','','',''],
68=>['content','desktop_arts','','','','','','','1','','',''],
69=>['content','desktop_finder','','','','','','','1','','',''],
70=>['lab','msql_links','links','','home','','','','','','',''],
71=>['system','csscode','','','','','','','1','','',''],
72=>['lab','finder','','','home','','','','','',''],
74=>['menu','url','contact','','','','','','','','',''],
75=>['menu','conn','','','','','','','1','','',''],
76=>['system','popadmin','admin arts finder apps search batch addurl addart hub log cache design dev time','','','horizontal','pictos','','','','',''],
77=>['menu','user_menu','','','','','','','','',''],
78=>['menu','BLOCK','','','home','','','','','','']]; ?>