<<<<<<< HEAD
<?php //msql/public_maths
$r=["_menus_"=>['','col2','col3'],
"1"=>['&#8469;','entiers naturels','algÃÂ¨bre'],
"2"=>['&#8484;','entiers relatifs (positifs, nÃÂ©gatifs et nuls)','algÃÂ¨bre'],
"3"=>['&#8474;','nombres rationnels','algÃÂ¨bre'],
"4"=>['&#8477;','nombres rÃÂ©els','algÃÂ¨bre'],
"5"=>['&sum;','somme','algÃÂ¨bre'],
"6"=>['&Pi;','produit','algÃÂ¨bre'],
"7"=>['&#8720;','coproduit','algÃÂ¨bre'],
"8"=>['&#8710;','incrÃÂ©ment (delta)','algÃÂ¨bre'],
"9"=>['&ang;','angle','algÃÂ¨bre'],
"10"=>['&int;','intÃÂ©grale (aire)','algÃÂ¨bre'],
"11"=>['|','tel que','algÃÂ¨bre'],
"12"=>['&sim;','ÃÂ©quivalence','algÃÂ¨bre'],
"13"=>['&asymp;','approximation','algÃÂ¨bre'],
"14"=>['&#8771;','ÃÂ©quivalence d\'homotopie','algÃÂ¨bre'],
"15"=>['&cong;','isomorphisme','algÃÂ¨bre'],
"16"=>['&equiv;','congruence, ÃÂ©galitÃÂ© dÃÂ©finitionnelle','algÃÂ¨bre'],
"70"=>['=','ÃÂ©galitÃÂ© propositionnelle','algÃÂ¨bre'],
"17"=>['&rarr;','s\'applique tel que','algÃÂ¨bre'],
"18"=>['&#10236;','fonction de','lambda-calcul'],
"19"=>['&#10233;','implication','algÃÂ¨bre'],
"20"=>['&#10234;','ÃÂ©quivalence logique','algÃÂ¨bre'],
"21"=>['&forall;','tout','ensembles'],
"22"=>['&exist;','existence','ensembles'],
"23"=>['&#8708;','non-existence','ensembles'],
"24"=>['&isin;','appartient ÃÂ , est compris dans','ensembles'],
"25"=>['&notin;','n\'appartient pas, n\'est pas compris dans','ensembles'],
"26"=>['&ni;','contient, comprend','ensembles'],
"27"=>['&#8716;','ne contient pas, ne comprend pas','ensembles'],
"28"=>['&#8898;','intersection','ensembles'],
"29"=>['&#8899;','union','ensembles'],
"30"=>['&sub;','est un sous-ensemble de ; implication rÃÂ©ciproque (suppose qu\'il reste un objet hors de l\'inclusion)','ensembles'],
"71"=>['&sup;','contient le sous-ensemble, implication (suppose qu\'il reste un objet hors de l\'inclusion)','ensembles'],
"31"=>['&#8896;','conjonction (AND)','ensembles'],
"32"=>['&#8897;','disjonction (OR)','ensembles'],
"33"=>['&#8892;','nand','ensembles'],
"34"=>['&#8893;','nor','ensembles'],
"35"=>['ÃÂ¬','la nÃÂ©gation, n\'est pas','logiques'],
"36"=>['&#8868;','tautologie (vrai)','logiques'],
"37"=>['&perp;','contradiction (faux)','logiques'],
"38"=>['&#8866;','dÃÂ©montre que','logiques'],
"39"=>['&#8876;','ne dÃÂ©montre pas','logiques'],
"40"=>['&#8871;','il existe des modÃÂ¨les pour','algÃÂ¨bre'],
"41"=>['&#8872;','consÃÂ©quence logique','logiques'],
"42"=>['&#8741;','ou (boolÃÂ©en)','informatique'],
"43"=>['&&','et (boolÃÂ©en)','informatique'],
"44"=>['&#8608;','surjection','algÃÂ¨bre'],
"45"=>['&#8620;','immersion','algÃÂ¨bre'],
"46"=>['&#8614;','devient (algo)','lambda-calcul'],
"47"=>['&#8618;','injection','lambda-calcul'],
"48"=>['&#10868;','affectation (2x deux points-ÃÂ©gal)','logique modale'],
"49"=>['&#9744;','nÃÂ©cessitÃÂ© logique','logique modale'],
"50"=>['&#9209;','Cqfd','logique modale'],
"51"=>['&loz;','possibilitÃÂ© logique','logique modale'],
"52"=>['&there4;','par consÃÂ©quent (donc)','logique modale'],
"53"=>['&#8757;','parce que (cause)','logique modale'],
"54"=>['&uarr;','nand (nÃÂ©gation de conjonction)','ensembles'],
"55"=>['&darr;','nor (nÃÂ©gation de disjonction)','ensembles'],
"56"=>['&sim;','nÃÂ©gation logique','logique linÃÂ©aire'],
"57"=>['&#8788;','est dÃÂ©fini comme','logique linÃÂ©aire'],
"58"=>['&equiv;','ÃÂ©quivalence linÃÂ©aire (permet de joindre la LC et la LI)','logique linÃÂ©aire'],
"59"=>['&#8888;','devient (consommation des prÃÂ©dicats) = nÃÂ©gation linÃÂ©aire + disjonction multiplicative','logique linÃÂ©aire'],
"60"=>['&#8857;','nÃÂ©gation de disjonction exclusive','logique linÃÂ©aire'],
"61"=>['&oplus;','disjonction additive (tenseur, &asymp; \"ou\")','logique linÃÂ©aire'],
"62"=>['&otimes;','conjonction (tenseur, &asymp; \"et\")','logique linÃÂ©aire'],
"63"=>['&#8523;','disjonction exclusive (non-et = \"ou\")','logique linÃÂ©aire'],
"64"=>['&#8905;','produit semi-direct','logique linÃÂ©aire'],
"65"=>['&#8906;','produit semi-direct','logique linÃÂ©aire'],
"66"=>['!','factorielle (nombres rÃÂ©els possiblement infinis)','logique linÃÂ©aire'],
"67"=>['&#8888;','devient (consommation des prÃÂ©dicats) = nÃÂ©gation linÃÂ©aire + disjonction multiplicative','logique linÃÂ©aire'],
"68"=>['&#12501;','\"fu\" (objectif) [japonais Katakana]','logique linÃÂ©aire'],
"69"=>['&#12530;','\"wo\" (subjectif) [japonais Katakana]','logique linÃÂ©aire']]; ?>
=======
<?php //philum/msql/public_maths
$r=["_menus_"=>['','col2','col3'],1=>['&#8469;','entiers naturels','alg�bre'],2=>['&#8484;','entiers relatifs (positifs, n�gatifs et nuls)','alg�bre'],3=>['&#8474;','nombres rationnels','alg�bre'],4=>['&#8477;','nombres r�els','alg�bre'],5=>['&sum;','somme','alg�bre'],6=>['&Pi;','produit','alg�bre'],7=>['&#8720;','coproduit','alg�bre'],8=>['&#8710;','incr�ment (delta)','alg�bre'],9=>['&ang;','angle','alg�bre'],10=>['&int;','int�grale (aire)','alg�bre'],11=>['|','tel que','alg�bre'],12=>['&sim;','�quivalence','alg�bre'],13=>['&asymp;','approximation','alg�bre'],14=>['&#8771;','�quivalence d\'homotopie','alg�bre'],15=>['&cong;','isomorphisme','alg�bre'],16=>['&equiv;','congruence, �galit� d�finitionnelle','alg�bre'],70=>['=','�galit� propositionnelle','alg�bre'],17=>['&rarr;','s\'applique tel que','alg�bre'],18=>['&#10236;','fonction de','lambda-calcul'],19=>['&#10233;','implication','alg�bre'],20=>['&#10234;','�quivalence logique','alg�bre'],21=>['&forall;','tout','ensembles'],22=>['&exist;','existence','ensembles'],23=>['&#8708;','non-existence','ensembles'],24=>['&isin;','appartient �, est compris dans','ensembles'],25=>['&notin;','n\'appartient pas, n\'est pas compris dans','ensembles'],26=>['&ni;','contient, comprend','ensembles'],27=>['&#8716;','ne contient pas, ne comprend pas','ensembles'],28=>['&#8898;','intersection','ensembles'],29=>['&#8899;','union','ensembles'],30=>['&sub;','est un sous-ensemble de ; implication r�ciproque (suppose qu\'il reste un objet hors de l\'inclusion)','ensembles'],71=>['&sup;','contient le sous-ensemble, implication (suppose qu\'il reste un objet hors de l\'inclusion)','ensembles'],31=>['&#8896;','conjonction (AND)','ensembles'],32=>['&#8897;','disjonction (OR)','ensembles'],33=>['&#8892;','nand','ensembles'],34=>['&#8893;','nor','ensembles'],35=>['�','la n�gation, n\'est pas','logiques'],36=>['&#8868;','tautologie (vrai)','logiques'],37=>['&perp;','contradiction (faux)','logiques'],38=>['&#8866;','d�montre que','logiques'],39=>['&#8876;','ne d�montre pas','logiques'],40=>['&#8871;','il existe des mod�les pour','alg�bre'],41=>['&#8872;','cons�quence logique','logiques'],42=>['&#8741;','ou (bool�en)','informatique'],43=>['&&','et (bool�en)','informatique'],44=>['&#8608;','surjection','alg�bre'],45=>['&#8620;','immersion','alg�bre'],46=>['&#8614;','devient (algo)','lambda-calcul'],47=>['&#8618;','injection','lambda-calcul'],48=>['&#10868;','affectation (2x deux points-�gal)','logique modale'],49=>['&#9744;','n�cessit� logique','logique modale'],50=>['&#9209;','Cqfd','logique modale'],51=>['&loz;','possibilit� logique','logique modale'],52=>['&there4;','par cons�quent (donc)','logique modale'],53=>['&#8757;','parce que (cause)','logique modale'],54=>['&uarr;','nand (n�gation de conjonction)','ensembles'],55=>['&darr;','nor (n�gation de disjonction)','ensembles'],56=>['&sim;','n�gation logique','logique lin�aire'],57=>['&#8788;','est d�fini comme','logique lin�aire'],58=>['&equiv;','�quivalence lin�aire (permet de joindre la LC et la LI)','logique lin�aire'],59=>['&#8888;','devient (consommation des pr�dicats) = n�gation lin�aire + disjonction multiplicative','logique lin�aire'],60=>['&#8857;','n�gation de disjonction exclusive','logique lin�aire'],61=>['&oplus;','disjonction additive (tenseur, &asymp; \"ou\")','logique lin�aire'],62=>['&otimes;','conjonction (tenseur, &asymp; \"et\")','logique lin�aire'],63=>['&#8523;','disjonction exclusive (non-et = \"ou\")','logique lin�aire'],64=>['&#8905;','produit semi-direct','logique lin�aire'],65=>['&#8906;','produit semi-direct','logique lin�aire'],66=>['!','factorielle (nombres r�els possiblement infinis)','logique lin�aire'],67=>['&#8888;','devient (consommation des pr�dicats) = n�gation lin�aire + disjonction multiplicative','logique lin�aire'],68=>['&#12501;','\"fu\" (objectif) [japonais Katakana]','logique lin�aire'],69=>['&#12530;','\"wo\" (subjectif) [japonais Katakana]','logique lin�aire']];
>>>>>>> f9944c7ea72fa2701f1c5861573e53d415060ec7
