<<<<<<< HEAD
<?php //philum/msql/newsnet_citation_7
$r=["_menus_"=>['Sant� publique'],1=>['� Je ne remettrai � personne du poison, si on m\'en demande, ni ne prendrai l\'initiative d\'une telle suggestion. �
Serment d\'Hippocrate (-460//377)'],2=>['Article R4127-36 du Code de sant� publique: � Le consentement de la personne examin�e ou soign�e doit �tre recherch� dans tous les cas. Lorsque le malade, en �tat d\'exprimer sa volont�, refuse les investigations ou le traitement propos�, le m�decin doit respecter ce refus apr�s avoir inform� le malade de ses cons�quences �'],3=>['Code de Nuremberg (1947) : � le consentement du sujet humain est absolument essentiel. Le pacte international relatif aux droits civils et politiques a repris cette interdiction contre toute exp�rimentation involontaire, dans son texte de 1966 qui stipule : nul ne peut �tre soumis sans son consentement � une exp�rience m�dicale ou scientifique �'],4=>['D�claration de Gen�ve pour les m�decins (1948) : � Je respecterai l\'autonomie et la dignit� de mon patient. Je n\'utiliserai pas mes connaissances m�dicales pour enfreindre les droits humains et les libert�s civiques, m�me sous la contrainte. Je garderai le respect absolu de la vie humaine, d�s la conception. Je consid�rerai la sant� de mon patient comme mon premier souci �'],5=>['D�claration d\'Helsinki (1996) sign�e par 45 pays dont la France :
Article 25 : � La participation de personnes capables de donner un consentement �clair� � une recherche m�dicale doit �tre un acte volontaire. Aucune personne capable de donner son consentement �clair� ne peut �tre impliqu�e dans une recherche sans avoir donn� son consentement libre et �clair� �'],6=>['Convention d\'Oviedo (1997) sign�e par 29 pays dont la France) :
Article 5 : � Une intervention dans le domaine de la sant� ne peut �tre effectu�e qu\'apr�s que la personne concern�e y a donn� son consentement libre et �clair�. Cette personne re�oit pr�alablement une information ad�quate quant au but et � la nature de l\'intervention ainsi que quant � ses cons�quences et ses risques. La personne concern�e peut, � tout moment, librement retirer son consentement �'],7=>['Arr�t Salvetti (2002) : Aucun traitement m�dical n\'est obligatoire au sein de l\'Union europ�enne : � En tant que traitement m�dical non volontaire, la vaccination obligatoire constitue une ing�rence dans le droit au respect de la vie priv�e, garanti par l\'article 8 de la Convention europ�enne des droits de l\'homme et des libert�s fondamentales � (Arr�t Salvetti c/Italie-CEDH d�cision du 9 juillet 2002 ; n�42197/98)'],8=>['Code civil fran�ais :
Article 16-1 : � Chacun a le droit au respect de son corps. Le corps est inviolable �'],9=>['R�solution 2361 du Conseil de l\'Europe (28 janvier 2021) : Avis consultatif : l\'Assembl�e demande instamment aux �tats membres et � l\'Union europ�enne :
Article 731 : � De s\'assurer que les citoyennes et les citoyens sont inform�s que la vaccination n\'est pas obligatoire et que personne ne subit de pressions politiques, sociales ou autres pour se faire vacciner, s\'il ou elle ne souhaite pas le faire personnellement �'],10=>['R�solution 2361 du Conseil de l\'Europe (28 janvier 2021) : Avis consultatif : l\'Assembl�e demande instamment aux �tats membres et � l\'Union europ�enne :
Article 732 : � De veiller � ce que personne ne soit victime de discrimination pour ne pas avoir �t� vaccin�, en raison de risque potentiel pour la sant� ou pour ne pas vouloir se faire vacciner �']];
=======
<?php //msql/public_citation_7
$r=["_menus_"=>['SantÃ© publique'],
"1"=>['Â« Je ne remettrai Ã  personne du poison, si on m\'en demande, ni ne prendrai l\'initiative d\'une telle suggestion. Â»
Serment d\'Hippocrate (-460//377)'],
"2"=>['Article R4127-36 du Code de santÃ© publique: Â« Le consentement de la personne examinÃ©e ou soignÃ©e doit Ãªtre recherchÃ© dans tous les cas. Lorsque le malade, en Ã©tat d\'exprimer sa volontÃ©, refuse les investigations ou le traitement proposÃ©, le mÃ©decin doit respecter ce refus aprÃ¨s avoir informÃ© le malade de ses consÃ©quences Â»'],
"3"=>['Code de Nuremberg (1947) : Â« le consentement du sujet humain est absolument essentiel. Le pacte international relatif aux droits civils et politiques a repris cette interdiction contre toute expÃ©rimentation involontaire, dans son texte de 1966 qui stipule : nul ne peut Ãªtre soumis sans son consentement Ã  une expÃ©rience mÃ©dicale ou scientifique Â»'],
"4"=>['DÃ©claration de GenÃ¨ve pour les mÃ©decins (1948) : Â« Je respecterai l\'autonomie et la dignitÃ© de mon patient. Je n\'utiliserai pas mes connaissances mÃ©dicales pour enfreindre les droits humains et les libertÃ©s civiques, mÃªme sous la contrainte. Je garderai le respect absolu de la vie humaine, dÃ¨s la conception. Je considÃ©rerai la santÃ© de mon patient comme mon premier souci Â»'],
"5"=>['DÃ©claration d\'Helsinki (1996) signÃ©e par 45 pays dont la France :
Article 25 : Â« La participation de personnes capables de donner un consentement Ã©clairÃ© Ã  une recherche mÃ©dicale doit Ãªtre un acte volontaire. Aucune personne capable de donner son consentement Ã©clairÃ© ne peut Ãªtre impliquÃ©e dans une recherche sans avoir donnÃ© son consentement libre et Ã©clairÃ© Â»'],
"6"=>['Convention d\'Oviedo (1997) signÃ©e par 29 pays dont la France) :
Article 5 : Â« Une intervention dans le domaine de la santÃ© ne peut Ãªtre effectuÃ©e qu\'aprÃ¨s que la personne concernÃ©e y a donnÃ© son consentement libre et Ã©clairÃ©. Cette personne reÃ§oit prÃ©alablement une information adÃ©quate quant au but et Ã  la nature de l\'intervention ainsi que quant Ã  ses consÃ©quences et ses risques. La personne concernÃ©e peut, Ã  tout moment, librement retirer son consentement Â»'],
"7"=>['ArrÃªt Salvetti (2002) : Aucun traitement mÃ©dical n\'est obligatoire au sein de l\'Union europÃ©enne : Â« En tant que traitement mÃ©dical non volontaire, la vaccination obligatoire constitue une ingÃ©rence dans le droit au respect de la vie privÃ©e, garanti par l\'article 8 de la Convention europÃ©enne des droits de l\'homme et des libertÃ©s fondamentales Â» (ArrÃªt Salvetti c/Italie-CEDH dÃ©cision du 9 juillet 2002 ; nÂ°42197/98)'],
"8"=>['Code civil franÃ§ais :
Article 16-1 : Â« Chacun a le droit au respect de son corps. Le corps est inviolable Â»'],
"9"=>['RÃ©solution 2361 du Conseil de l\'Europe (28 janvier 2021) : Avis consultatif : l\'AssemblÃ©e demande instamment aux Ãtats membres et Ã  l\'Union europÃ©enne :
Article 731 : Â« De s\'assurer que les citoyennes et les citoyens sont informÃ©s que la vaccination n\'est pas obligatoire et que personne ne subit de pressions politiques, sociales ou autres pour se faire vacciner, s\'il ou elle ne souhaite pas le faire personnellement Â»'],
"10"=>['RÃ©solution 2361 du Conseil de l\'Europe (28 janvier 2021) : Avis consultatif : l\'AssemblÃ©e demande instamment aux Ãtats membres et Ã  l\'Union europÃ©enne :
Article 732 : Â« De veiller Ã  ce que personne ne soit victime de discrimination pour ne pas avoir Ã©tÃ© vaccinÃ©, en raison de risque potentiel pour la santÃ© ou pour ne pas vouloir se faire vacciner Â»']]; ?>
>>>>>>> c3133bed7b5cef8cf040b043d741a1c96370c55d
