<<<<<<< HEAD
<?php //msql/newsnet_citation_10
$r=["_menus_"=>['Trait� sur l\'Antarctique'],
"1"=>['Article 1 : Seules les activit�s pacifiques sont autoris�es dans l\'Antarctique. Sont interdites,entre autres, toutes mesures de caract�re militaire telles que l\'�tablissement de bases, la construction de fortifications, les man&oelig;uvres, ainsi que les essais d\'armes de toutes sortes.'],
"2"=>['Article 1 (suite) : Le pr�sent Trait� ne s\'oppose pas � l\'emploi de personnel ou de mat�riel militaire pour la recherche scientifique ou pour toute autre fin pacifique.'],
"3"=>['Article 2 : les Parties Contractantes conviennent de proc�der, dans toute la mesure du possible :a) � l\'�change de renseignements relatifs aux programmes scientifiques dans l\'Antarctique,afin d\'assurer au maximum l\'�conomie des moyens et le rendement des op�rations ; b) � des �changes de personnel scientifique entre exp�ditions et stations dans cette r�gion ; c) � l\'�change des observations et des r�sultats scientifiques obtenus dans l\'Antarctique qui seront rendus librement disponibles.'],
"4"=>['Article 2 (suite) : Dans l\'application de ces dispositions, la coop�ration dans les relations de travail avec les Institutions Sp�cialis�es des Nations Unies et les autres organisations internationales pour lesquelles l\'Antarctique offre un int�r�t scientifique ou technique, sera encourag�e par tous les moyens.'],
"5"=>['Article 4 : 1) renonciation � ses droits de souverainet� territoriale. 2) abandon total ou partiel d\'une base de revendication de souverainet� territoriale dans l\'Antarctique. 3) portant atteinte � la position de chaque Partie toute revendication de souverainet� territoriale de tout autre Etat.'],
"6"=>['Article 5 : Toute explosion nucl�aire dans l\'Antarctique est interdite, ainsi que l\'�limination dans cette r�gion de d�chets radioactifs.']];
=======
<?php //msql/public_citation_10
$r=["_menus_"=>['TraitÃ© sur l\'Antarctique'],
"1"=>['Article 1 : Seules les activitÃ©s pacifiques sont autorisÃ©es dans l\'Antarctique. Sont interdites,entre autres, toutes mesures de caractÃ¨re militaire telles que l\'Ã©tablissement de bases, la construction de fortifications, les man&oelig;uvres, ainsi que les essais d\'armes de toutes sortes.'],
"2"=>['Article 1 (suite) : Le prÃ©sent TraitÃ© ne s\'oppose pas Ã  l\'emploi de personnel ou de matÃ©riel militaire pour la recherche scientifique ou pour toute autre fin pacifique.'],
"3"=>['Article 2 : les Parties Contractantes conviennent de procÃ©der, dans toute la mesure du possible :a) Ã  l\'Ã©change de renseignements relatifs aux programmes scientifiques dans l\'Antarctique,afin d\'assurer au maximum l\'Ã©conomie des moyens et le rendement des opÃ©rations ; b) Ã  des Ã©changes de personnel scientifique entre expÃ©ditions et stations dans cette rÃ©gion ; c) Ã  l\'Ã©change des observations et des rÃ©sultats scientifiques obtenus dans l\'Antarctique qui seront rendus librement disponibles.'],
"4"=>['Article 2 (suite) : Dans l\'application de ces dispositions, la coopÃ©ration dans les relations de travail avec les Institutions SpÃ©cialisÃ©es des Nations Unies et les autres organisations internationales pour lesquelles l\'Antarctique offre un intÃ©rÃªt scientifique ou technique, sera encouragÃ©e par tous les moyens.'],
"5"=>['Article 4 : 1) renonciation Ã  ses droits de souverainetÃ© territoriale. 2) abandon total ou partiel d\'une base de revendication de souverainetÃ© territoriale dans l\'Antarctique. 3) portant atteinte Ã  la position de chaque Partie toute revendication de souverainetÃ© territoriale de tout autre Etat.'],
"6"=>['Article 5 : Toute explosion nuclÃ©aire dans l\'Antarctique est interdite, ainsi que l\'Ã©limination dans cette rÃ©gion de dÃ©chets radioactifs.']]; ?>
>>>>>>> c3133bed7b5cef8cf040b043d741a1c96370c55d
