<<<<<<< HEAD
<?php //msql/newsnet_citation_5
$r=["_menus_"=>['Principes des Nations Unies'],
"1"=>['Article 2.1 - L\'Organisation des Nations Unies et ses Membres, dans la poursuite des buts énoncés à l\' Article 1, doivent agir conformément aux principes suivants :'],
"2"=>['Article 2.2 - L\'Organisation est fondée sur le principe de l\'égalité souveraine de tous ses Membres.'],
"3"=>['Article 2.3 - Les Membres de l\'Organisation, afin d\'assurer à tous la jouissance des droits et avantages résultant de leur qualité de Membre, doivent remplir de bonne foi les obligations qu\'ils ont assumées aux termes de la présente Charte.'],
"4"=>['Article 2.4 - Les Membres de l\'Organisation règlent leurs différends internationaux par des moyens pacifiques, de telle manière que la paix et la sécurité internationales ainsi que la justice ne soient pas mises en danger.'],
"5"=>['Article 2.5 - Les Membres de l\'Organisation s\'abstiennent, dans leurs relations internationales, de recourir à la menace ou à l\'emploi de la force, soit contre l\'intégrité territoriale ou l\'indépendance politique de tout État, soit de toute autre manière incompatible avec les buts des Nations Unies.'],
"6"=>['Article 2.5 - Les Membres de l\'Organisation donnent à celle-ci pleine assistance dans toute action entreprise par elle conformément aux dispositions de la présente Charte et s\'abstiennent de prêter assistance à un État contre lequel l\'Organisation entreprend une action préventive ou coercitive.'],
"7"=>['Article 2.6 - L\'Organisation fait en sorte que les États qui ne sont pas Membres des Nations Unies agissent conformément à ces principes dans la mesure nécessaire au maintien de la paix et de la sécurité internationales.'],
"8"=>['Article 2.7 - Aucune disposition de la présente Charte n\'autorise les Nations Unies à intervenir dans des affaires qui relèvent essentiellement de la compétence nationale d\'un État ni n\'oblige les Membres à soumettre des affaires de ce genre à une procédure de règlement aux termes de la présente Charte; toutefois, ce principe ne porte en rien atteinte à l\'application des mesures de coercition prévues au Chapitre VII.'],
"9"=>['Article 106 - En attendant l\'entrée en vigueur des accords spéciaux visés à l\'article 43* qui, de l\'avis du Conseil de sécurité, lui permettent de commencer à exercer ses responsabilités en vertu de l\'article 42*, les parties à la déclaration des quatre nations, signée à Moscou le 30 octobre 1943, et la France, conformément aux dispositions du paragraphe 5 de ladite déclaration, se consulteront et, selon que de besoin, avec d\'autres Membres de l\'Organisation des Nations unies en vue d\'une action commune au nom de l\'Organisation qui pourra être nécessaire dans le but de maintenir la paix et la sécurité internationales.']];
=======
<?php //msql/public_citation_5
$r=["_menus_"=>['Principes des Nations Unies'],
"1"=>['Article 2.1 - L\'Organisation des Nations Unies et ses Membres, dans la poursuite des buts Ã©noncÃ©s Ã  l\' Article 1, doivent agir conformÃ©ment aux principes suivants :'],
"2"=>['Article 2.2 - L\'Organisation est fondÃ©e sur le principe de l\'Ã©galitÃ© souveraine de tous ses Membres.'],
"3"=>['Article 2.3 - Les Membres de l\'Organisation, afin d\'assurer Ã  tous la jouissance des droits et avantages rÃ©sultant de leur qualitÃ© de Membre, doivent remplir de bonne foi les obligations qu\'ils ont assumÃ©es aux termes de la prÃ©sente Charte.'],
"4"=>['Article 2.4 - Les Membres de l\'Organisation rÃ¨glent leurs diffÃ©rends internationaux par des moyens pacifiques, de telle maniÃ¨re que la paix et la sÃ©curitÃ© internationales ainsi que la justice ne soient pas mises en danger.'],
"5"=>['Article 2.5 - Les Membres de l\'Organisation s\'abstiennent, dans leurs relations internationales, de recourir Ã  la menace ou Ã  l\'emploi de la force, soit contre l\'intÃ©gritÃ© territoriale ou l\'indÃ©pendance politique de tout Ã‰tat, soit de toute autre maniÃ¨re incompatible avec les buts des Nations Unies.'],
"6"=>['Article 2.5 - Les Membres de l\'Organisation donnent Ã  celle-ci pleine assistance dans toute action entreprise par elle conformÃ©ment aux dispositions de la prÃ©sente Charte et s\'abstiennent de prÃªter assistance Ã  un Ã‰tat contre lequel l\'Organisation entreprend une action prÃ©ventive ou coercitive.'],
"7"=>['Article 2.6 - L\'Organisation fait en sorte que les Ã‰tats qui ne sont pas Membres des Nations Unies agissent conformÃ©ment Ã  ces principes dans la mesure nÃ©cessaire au maintien de la paix et de la sÃ©curitÃ© internationales.'],
"8"=>['Article 2.7 - Aucune disposition de la prÃ©sente Charte n\'autorise les Nations Unies Ã  intervenir dans des affaires qui relÃ¨vent essentiellement de la compÃ©tence nationale d\'un Ã‰tat ni n\'oblige les Membres Ã  soumettre des affaires de ce genre Ã  une procÃ©dure de rÃ¨glement aux termes de la prÃ©sente Charte; toutefois, ce principe ne porte en rien atteinte Ã  l\'application des mesures de coercition prÃ©vues au Chapitre VII.'],
"9"=>['Article 106 - En attendant l\'entrÃ©e en vigueur des accords spÃ©ciaux visÃ©s Ã  l\'article 43* qui, de l\'avis du Conseil de sÃ©curitÃ©, lui permettent de commencer Ã  exercer ses responsabilitÃ©s en vertu de l\'article 42*, les parties Ã  la dÃ©claration des quatre nations, signÃ©e Ã  Moscou le 30 octobre 1943, et la France, conformÃ©ment aux dispositions du paragraphe 5 de ladite dÃ©claration, se consulteront et, selon que de besoin, avec d\'autres Membres de l\'Organisation des Nations unies en vue d\'une action commune au nom de l\'Organisation qui pourra Ãªtre nÃ©cessaire dans le but de maintenir la paix et la sÃ©curitÃ© internationales.']]; ?>
>>>>>>> c3133bed7b5cef8cf040b043d741a1c96370c55d
