<?php //public_defcons_tt
$r=["1"=>['::h1'],
"2"=>['title::h1'],
"3"=>['post-title entry-title::h3'],
"4"=>['post-title entry-title::h3'],
"5"=>['post-title::h2'],
"6"=>['post-title::h1'],
"7"=>['titre::h1'],
"8"=>['entry-title::h2'],
"9"=>['headline:itemprop:h1'],
"10"=>['name:itemprop:h1'],
"11"=>['titre-article::h1'],
"12"=>['divTitreArticle::'],
"13"=>['entry-title::h3'],
"14"=>['p1:id:h3'],
"15"=>['title::h1'],
"16"=>['title::h2'],
"17"=>['entry-title::h1'],
"18"=>['::h2'],
"19"=>['::h3'],
"20"=>['::title']]; ?>