<?php //msql/public_citation_9
$r=["_"=>['Code de Nuremberg'],
"1"=>['Article 1 : « Le consentement volontaire du sujet humain est absolument essentiel. Cela veut dire que la personne intéressée doit jouir de capacité légale totale pour consentir ; qu\'elle doit être laissée libre de décider, sans intervention de quelque élément de force de fraude, de contrainte, de supercherie, de duperie ou d\'autres formes de contraintes ou de coercition. »'],
"2"=>['Article 1 (suite) : « L\'obligation et la responsabilité d\'apprécier les conditions dans lesquelles le sujet donne son consentement incombent à la personne qui prend l\'initiative et la direction de ces expériences ou qui y travaille. Cette obligation et cette responsabilité s\'attachent à cette personne, qui ne peut les transmettre à nulle autre sans être poursuivie. »'],
"3"=>['Article 2 : « L\'expérience doit avoir des résultats pratiques pour le bien de la société impossibles à obtenir par d\'autres moyens ; elle ne doit pas être pratiquée au hasard et sans nécessité. »'],
"4"=>['Article 3 : « Les fondements de l\'expérience doivent résider dans les résultats d\'expériences antérieures faites sur des animaux, et dans la connaissance de la genèse de la maladie ou des questions de l\'étude, de façon à justifier par les résultats attendus l\'exécution de l\'expérience. »'],
"5"=>['Article 4 : « L\'expérience devrait être menée de manière à éviter toutes les souffrances et blessures physiques et mentales inutiles. »'],
"6"=>['Article 5 : « L\'expérience ne doit pas être tentée lorsqu\'il y a une raison a priori de croire qu\'elle entraînera la mort ou l\'invalidité du sujet, à l\'exception des cas où les médecins qui font les recherches servent eux-mêmes de sujets à l\'expérience. »'],
"7"=>['Article 6 : « Le degré de risque à prendre ne doit jamais dépasser celui déterminé par l\'importance humanitaire du problème à résoudre par l\'expérience. »'],
"8"=>['Article 7 : « On doit faire en sorte d\'écarter du sujet expérimental toute éventualité, si mince soit-elle, susceptible de provoquer des blessures, l\'invalidité ou la mort. »'],
"9"=>['Article 8 : « L\'expérience ne devrait être menée que par des personnes scientifiquement qualifiées. Le plus haut degré de compétence et de soin devrait être exigé à toutes les étapes de l\'expérience de ceux qui mènent ou s\'engagent dans l\'expérience. »'],
"10"=>['Article 9 : « L\'expérience ne devrait être menée que par des personnes scientifiquement qualifiées. Le plus haut degré de compétence et de soin devrait être exigé à toutes les étapes de l\'expérience de ceux qui mènent ou s\'engagent dans l\'expérience. »'],
"11"=>['Article 10 : « Le scientifique chargé de l\'expérience doit être prêt à l\'interrompre à tout moment, s\'il a une raison de croire que sa continuation pourrait entraîner des blessures, l\'invalidité ou la mort pour le sujet expérimental. »']]; ?>