<?php //msql/public_citation_7
$r=["_"=>['Santé publique'],
"1"=>['« Je ne remettrai à personne du poison, si on m\'en demande, ni ne prendrai l\'initiative d\'une telle suggestion. »
Serment d\'Hippocrate (-460//377)'],
"2"=>['Article R4127-36 du Code de santé publique: « Le consentement de la personne examinée ou soignée doit être recherché dans tous les cas. Lorsque le malade, en état d\'exprimer sa volonté, refuse les investigations ou le traitement proposé, le médecin doit respecter ce refus après avoir informé le malade de ses conséquences »'],
"3"=>['Code de Nuremberg (1947) : « le consentement du sujet humain est absolument essentiel. Le pacte international relatif aux droits civils et politiques a repris cette interdiction contre toute expérimentation involontaire, dans son texte de 1966 qui stipule : nul ne peut être soumis sans son consentement à une expérience médicale ou scientifique »'],
"4"=>['Déclaration de Genève pour les médecins (1948) : « Je respecterai l\'autonomie et la dignité de mon patient. Je n\'utiliserai pas mes connaissances médicales pour enfreindre les droits humains et les libertés civiques, même sous la contrainte. Je garderai le respect absolu de la vie humaine, dès la conception. Je considérerai la santé de mon patient comme mon premier souci »'],
"5"=>['Déclaration d\'Helsinki (1996) signée par 45 pays dont la France :
Article 25 : « La participation de personnes capables de donner un consentement éclairé à une recherche médicale doit être un acte volontaire. Aucune personne capable de donner son consentement éclairé ne peut être impliquée dans une recherche sans avoir donné son consentement libre et éclairé »'],
"6"=>['Convention d\'Oviedo (1997) signée par 29 pays dont la France) :
Article 5 : « Une intervention dans le domaine de la santé ne peut être effectuée qu\'après que la personne concernée y a donné son consentement libre et éclairé. Cette personne reçoit préalablement une information adéquate quant au but et à la nature de l\'intervention ainsi que quant à ses conséquences et ses risques. La personne concernée peut, à tout moment, librement retirer son consentement »'],
"7"=>['Arrêt Salvetti (2002) : Aucun traitement médical n\'est obligatoire au sein de l\'Union européenne : « En tant que traitement médical non volontaire, la vaccination obligatoire constitue une ingérence dans le droit au respect de la vie privée, garanti par l\'article 8 de la Convention européenne des droits de l\'homme et des libertés fondamentales » (Arrêt Salvetti c/Italie-CEDH décision du 9 juillet 2002 ; n°42197/98)'],
"8"=>['Code civil français :
Article 16-1 : « Chacun a le droit au respect de son corps. Le corps est inviolable »'],
"9"=>['Résolution 2361 du Conseil de l\'Europe (28 janvier 2021) : Avis consultatif : l\'Assemblée demande instamment aux États membres et à l\'Union européenne :
Article 731 : « De s\'assurer que les citoyennes et les citoyens sont informés que la vaccination n\'est pas obligatoire et que personne ne subit de pressions politiques, sociales ou autres pour se faire vacciner, s\'il ou elle ne souhaite pas le faire personnellement »'],
"10"=>['Résolution 2361 du Conseil de l\'Europe (28 janvier 2021) : Avis consultatif : l\'Assemblée demande instamment aux États membres et à l\'Union européenne :
Article 732 : « De veiller à ce que personne ne soit victime de discrimination pour ne pas avoir été vacciné, en raison de risque potentiel pour la santé ou pour ne pas vouloir se faire vacciner »']]; ?>