<<<<<<< HEAD
<?php //msql/newsnet_citation_11
$r=["_menus_"=>['Traité sur l\'Espace'],
"1"=>['Article 1 (1) : L\'exploration et l\'utilisation de l\'espace extra-atmosphérique, y compris la Lune et les autres corps célestes, doivent se faire pour le bien et dans l\'intérêt de tous les pays, quelque soit le stade de leur développement économique ou scientifique; elles sont l\'apanage de l\'humanité tout entière.'],
"2"=>['Article 1 (2) : L\'espace extra-atmosphérique, y compris la Lune et les autres corps célestes, peut être exploré et utilisé librement par tous les États sans aucune discrimination, dans des conditions d\'égalité et conformément au droit international, toutes les régions des corps célestes devant être librement accessibles.'],
"3"=>['Article 1 (3) : Les recherches scientifiques sont libres dans l\'espace extra-atmosphérique, y compris la Lune et les autres corps célestes, et les États doivent faciliter et encourager la coopération internationale dans ces recherches.'],
"4"=>['Article 2 : L\'espace extra-atmosphérique, y compris la Lune et les autres corps célestes, ne peut faire l\'objet d\'appropriation nationale par proclamation de souveraineté, ni par voied\'utilisation ou d\'occupation, ni par aucun autre moyen.'],
"5"=>['Article 3 : Les activités des États parties au Traité relatives à l\'exploration et à l\'utilisation de l\'espace extra-atmosphérique, y compris la Lune et les autres corps célestes, doivents\'effectuer conformément au droit international, y compris la Charte des Nations Unies,en vue de maintenir la paix et la sécurité internationales et de favoriser la coopération etla compréhension internationales.'],
"6"=>['Article 4 : Les États parties au Traité s\'engagent à ne mettre sur orbite autour de la Terre aucun objet porteur d\'armes nucléaires ou de tout autre type d\'armes de destruction massive, à ne pas installer de telles armes sur des corps célestes et à ne pas placer de telles armes, de toute autre manière, dans l\'espace extra-atmosphérique.'],
"7"=>['Article 4 (suite) : Tous les États parties au Traité utiliseront la Lune et les autres corps célestes exclusivement à des fins pacifiques. Sont interdits sur les corps célestes l\'aménagement de bases et installations militaires et de fortifications, les essais d\'armes de tous types et l\'exécution de man&oelig;uvres militaires. N\'est pas interdite l\'utilisation de personnel militaire à des fins de recherche scientifique ou à toute autre fin pacifique. N\'est pas interdite non plus l\'utilisation de tout équipement ou installation nécessaire à l\'exploration pacifique de la Lune et des autres corps célestes.'],
"8"=>['Article 5 : Les États parties au Traité considéreront les astronautes comme des envoyés de l\'humanité dans l\'espace extra-atmosphérique et leur prêteront toute l\'assistance possible en cas d\'accident, de détresse ou d\'atterrissage forcé sur le territoire d\'un autre État partie au Traité ou d\'amerrissage en haute mer. En cas d\'un tel atterrissage ou amerrissage, le retour des astronautes à l\'État d\'immatriculation de leur véhicule spatial devra être effectué promptement et en toute sécurité.'],
"9"=>['Article 5 (2) : Lorsqu\'ils poursuivront des activités dans l\'espace extra-atmosphérique et sur les corps célestes, les astronautes d\'un État partie au Traité prêteront toute l\'assistance possible aux astronautes des autres États parties au Traité.'],
"10"=>['Article 5 (3) : Les États parties au Traité porteront immédiatement à la connaissance des autres États parties au Traité ou du Secrétaire général de l\'Organisation des Nations Unies tout phénomène découvert par eux dans l\'espace extra-atmosphérique, y compris la Lune et les corps célestes, qui pourrait présenter un danger pour la vie ou la santé des astronautes.'],
"11"=>['Article 8 : L\'État partie au Traité sur le registre duquel est inscrit un objet lancé dans l\'espace extra-atmosphérique conservera sous sa juridiction et son contrôle ledit objet et tout le personnel dudit objet, alors qu\'ils se trouvent dans l\'espace extra-atmosphérique ou sur un corps céleste. Les droits de propriété sur les objets lancés dans l\'espace extra-atmosphérique, y compris les objets amenés ou construits sur
un corps céleste, ainsi que sur leurs éléments constitutifs, demeurent entiers lorsque ces objets ou éléments se trouvent dans l\'espace extra-atmosphérique ou sur un corps céleste, et lorsqu\'ils reviennent sur la Terre.']];
=======
<?php //msql/public_citation_11
$r=["_menus_"=>['TraitÃ© sur l\'Espace'],
"1"=>['Article 1 (1) : L\'exploration et l\'utilisation de l\'espace extra-atmosphÃ©rique, y compris la Lune et les autres corps cÃ©lestes, doivent se faire pour le bien et dans l\'intÃ©rÃªt de tous les pays, quelque soit le stade de leur dÃ©veloppement Ã©conomique ou scientifique; elles sont l\'apanage de l\'humanitÃ© tout entiÃ¨re.'],
"2"=>['Article 1 (2) : L\'espace extra-atmosphÃ©rique, y compris la Lune et les autres corps cÃ©lestes, peut Ãªtre explorÃ© et utilisÃ© librement par tous les Ã‰tats sans aucune discrimination, dans des conditions d\'Ã©galitÃ© et conformÃ©ment au droit international, toutes les rÃ©gions des corps cÃ©lestes devant Ãªtre librement accessibles.'],
"3"=>['Article 1 (3) : Les recherches scientifiques sont libres dans l\'espace extra-atmosphÃ©rique, y compris la Lune et les autres corps cÃ©lestes, et les Ã‰tats doivent faciliter et encourager la coopÃ©ration internationale dans ces recherches.'],
"4"=>['Article 2 : L\'espace extra-atmosphÃ©rique, y compris la Lune et les autres corps cÃ©lestes, ne peut faire l\'objet d\'appropriation nationale par proclamation de souverainetÃ©, ni par voied\'utilisation ou d\'occupation, ni par aucun autre moyen.'],
"5"=>['Article 3 : Les activitÃ©s des Ã‰tats parties au TraitÃ© relatives Ã  l\'exploration et Ã  l\'utilisation de l\'espace extra-atmosphÃ©rique, y compris la Lune et les autres corps cÃ©lestes, doivents\'effectuer conformÃ©ment au droit international, y compris la Charte des Nations Unies,en vue de maintenir la paix et la sÃ©curitÃ© internationales et de favoriser la coopÃ©ration etla comprÃ©hension internationales.'],
"6"=>['Article 4 : Les Ã‰tats parties au TraitÃ© s\'engagent Ã  ne mettre sur orbite autour de la Terre aucun objet porteur d\'armes nuclÃ©aires ou de tout autre type d\'armes de destruction massive, Ã  ne pas installer de telles armes sur des corps cÃ©lestes et Ã  ne pas placer de telles armes, de toute autre maniÃ¨re, dans l\'espace extra-atmosphÃ©rique.'],
"7"=>['Article 4 (suite) : Tous les Ã‰tats parties au TraitÃ© utiliseront la Lune et les autres corps cÃ©lestes exclusivement Ã  des fins pacifiques. Sont interdits sur les corps cÃ©lestes l\'amÃ©nagement de bases et installations militaires et de fortifications, les essais d\'armes de tous types et l\'exÃ©cution de man&oelig;uvres militaires. N\'est pas interdite l\'utilisation de personnel militaire Ã  des fins de recherche scientifique ou Ã  toute autre fin pacifique. N\'est pas interdite non plus l\'utilisation de tout Ã©quipement ou installation nÃ©cessaire Ã  l\'exploration pacifique de la Lune et des autres corps cÃ©lestes.'],
"8"=>['Article 5 : Les Ã‰tats parties au TraitÃ© considÃ©reront les astronautes comme des envoyÃ©s de l\'humanitÃ© dans l\'espace extra-atmosphÃ©rique et leur prÃªteront toute l\'assistance possible en cas d\'accident, de dÃ©tresse ou d\'atterrissage forcÃ© sur le territoire d\'un autre Ã‰tat partie au TraitÃ© ou d\'amerrissage en haute mer. En cas d\'un tel atterrissage ou amerrissage, le retour des astronautes Ã  l\'Ã‰tat d\'immatriculation de leur vÃ©hicule spatial devra Ãªtre effectuÃ© promptement et en toute sÃ©curitÃ©.'],
"9"=>['Article 5 (2) : Lorsqu\'ils poursuivront des activitÃ©s dans l\'espace extra-atmosphÃ©rique et sur les corps cÃ©lestes, les astronautes d\'un Ã‰tat partie au TraitÃ© prÃªteront toute l\'assistance possible aux astronautes des autres Ã‰tats parties au TraitÃ©.'],
"10"=>['Article 5 (3) : Les Ã‰tats parties au TraitÃ© porteront immÃ©diatement Ã  la connaissance des autres Ã‰tats parties au TraitÃ© ou du SecrÃ©taire gÃ©nÃ©ral de l\'Organisation des Nations Unies tout phÃ©nomÃ¨ne dÃ©couvert par eux dans l\'espace extra-atmosphÃ©rique, y compris la Lune et les corps cÃ©lestes, qui pourrait prÃ©senter un danger pour la vie ou la santÃ© des astronautes.'],
"11"=>['Article 8 : L\'Ã‰tat partie au TraitÃ© sur le registre duquel est inscrit un objet lancÃ© dans l\'espace extra-atmosphÃ©rique conservera sous sa juridiction et son contrÃ´le ledit objet et tout le personnel dudit objet, alors qu\'ils se trouvent dans l\'espace extra-atmosphÃ©rique ou sur un corps cÃ©leste. Les droits de propriÃ©tÃ© sur les objets lancÃ©s dans l\'espace extra-atmosphÃ©rique, y compris les objets amenÃ©s ou construits sur
un corps cÃ©leste, ainsi que sur leurs Ã©lÃ©ments constitutifs, demeurent entiers lorsque ces objets ou Ã©lÃ©ments se trouvent dans l\'espace extra-atmosphÃ©rique ou sur un corps cÃ©leste, et lorsqu\'ils reviennent sur la Terre.']]; ?>
>>>>>>> c3133bed7b5cef8cf040b043d741a1c96370c55d
