<?php 
return ['_'=>['function'],
'art'=>['[_BACK _AVATAR[_SEARCH|txtbox:css] [_NBARTS|txtnoir:css] [_DATE|txtsmall2:css] [_AUTHOR _SOURCE _LENGTH _PRIORITY _BTIM _TRACKS _OPT _LANG _PID|txtsmall:css]|[meta_ID:id]:header][_EDIT|right:css]rn_THUMB[_PARENT:h4][[_URL|_SUJ:url]:h1]rn_ARTEDIT_FLOAT[_ARTLANG _SOCIAL _WORDS _OPEN|grey right:css][_TAG|txtsmall:divc] [:clear][_MSG|[art_ID:id][justy:class]_JS:article]'],
'cat'=>['[[_THUMB[_TAG|txtsmall:divc]|row1 col1:divc]rn[[[_BACK _AVATAR[_SEARCH|txtbox:css] [_NBARTS|txtnoir:css] [_DATE|txtsmall2:css] [_AUTHOR _SOURCE _LENGTH _PRIORITY _BTIM _TRACKS _OPT _LANG _PID|txtsmall:css]|[meta_ID:id]:div]rn[_PARENT:h4]rn[_EDIT|right:css][[_URL|_SUJ:url]:h2]rn[_ARTLANG _SOCIAL _WORDS _OPEN|[grey:class][text-align:right:style]:div]:header]rn_FLOAT_ARTEDIT[_MSG|[art_ID:id][panel:class]:article]|row1 col2:divc]rn|grid-art:divc][:clear]'],
'cat2'=>['[[_THUMB[_TAG|txtsmall:divc]|row1 col1:divc]rn[[[_BACK _AVATAR[_SEARCH|txtbox:css] [_NBARTS|txtnoir:css] [_DATE|txtsmall2:css] [_AUTHOR _SOURCE _LENGTH _PRIORITY _BTIM _TRACKS _OPT _LANG _PID|txtsmall:css]|[meta_ID:id]:div]rn[_PARENT:h4]rn[_EDIT|right:css][[_JURL|_SUJ:jurl]:h2]rn[_ARTLANG _SOCIAL _WORDS _OPEN|[grey:class][text-align:right:style]:div]:header]rn_FLOAT_ARTEDIT[_MSG|[art_ID:id][panel:class]:article]|row1 col2:divc]rn|grid-art:divc][:clear]'],
'read'=>['[_THUMB [_AVATAR[_SEARCH|txtbox:css]_BACK [_DATE|txtsmall2:css] [_NBARTS|txtnoir:css] [_AUTHOR _SOURCE _LENGTH _PRIORITY _BTIM _TRACKS _OPT _LANG _PID|txtsmall:css]|[meta_ID:id]:div]rn[_PARENT:h4][_EDIT|right:css][[_URL|_SUJ:url]:h1]rn[_ARTLANG _SOCIAL _WORDS _OPEN|grey right:css][:clear]rn_FLOAT[_TAG|txtsmall:divc]:header]rn_ARTEDIT[_MSG[:clear]|[art_ID:id][justy:class]_JS:article]'],
'tracks'=>['[trk_ID:anchor][_EDIT|[float:right;:style]:div]rn[_AVATAR [_AUTHOR|txtsmall:css][:br]rn[_DATE|txtsmall2:css]|[imgl:class][width:60px; padding:0;:style]:div]rn[_MSG[:clear]|[_STY:class][margin-left:60px;:style]:div]'],
'simple'=>['[[_EDIT|right:css]_BACK _AUTHOR [_DATE|txtsmall2:css] [_NBARTS|txtnoir:css] _LANGrn[[_URL|_SUJ:url]:h2]|[meta_ID:id]:header]_ARTEDITrn_FLOAT[_MSG[:clear]|[art_ID:id][justy:class]:article]'],
'rss'=>['[[_URL|_SUJ:url]|h2:html]rn[[_OPT|txtsmall2:css]|[float:right:style]:div]rn[_DATE|txtsmall:css] rn[_ARTEDIT|[reponse_ID:id]:div]rn	[[_THUMB_MSG|[panel justy:class]:div]rn	|[art_ID:id][_STY:class]:div]'],
'twitter'=>['[[_AUTHOR|txtsmall:css][:br]rn_SUJ[:br][_DATE|txtsmall2:css]|[twitter:class][_ID:id]:div]'],
'gsm'=>['[_ID:anchor] [_EDIT|[text-align:right;:style]:div] [_SEARCH|txtred:css][_EDITART|[reponse_ID:id]:div] [_BACK|txtx:css] [Par: _AUTHOR|txtsmall:css] [ [ [[_DAY|d:date][:br][_DAY|M:date]|[txtdate:class]:div] [:br][:br] [_TRACKS|txtx:css][:br][_TAG|txtsmall:css] [_USERTAGS|txtsmall:css] [_OPT|txtsmall2:css] |[gsm_element:class]:div] [_THUMB |[float:left; width:230px;:style]:div] [[_URL_SUJ|:url]|h2:html] [ _MSG [:br][:br] [[_URL|Lire la suite:url]|[txtsmall:class][text-align:right:style]:div] |[justy:class]:div] |[art_ID:id][_STY panel:class] [_ADDCLR:style]:div] [ |[clear:class]:div]']]; ?>